ten-protocol/go-ten

go/common/gethutil/gethutil.go, go/host/enclave/state.go, go/host/enclave/state_test.go, go/host/host.go
Added a simple state machine that tracks the state of an enclave so host can change its behaviour accordingly. This will be within the enclave-guardian package but getting it in early because it makes the PRs for the other services easier.
Add an enclave status tracker that gets updated based on the hosts data about the enclave. Not being used for much yet but eventually it drives and guards all behaviour of host towards enclave.
=> enclave-guardian: add enclave status tracker to host

go/host/host.go, go/host/l1/blockrepository.go
We see a lot of messages early in the host lifecycle that look like `could not find block after latest canon ancestor, height=5 - not found`
This happens when the block streaming is getting going and it doesn't realise the enclave is up-to-date so it keeps asking for the next block which isn't there yet.
Only log for unexpected errors in that method.
=> Reduce log noise from block catchup at startup

go/host/host.go, integration/simulation/simulation_in_mem_test.go
Stefan spotted that I wasn't locking the mutex when new blocks arrive, only when processing catch-up blocks.
=> Fix missing mutex lock for block submission

go/common/host/host_healthcheck.go, go/common/host/services.go, go/host/host.go, go/host/l1/blockrepository.go
We want the host to be a container that wires together a bunch of services running that depend on each other. It shouldn't have much logic itself.
So it's useful for the host to be able to treat these services the same as each other for starting/stopping/health checks.
Add a way to register services on the host. Make start/stop loop through services that are registered.
=> Setup generic services in the host

testnet/docker-compose.local.yml, testnet/testnet-local-build_images.sh
To be able to build local images for testnet
Fixed some relative paths
=> fix paths for testnet local build

go/common/host/services.go, go/common/subscription/subscription.go, go/common/subscription/subscription_test.go, go/host/l1/blockrepository.go
A few of these services in host refactor need to subscribe to be notified of things, a basic subscription manager helps keep the code for that tidied away and means they don't need to worry about thread-safety.
Add a generic sub/unsub subscription manager, use it for block repository.
=> Add subscription manager for sub/unsub

.github/workflows/manual-upgrade-testnet-l2.yml
To re-enable the nightly upgrade on schedule
=> Re-enable the upgrade

testnet/docker-compose.local.yml, testnet/testnet-local-build_images.sh, tools/walletextension/container_run.sh
Part of https://github.com/obscuronet/obscuro-internal/issues/1941 
Makes sure the container joins the node network (for docker connectivity) and a few other minor blips.
=> Tweak WE/OG start flags for local testnet

go/common/host/services.go, go/host/host.go, go/host/l1/blockrepository.go, integration/obscuroscan/obscuroscan_test.go
We have an edgecase after returning to an L1 fork where using the state machine to decide what block to send next is a bit fragile. We should instead try consecutive canonical blocks from the LCA until we get to one that the enclave hasn't seen
Also, this disables a flaky obscuroscan test until we get a chance to make it more robust.
=> Try feeding consecutive blocks if failing after a fork

go/host/host.go
Seeing issues with node restart tests that suggested host was failing to stop. In particular I saw failure to stop enclave with client causing an error which meant the host didn't finish stopping.
Log errors while stopping rather than returning them.
=> fix issue with host failing to stop after error

.github/workflows/manual-deploy-testnet-faucet.yml, .github/workflows/manual-upgrade-testnet-l2.yml
Calling a re-usable workflow from a schedule _should_ pass in the testnet_type in the inputs context according to all documentation, but it doesn't seem to be working. There are reported bugs of if conditions in re-usable workflows called from a workflow_call, so I want to put in a little more logging and up the schedule to try and fix today.
=> Put in some logging

go/host/rpc/clientapi/client_api_scan.go, go/obsclient/obsclient.go, go/rpc/client.go, integration/obscuroscan/obscuroscan_test.go, tools/obscuroscan_v2/backend/obscuroscan_backend.go, tools/obscuroscan_v2/backend/webserver/webserver.go, tools/obscuroscan_v2/frontend/src/components/SummaryItem.vue, tools/obscuroscan_v2/frontend/src/lib/config.dev.js, tools/obscuroscan_v2/frontend/src/lib/config.js, tools/obscuroscan_v2/frontend/src/stores/batchStore.js, tools/obscuroscan_v2/frontend/src/stores/counterStore.js, tools/obscuroscan_v2/frontend/src/stores/priceStore.js, tools/obscuroscan_v2/frontend/src/views/HomeView.vue
https://github.com/obscuronet/obscuro-internal/issues/1962
https://github.com/obscuronet/obscuro-internal/issues/1965
=> Hook obscuro scan other endpoints

.github/workflows/manual-deploy-testnet-faucet.yml, .github/workflows/manual-upgrade-testnet-l2.yml
Fixes to get the workflow_call working when the calling workflow is started from a schedule. This required the following;
1. The faucet workflow should use the inputs context, and not inherit the events.inputs context as this is only set when the calling workflow is started from a workflow_dispatch (i.e. manually through the portal). The inputs context is shared across both workflow_dispatch and workflow_calls. 
2. The upgrade workflow has to have two streams for the faucet deployment, and for sending the repository dispatch to the E2E tests. It looks like the build output approach cannot be used for a reason that is unclear to me (perhaps a bug in the workflow actions) - it is not passed through when referenced as an input in the workflow call.
=> More fixes to get the faucet deployment to work when the upgrade workflow is initiated from a schedule event. 

go/host/rpc/enclaverpc/enclave_client.go
Some errors were being swallowed in transit by the enclave RPC communication.
=> Ensure Error fields on encl RPC resp are captured

go/enclave/storage/storage.go
the bigcache library only caches `[]byte`.
This PR handles serialisiation and deserialisation
=> fix cache for blocks and batches

go/common/types.go, go/enclave/storage/storage.go
The fork log message is helpful for debugging but it's logging the block pointers instead of their hashes, like:
`INFO [08-01|14:19:36.896] Fork. &{NewCanonical:0x140873ccab0 OldCanonical:0x140873ccb40 CommonAncestor:0x140873ccbd0 CanonicalPath:[] NonCanonicalPath:[0x79e235428ddedfca0eb3c7ee2bf96a1b7328754d0509bc7cc7b4e9006cec954e]}. component=test_log    node_id=0 component=enclave`
After the change the message logs like:
`INFO [08-01|15:27:57.585] Fork. ChainFork{NewCanonical: 0xd434e10119b1e4d4cd98cc4ea432b663005d90ff1d45ba1f2d13612e0f2e8343, OldCanonical: 0xc10e9a09b6ee651e518ecb637f34bd88c9f3b2d7ff33fdd3e7e98e68ae7fe487, CommonAncestor: 0xabaac0fd96bc9fe9a3c143b66de4f862f935cfbf71cfb3975dca1f816839052c, CanonicalPath: [], NonCanonicalPath: …
=> Log block hash rather than pointer for fork debug

.github/workflows/build-pr.yml
We regularly fill up our usage on actions storage and it looks like the ci-logs are the culprit. This PR only uploads the logs as artifacts on failure, and only with a retention of 1 day.
=> Reduce retention to 1 day on failure only

go/host/enclave/guardian.go
Sometimes we hit the following panic while running:
`enclave service is not a validator but validator was requested!`
This is caused by the host attempting to submit a batch to a sequencer enclave. This seems to be caused by the host briefly flickering into an L2 catch-up state because it thinks it is behind on batches (which shouldn't be possible for the sequencer).
Avoid L2 catchup in the sequencer host so we do not panic. Instead log a warning so we  have visibility to better understand why this is happening.
=> Avoid panics when sequencer host thinks it is behind the enclave

go/enclave/enclave_test.go, go/enclave/storage/enclavedb/batch.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql, integration/networktest/runner.go
We were hitting errors because couldn't find state for unexecuted batches.
Needed to exclude unexecuted batches from data queries.
=> Fix bug with unexecuted batch data

tools/walletextension/api/routes.go, tools/walletextension/container/walletextension_container.go, tools/walletextension/wallet_extension.go
In the Obscuro Gateway userID is generated as hash of a publicKey.
It is stored in the database (and returned from it) as []byte, however users use hex-encoded version of it in the query parameter and the same hex format is used also in UserAccountManager `make(map[string]*accountmanager.AccountManager)`.
There is a special userID (`defaultUser`) which is needed to support old Wallet Extension endpoints (for now - and will be removed in the future). It is saved as a constant string in the code (and is also added to the database as all other users).  This string also needs to be hex encoded to standardise things and avoid additional if statements in multiple places for that default user.
There was a mistake in the encoding when loading all clients at the startup (which caused them to have …
=> Fix encoding of userID

integration/eth2network/eth2_network.go
I saw a goroutine waiting for merge in one of the thread dumps in a timed out build.
Not sure it's a problem (and if it is, not sure it's the only problem), but seems worthwhile to rule it out with a timeout.
Also, changed the condition to `<= 7` rather than `!= 7`, I think this is the intention and just wanted to rule out any edgecase if timings mean it skipped a number.
=> Add timeout to wait for L1 merge

go/enclave/enclave.go
The enclave reports in its status to the host what the latest L2 batch it has received is. But we recently updated that head batch query used for the status to only include executed batches.
So the host gets this status and thinks the enclave has lost the batch it just sent somehow and puts it into catchup. This means the host is constantly flickering to catchup unnecessarily.
Use current seq number for the status reporting instead of head batch.
=> Enclave should report latest batch received even if unexecuted

go/host/enclave/state.go
testnet startup was taking a long time because it had to submit blocks from L1 genesis.
There was a bug where the enclave status before it had processed a block would reset the hash to start catch-up from.
Make it so the L1 head hash is never overwritten with an empty hash.
=> Bug: L1 start hash was overwritten so catching up from genesis

go/host/p2p/p2p.go
Response batches message has flag live=true which isn't catastrophic but might make L2 catch up much slower because L2 repo won't realise that p2p response came back.
Correct the `live` flag to `false` in batch data response.
=> p2p batch request data is historic not live

.github/workflows/manual-deploy-dev-obscuroscan.yml, .github/workflows/manual-deploy-obscuroscan.yml
The deployment scripts were referencing the old location.
=> New location of the obscuroscan docker files

go/host/enclave/guardian.go, go/host/enclave/state.go, go/host/host.go
Configured L1 start hash wasn't making it to the enclave guardian so we were still streaming from genesis of L1.
=> Fix wiring of L1 start hash

go/common/enclave.go, go/enclave/components/attestation.go, go/enclave/components/shared_secret_process.go, go/enclave/enclave.go, go/host/rpc/enclaverpc/enclave_client.go
- moves logic with a single responsibility to its own type
- some enclave functions were not respecting the sys error convention
- fixes 2 enclave methods to return SystemError
- move shared secret logic to a component
=> some errors, plus extract shared secret processing

go/host/p2p/p2p.go
We see occasional p2p message serialisation issues on dev-testnet.
To investigate the cause, this pr adds a sanity check to make sure they are not programming errors
=> sanity check p2p message before sending

go/enclave/storage/init/sqlite/001_init.sql, go/enclave/storage/init/sqlite/sqlite.go, go/obsclient/obsclient.go, integration/networktest/env/dev_network.go
1. Tests were failing with 'database is locked' in the errors. We need to limit the connections for persistent sqlite like we do for in-mem.
2. The strict `REFERENCE` check of parent lookup in the db schema is breaking when using l1StartHash and starting mid-chain. Since this doesn't exist on the prod config I thought it was ok to remove for now (it's still checked in the code in `ingestBlock()`).
3. We were just waiting 15secs for network to start instead of waiting for node health checks in network tests.
=> Fixes for tests using persistent sqlite db

go/node/config.go, testnet/launcher/docker.go
[Issue 2058: WithInMemFlag seemingly ignored](https://github.com/obscuronet/obscuro-internal/issues/2058)
Actually turned out that flag is for the host DB to be in-memory. And think we have found a fix for the persisted sqlite db issues on the enclave so will leave that as hardcoded to persisted for now (lots of the settings are hardcoded where they until the tests need flexibility).
Rename the in-mem flag method to make it clear it is for the host DB.
=> Clarify in-mem flag is for host DB

go/host/p2p/p2p.go
Ensure p2p peer list resync after restart because the list is empty at startup and only resynced when secret responses are seen.
Have p2p service resync at startup.
=> Ensure p2p peer list resync after restart

go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql
The database indexes works better if columns are explicitly marked as "not null"
=> add not null constraints

go/host/l1/blockrepository.go
When using Infura RPC endpoint for sepolia data we were getting nil pointers with the new block lookup. This shouldn't happen but if it does we shouldn't nil pointer and should be able to recover.
=> Bug: nil pointer when eth new block not found

go/enclave/storage/storage.go
Visibility on expensive DB calls is important as we debug perf issues but the logging is noisy.
=> Add condition to only log slow storage calls

tools/walletextension/common/constants.go, tools/walletextension/test/utils.go, tools/walletextension/test/wallet_extension_test.go, tools/walletextension/wallet_extension.go
We need this to get userID to frontent as Metamask does not allow us to look for `rpcURL`. 
We decided to use function `getStorageAt` with predefined parameters address=obscuro, position=0 to return us userID from which it was requested.
Obscuro Gateway does not forward the request to `getStorageAt` to Obscuro Node if conditions mentioned above are met and responds with userID that was used in the request. It additionally checks if that userID exists in the databse.
=> user getStorageAt with parameters "obscuro" and "0" to get userID from request URL

go/enclave/storage/storage.go
We've started seeing these errors on latest geth version:
`ERROR[08-25|10:52:20.285] Zero state root hash! `
Use constant empty root hash instead of zero hash to keep geth happy (no behaviour change - see `newTrieReader()` in geth code, it logs error if it's zero but treats it the same as `EmptyRootHash`).
=> fix for zero hash geth errors

contracts/deployment_scripts/testnet/layer2/001_whitelist_tokens.ts, dockerfiles/enclave.debug.Dockerfile, go/common/gethencoding/geth_encoding.go, integration/eth2network/eth2_binaries.go, integration/eth2network/eth2_network.go, integration/simulation/utils.go, testnet/launcher/docker.go
- Bumps geth to 1.12.2 
- Fixes the hardhat deployer static call
- Fixes the way the Health endpoint was called
- Updated the dlv version in the enclave_debug docker image
=> Bump eth2network

go.mod, go.sum, go/common/stopcontrol/stop_control.go, go/common/stopcontrol/stop_control_test.go, go/host/enclave/guardian.go, go/host/host.go
https://github.com/obscuronet/obscuro-internal/issues/2060
The 2 packages had similar purposes.
This avoids confusion. Also cleans up the host handling it's own stop cycle.
- Merged breaker into the stopcontrol package
- Host is not looking out for signals to stop
=> Merge stopcontrol + breaker packages

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/runner-scripts/create-vm.txt
https://github.com/obscuronet/obscuro-internal/issues/1449
Improves the deploy time by having a pre-built image instead of installing everything on the fly.
Should also reduce install-time flakyness, like errors on apt-get update / docker install, that we have seen in the past.
Defaults to using the ObscuroConfUbuntu image
Added a text file on how to create these images for future reference.
=> Uses a prebuilt obscuro node image

tools/walletextension/README.md, tools/walletextension/api/routes.go, tools/walletextension/api/staticOG/javascript.js, tools/walletextension/common/constants.go, tools/walletextension/main/main.go, tools/walletextension/test/utils.go, tools/walletextension/test/wallet_extension_test.go
We want to have versions in the Obscuro Gateway API to allow new versions in the future.
As path for `eth` requests change to `/v1` we can serve frontend on `/` instead of `/og`
/v1/ is used before Obscuro Gateway endpoints (except health, ready and old walletExtension endpoints that will be removed soon)
=> use versioning with Obscuro Gateway API

contracts/config/networks.json, testnet/launcher/l2contractdeployer/docker.go, tools/obscuroscan/main/cli.go
After introduction of versions some calls failed as they did not have the correct URL (with version included)
Added versions to the URLs
=> Add versions to calls to the Obscuro Gateway

go/enclave/storage/enclavedb/events.go
Looks like there's a field change that wasn't updated.
`txHash` no longer exits. Changing it to `tx.hash`
=> Fix txHash field in SQL

go/ethadapter/geth_rpc_client.go, go/ethadapter/interface.go, go/host/l1/blockrepository.go, go/host/l1/publisher.go, integration/ethereummock/node.go
Aggressive reconnects were unnecessary and interfering with slower connections (infura)
=> L1 client - Change client to only reconnect if dead

contracts/deployment_scripts/testnet/layer2/001_whitelist_tokens.ts
Small bug in the sleep in this TS script means that we spin and create lots of promises instead of waiting 1sec between each one.
=> hardhat: ensure token script doesn't spin when waiting

go/common/host/services.go, go/ethadapter/geth_rpc_client.go, go/ethadapter/interface.go, go/host/enclave/guardian.go, go/host/l1/blockrepository.go, integration/ethereummock/node.go
Currently we only send tx receipts to the enclave for L1 transactions addressed `to` an obscuro contract (message bus or management contract).
However we need to capture receipts for any transaction that interacts with those contracts even if the transaction is not addressed `to` the contract directly.
This was breaking local network and testnet networks deployments because the whitelist ERC20 bridge script was failing.
Make an `eth_getLogs` call to fetch all logs in the block and scan through them to see if they come from the obscuro relevant contracts.
Send receipts for those transactions.
=> Filter for tx receipts with any obscuro interactions

.github/workflows/manual-deploy-obscuro-gateway-database.yml, tools/walletextension/storage/database/001_init.sql
https://github.com/obscuronet/obscuro-internal/issues/2158
Adds a deployment for mariadb into a vm.
=> Obscuro Gateway Database Deploy

.github/workflows/manual-deploy-obscuro-gateway-database.yml
Continuation of https://github.com/obscuronet/obscuro-internal/issues/2158
=> Tweak OG database deploy

tools/walletextension/container/walletextension_container.go, tools/walletextension/storage/database/sqlite.go, tools/walletextension/storage/storage.go, tools/walletextension/storage/storage_test.go, tools/walletextension/wallet_extension.go
https://github.com/obscuronet/obscuro-internal/issues/2157
- Storage was a passthrough
- Tests need to work against sqllite and mariadb (in the future)
- Small PR to make the upcoming remote database change easier.
=> Refactor storage to allow for different dbs + tests

.github/workflows/manual-deploy-obscuro-gateway.yml
On hosted gateway port 81 was not open and event subscriptions failed to work because of that.
Open port 81 on the deployed container.
=> Enable websockets on hosted Obscuro Gateway

go/config/host_config.go, go/host/container/cli.go, go/host/host.go, go/host/l1/publisher.go, go/node/config.go, integration/simulation/network/inmemory.go, integration/simulation/network/network_utils.go, integration/simulation/network/obscuro_node_utils.go, integration/simulation/network/socket.go
Timings around retries and timeouts on the host depend on the host block size.
These times are very different between testnets and sims.
The hardcoded times we got by with are causing problems for the sepolia readiness work.
- Add L1 block time field to host config
- Default to 15s
- Overridden by sims and tests
=> Add l1 block time config for host

go/ethadapter/erc20contractlib/erc20_contract_lib.go, go/ethadapter/geth_rpc_client.go, go/ethadapter/interface.go, go/ethadapter/mgmtcontractlib/mgmt_contract_lib.go, go/host/host.go, go/host/l1/publisher.go, integration/eth2network/eth2_network_test.go, integration/ethereummock/erc20_contract_lib.go, integration/ethereummock/mgmt_contract_lib.go, integration/ethereummock/node.go, integration/manualtests/tx_test.go, integration/noderunner/noderunner_test.go, integration/simulation/devnetwork/config.go, integration/simulation/devnetwork/node.go, integration/simulation/network/geth_utils.go, integration/simulation/simulation.go, integration/smartcontract/debug_mgmt_contract_lib.go, integration/smartcontract/debug_wallet.go, integration/smartcontract/smartcontracts_test.go
If a tx is stuck pending on sepolia it brings the whole network to a halt
Keep retrying stuck transactions with the same nonce but updated gas values.
The changes:
- instead of setting nonce when creating L1 tx, it gets set when the tx is 'prepared' at the same time as the from field and gas/gas price fields
- L1 publisher never gives up on a sent tx where it hasn't received a receipt, it will resend with the same nonce
- L1 publisher `publishTransaction` method takes responsibility for reverting the wallet nonce if something goes wrong
=> L1 Publisher: resend stuck tx and manage nonce

.github/workflows/manual-deploy-testnet-l2.yml, testnet/launcher/l1contractdeployer/cmd/cli_flags.go, testnet/launcher/l2contractdeployer/cmd/cli_flags.go
The http_url CLI flag for the deployers said ws_url by accident.
=> Correct ws to http on the deployers flag name

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-upgrade-testnet-l2.yml, go/node/cmd/cli.go, go/node/cmd/cli_flags.go, go/node/cmd/main.go, go/node/config.go, go/node/docker_node.go
We want to configure slower rollup rate for sepolia-testnet
Wire through CLI options for the docker node starter to set batch/rollup intervals.
=> Sepolia prep: add batch + rollup interval CLI options

go/node/cmd/cli.go, go/node/cmd/cli_flags.go, go/node/cmd/main.go, go/node/config.go, go/node/docker_node.go
We need to wire sepolia chain ID from the github action script but it's not a CLI option at that level :(
=> Add flag to configure L1 chainID for docker nodes

go/enclave/enclave.go, go/enclave/evm/evm_facade.go, go/enclave/l2chain/l2_chain.go
=> Removed bad logs.

docs/_data/navigation.yml, docs/_docs/testnet/security.md, docs/_docs/what-is-obscuro/quick-start.md, docs/index.md
Improve docs and add security warning
=> small doc changes

go/enclave/components/rollup_compression.go, go/enclave/limiters/interfaces.go, go/enclave/limiters/rolluplimiter.go, go/enclave/storage/storage.go, integration/simulation/validate_chain.go
- The rollup limiter does not take into account the compression logic
- improve the granularity of the "slow query" logging to help perf debugging
- fix gas validation to exclude empty rollups from the collected fees comparison
=> fix rollup limiter & improve "slow query" logging

go/rpc/encrypted_client.go, tools/walletextension/common/common.go, tools/walletextension/container/walletextension_container.go, tools/walletextension/storage/database/mariadb.go, tools/walletextension/wallet_extension.go
=> Fix OG panic issues

go/host/enclave/guardian.go
At some stage I moved receipt fetch to only fire when we were not busy submitting to the enclave, to avoid unnecessary L1 data requests.
This introduced a bug because if the receipt fetch failed I forgot to release the lock.
The symptom of the bug is the logs spamming: `Unable to submit block, already submitting another block` repeatedly.
=> Submit L1 Block: fix lock bug

go/enclave/components/batch_executor.go, go/enclave/evm/evm_facade.go, integration/networktest/actions/native_fund_actions.go, integration/networktest/env/testnet.go, integration/networktest/log.go, integration/networktest/runner.go, integration/networktest/tests/gas/gas_test.go, integration/networktest/userwallet/userwallet.go, integration/simulation/devnetwork/dev_network.go, integration/simulation/network/geth_utils.go
The base fee needs to not be burned on the Obscuro L2. Furthermore, L2 gas must be refunded for transactions that do not get included in the batch (and are thus not published)
Fixed the issues and added tests capable of tracking known failures.
=> L1 gas refunds for failing transactions. BaseFee not burned anymore.

.github/workflows/manual-deploy-testnet-faucet.yml, README.md, docs/_docs/testnet/deploying-a-smart-contract-programmatically.py, docs/_docs/testnet/faucet.md, integration/faucet/faucet_test.go, integration/networktest/env/network_setup.go, integration/networktest/tests/helpful/availability_test.go, tools/faucet/README.md, tools/faucet/cmd/cli.go, tools/faucet/container/faucet_container.go, tools/faucet/faucet/faucet.go, tools/faucet/faucet/faucet_config.go, tools/faucet/webserver/web_server.go
- Sepolia testing is easier with a faucet.
- We can probably use this faucet for early partners and users too.
- The testnet deploy was showing red for sepolia because of the faucet step
Add config
=> Setup faucet for sepolia env

.github/workflows/manual-deploy-testnet-l2.yml, contracts/deployment_scripts/funding/layer1/002_fund_faucet.ts, testnet/launcher/l2contractdeployer/cmd/cli.go, testnet/launcher/l2contractdeployer/cmd/cli_flags.go, testnet/launcher/l2contractdeployer/config.go, testnet/launcher/l2contractdeployer/docker.go
=> added faucet funding.

integration/obscuroscan/obscuroscan_test.go
=> Enable obscuroscan test

go/common/batches.go, go/enclave/storage/storage.go, go/host/enclave/guardian.go
to avoid errors when storing object in the cache, we need to reduce the shard size.
With the previous setup it was 512K.
- adjust cache cfg
-Also adjust the "create rollup" logic 
=> adjust cache cfg

.github/workflows/manual-recover-network-funds.yml, contracts/deployment_scripts/testnet/recoverfunds/001_recover_funds.ts, testnet/launcher/fundsrecovery/cmd/cli.go, testnet/launcher/fundsrecovery/cmd/cli_flags.go, testnet/launcher/fundsrecovery/cmd/main.go, testnet/launcher/fundsrecovery/config.go, testnet/launcher/fundsrecovery/docker.go
Short term for sepolia we want to be able to recover funds from testnet network bridge.
This script recovers all bridge funds to the deployer acc. It allows us to recover bridged funds on a deprecated network when Obscuro has been redeployed or to add more obscuro play money to the faucet by rebridging.
Note: this functionality will need to go away when we enable bridging off of obscuro back to the L1.
=> Add gh actions script to retrieve funds from the bridge

README.md, docs/_docs/testnet/deploying-a-smart-contract-programmatically.md, docs/_docs/testnet/deploying-a-smart-contract-programmatically.py, docs/_docs/testnet/faucet.md, docs/_docs/wallet-extension/wallet-extension.md, go/common/denomination.go, tools/faucet/README.md
We want docs for users and devs to be clear that users will receive native ETH from the L2 faucet, not OBX.
=> Update some OBX references in docs

integration/networktest/env/network_setup.go, integration/networktest/env/testnet.go
Now that the sepolia faucet is working we can use SepoliaTestnet as an environment on the network tests.
Renamed the RPC URL field as there's no requirement for it to be websocket for testing unless the test is doing some subscription stuff. This means we can configure a public sepolia URL instead of an infura URL requiring API key.
=> Add SepoliaTestnet as an environment for network tests

go/enclave/main/enclave.json
=> bump enclave heap size

go/enclave/components/batch_registry.go, go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go
To improve the performance of "create batch", remove costly select called for each batch.
It also fixes a small flakyness that was causing sim tests to fail due to duplicated genesis
=> remove costly select

go/enclave/components/block_processor.go, go/enclave/nodetype/sequencer.go
there is a slight performance degradation on testnet.
The query for the block head is one potential cause
- cache the l1 head
=> Add block head cache

integration/eth2network/eth2_network.go
https://github.com/obscuronet/obscuro-internal/issues/2281
Reduces the eth2 network logs to error
=> Reduce the verbosity of eth2network

.github/workflows/manual-deploy-testnet-l1.yml, .github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-recover-network-funds.yml, .github/workflows/manual-upgrade-testnet-l2.yml, integration/manualtests/connection_test.go
=> Updates GH Inputs to reflect current networks

.github/workflows/manual-deploy-obscuro-gateway.yml, .github/workflows/manual-deploy-obscuro-scan-2.yml
- Obscuro gateway now uses correct tag
- Obscuro scan v2 now has sepolia option
=> CI fixes for deployment

tools/walletextension/api/staticOG/index.html, tools/walletextension/api/staticOG/javascript.js
https://github.com/obscuronet/obscuro-internal/issues/2288
Do not display buttons and accounts table if Metamask is not installed
=> fix stuck at revoke userID

go/enclave/nodetype/sequencer.go, go/host/enclave/guardian.go, integration/networktest/tests/helpful/availability_test.go
To reduce our datadog log volume these non-critical messages can be downgraded to debug.
=> Downgrade spammy log messages

contracts/package.json
Locking hardhat-deploy version fixes an error we see: https://github.com/obscuronet/obscuro-internal/issues/2294
=> Lock hh-deploy version to fix config compatability bug

tools/walletextension/api/staticOG/javascript.js
Keeping table behind spinner until completely loaded.
=> Keeping table behind spinner until loaded

integration/simulation/simulation.go
remove a simulation flakyness 
increase initialisation time
=> increase init time

go/enclave/components/batch_registry.go, go/host/rpc/clientapi/client_api_eth.go
Some tools are making RPC requests to us with 'pending' blocknumber which was erroring.
These are the eth block number options:
They don't map that well to obscuro batches. For now this treats those requests the same as for latest block because it's better than failing, and I will create an issue for us to revisit this.
We may eventually want to respond with the latest batch that's been rolled up for the 'finalized' flag but maybe that's not intuitive behaviour when rollups may take hours.
Handle the nuanced cases of eth block number all as 'latest' batch for now, in particular `pending` which wasn't supported.
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev-ops-docs/dev-pr- …
=> Respond with latest for pending block number requests

tools/obscuroscan_v2/backend/cmd/cli.go, tools/obscuroscan_v2/frontend/src/lib/config.dev.js, tools/obscuroscan_v2/frontend/src/lib/config.js, tools/obscuroscan_v2/frontend/src/lib/config.prod.js, tools/obscuroscan_v2/frontend/src/lib/poller.js, tools/obscuroscan_v2/frontend/src/stores/priceStore.js
Currently it takes one minute before the eth price is requested so we see a loading circle. The other data also has a slight (1 second) delay before it loads because it waits for its polling interval.
Change the poller semantics to make the request immediately when started and then at the interval thereafter.
=> ObscuroScan: load eth price on init

tools/obscuroscan_v2/frontend/src/components/BatchDataGrid.vue, tools/obscuroscan_v2/frontend/src/components/PublicTxDataGrid.vue, tools/obscuroscan_v2/frontend/src/components/SummaryItem.vue
- Add title to transaction list for clarity
- Show height, not batch seq number in batches table
- Put placeholder for node count to get rid of spinner
=> ObscuroScan: small UI tweaks

tools/walletextension/api/staticOG/index.html, tools/walletextension/api/staticOG/javascript.js, tools/walletextension/api/staticOG/style.css
Some of the UI changes requested by the team.
=> Cais UI updates

tools/walletextension/accountmanager/account_manager.go, tools/walletextension/wallet_extension.go
=> Return error instead of just logging it if client fails

tools/obscuroscan_v2/frontend/src/components/MetaMaskConnectButton.vue, tools/obscuroscan_v2/frontend/src/components/PersonalTxsGrid.vue
Not obvious that wallet is connected on obscuro scan atm.
Before:
After:
=> ObscuroScan: MetaMask button show connected

integration/obscurogateway/obscurogateway_test.go, tools/walletextension/common/common.go, tools/walletextension/common/constants.go, tools/walletextension/subscriptions/deduplication_circular_buffer.go, tools/walletextension/subscriptions/subscriptions.go, tools/walletextension/test/utils.go, tools/walletextension/test/wallet_extension_test.go
For the users to be able to get events from all of their accounts
- Subscribing to events in a for loop for all clients (accounts) current user registered with Obscuro Gateway.
- subscriptionID is generated for subscription call from user and then used in all events that current user received with that subscription (this is required because some tools filter out events that don't match with subscriptionID first sent in websocket)
- Some minor refactoring of the code (`PrepareLogResponse` moved to `subscriptions` package)
TODO (To have completely finished subscriptions working in Obscuro Gateway):
- Deduplication of events
- Unsubscribing (currently we unsubscribe gateway from node when user connection is closed)
Please indicate below by ticking the checkbox that you have read and …
=> Subscribe to events with multiple accounts

go/common/query_types.go, go/host/db/batches.go, go/host/db/blocks.go, tools/obscuroscan_v2/frontend/src/components/BatchDataGrid.vue, tools/obscuroscan_v2/frontend/src/components/RotatingRollupsItem.vue
We want to show oldest batches first in obscuro scan, very rare that someone would want to look at the first batches of the network.
Also added the batch tx hashes so we can use them for tx count and to link to txs potentially.
=> ObscuroScan: serve oldest batches first

go/rpc/client.go, go/rpc/encrypted_client.go, integration/obscurogateway/obscurogateway_test.go, tools/walletextension/accountmanager/account_manager.go, tools/walletextension/subscriptions/subscriptions.go
Since we  (can) have multiple accounts/addresses registered per user and Obscuro Gateway subscribes for all of them. We return  new subscriptionID. And in case users wants to unsubscribe we want to make sure the gateway also unsubscribes from all subscriptions to the node that are/were related to that specific subscriptionID.
=> Gateway unsubscribe for multiple subscribed clients

tools/obscuroscan_v2/frontend/index.html, tools/walletextension/api/staticOG/index.html
https://github.com/obscuronet/obscuro-internal/issues/2387
Integrate Google Analytics for:
- Obscuro Gateway
- Obscuroscan
=> integrate Google Analytics for OG and Obscuroscan

.github/workflows/manual-deploy-obscuro-scan-2.yml
=> Change base url to https

tools/walletextension/userconn/user_conn.go
Gateway crashed because of this. See logs:
https://app.datadoghq.eu/logs?query=service%3Aobscuro_gateway_sepolia_testnet%20container_id%3A6f39991112df50e334e5c2627fa104decaae3e0977db20b27ef10540a5d843f9%20&cols=host%2Cservice&event=AgAAAYv1CizXdvjiHgAAAAAAAAAYAAAAAEFZdjFDamRRQUFDZHVZQnZoUWZ5M1FBSAAAACQAAAAAMDE4YmY1MmYtNGM3NC00MDRiLWFiNGUtOGZhNDcxN2EwNzMw&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&view=spans&viz=stream&from_ts=1700556971076&to_ts=1700643371076&live=true
=> Prevent concurrent writes to a websocket connection

go/common/host/services.go, go/common/query_types.go, go/ethadapter/l1_transaction.go, go/ethadapter/mgmtcontractlib/mgmt_contract_ABI.go, go/ethadapter/mgmtcontractlib/mgmt_contract_lib.go, go/host/enclave/guardian.go, go/host/host.go, go/host/l1/publisher.go, integration/ethereummock/mgmt_contract_lib.go, integration/networktest/actions/l1/important_contracts.go, integration/networktest/env/testnet.go, integration/networktest/interfaces.go, integration/networktest/tests/bridge/important_contracts_test.go, integration/simulation/devnetwork/dev_network.go
For the near term we want to make important network contract addresses to be available. This is especially useful for short-lived testnets etc.
The data is published to the L1 management contract, this PR has node hosts monitor that contract and serve the addresses that are stored in it.
- host to cache L1 important contracts data and serve it with network info on RPC method
- guardian to look out for L1 transactions that change the important contracts, update cache
- add network test that adds an important contract to the L1 and checks that the host starts serving it
Serve the cached addresses with the network info RPC method.
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev …
=> Host: Monitor and serve important contract addresses

.github/workflows/manual-deploy-testnet-l2.yml, contracts/deployment_scripts/bridge/001_deploy_bridge.ts, contracts/deployment_scripts/messenger/layer1/001_deploy_cross_chain_messenger.ts, testnet/launcher/l2contractdeployer/cmd/cli.go, testnet/launcher/l2contractdeployer/cmd/cli_flags.go, testnet/launcher/l2contractdeployer/cmd/main.go, testnet/launcher/l2contractdeployer/config.go, testnet/launcher/l2contractdeployer/docker.go
When L1Bridge and L1CrossChainMessenger contracts are deployed we want to write their addresses to the mgmt contract so they are stored in an accessible source of truth (useful for automated testing with often short-lived testnets)
- pass mgmt contract address to L2 contract deployment
- call mgmt contract 'SetImportantContractAddress' method after the two deployments mentioned above
=> Contract deployment: store important addresses

tools/walletextension/accountmanager/account_manager.go, tools/walletextension/container/walletextension_container.go, tools/walletextension/useraccountmanager/user_account_manager.go, tools/walletextension/useraccountmanager/user_account_manager_test.go, tools/walletextension/wallet_extension.go
This change is needed to fix recently found issue with large number connections to the host.
This is temporary hotfix and the way we do and maintain connection needs to be changed.
Previously we were creating clients for all existing users in the database at startup.
To avoid problems with that we now create all the clients for existing users and only when they are requested with:  `GetUserAccountManager`
=> remove creating all clients at startup

design/ux/Obscuro_Gateway.md, go/common/tracers/tracers.go, go/common/viewingkey/viewing_key.go, go/enclave/enclave.go, go/enclave/events/subscription_manager.go, go/enclave/vkhandler/vk_handler.go, go/enclave/vkhandler/vk_handler_test.go, integration/obscurogateway/obscurogateway_test.go, tools/walletextension/api/routes.go, tools/walletextension/api/staticOG/javascript.js, tools/walletextension/common/common.go, tools/walletextension/common/constants.go, tools/walletextension/config/config.go, tools/walletextension/container/walletextension_container.go, tools/walletextension/lib/client_lib.go, tools/walletextension/main/cli.go, tools/walletextension/storage/database/001_init.sql, tools/walletextension/storage/database/sqlite.go, tools/walletextension/test/apis.go, tools/walletextension/wallet_extension.go
We want to use EIP-712 style signatures to make it more clear what users are signing when prompted to sign viewingkey.
Additionally I changed userID size to 20 bytes.
-  New method to verify EIP-712 messages when authenticating
- Check and accept new signatures in the enclave
- Fix tests to use new version
- Fix Obscuro Gateway frontent (javascript) to use new format
- Updated design file describing the approach used
- Changed size of userID to 20 bytes
=> Use eth sign typed data v4 in gateway

tools/walletextension/api/routes.go, tools/walletextension/container/walletextension_container.go, tools/walletextension/test/wallet_extension_test.go, tools/walletextension/wallet_extension.go
Following test was failing after latest changes: TestCannotInvokeSensitiveMethodsWithoutViewingKey
To get it working as expected we need to add a default user that is used with old endpoints and if userID was not found.
Added default userID to the database at startup
=> add default user for old endpoints

testnet/launcher/l1contractdeployer/docker.go
Testnet deployments are failing because new transactions on the L1 contract deployer (to write important contract addresses to the management contract) have slowed the script down but the timeout wasn't increased.
Bump the allowed time from 1min to 3mins (was taking about 1.5mins on dev-testnet, plus some padding for sepolia being slower).
When things go wrong the container generally fails fast so shouldn't add much time when there are issues.
=> L1 contracts: increase timeout for extra transactions

go/common/viewingkey/viewing_key.go, go/enclave/vkhandler/vk_handler_test.go, integration/obscurogateway/tengateway_test.go, tools/walletextension/lib/client_lib.go
Add another option for for EIP712 signatures. It supports both `Encryption Token` and `EncryptionToken` to enable support for older versions of third party libraries.
=> add another signed message format gateway

go/host/rpc/clientapi/client_api_obscuro.go
Moray suggested we should provide contract addresses in the standard checksum format for callers.
Changed the json serialisation of the network config response to use the checksum formatting geth Address type.
I ran the test to verify this doesn't break the RPC client.
=> Host RPC: use checksum format for contract addresses

go/enclave/rpc_server.go
We don't want to fail for badly formatted requests, we want to log the error and allow chance to recover.
Currently we panic and this recently took down the sepolia testnet. (Investigation of the root cause of that is ongoing).
=> Enclave: no panic for bad rlp format

dockerfiles/enclave.debug.Dockerfile, dockerfiles/host.Dockerfile, tools/hardhatdeployer/Dockerfile, tools/obscuroscan/Dockerfile, tools/walletextension/Dockerfile
there was a change in the latest docker go image
see: https://github.com/mattn/go-sqlite3/issues/1164#issuecomment-1848677118
revert to 3.18 as suggested
=> use the 3.18 go alpine image

dockerfiles/enclave.debug.Dockerfile, dockerfiles/host.Dockerfile, tools/hardhatdeployer/Dockerfile, tools/obscuroscan/Dockerfile, tools/walletextension/Dockerfile
cherry pick from `release/0.20`
https://github.com/ten-protocol/go-ten/pull/1687
=> use the 3.18 go alpine image (#1687)

tools/walletextension/frontend/src/components/layouts/footer.tsx, tools/walletextension/frontend/src/components/modules/home/connected.tsx, tools/walletextension/frontend/src/components/providers/wallet-provider.tsx, tools/walletextension/frontend/src/lib/constants.ts
https://github.com/ten-protocol/ten-internal/issues/2583
- Remove listener for account change
- Move the version to the footer
- Update social links
=> [Gateway] remove listener for account change

tools/walletextension/frontend/src/lib/constants.ts
To avoid warnings from Metamask, caused by having different name for the network
=> Change network name back to Obscuro Testnet, to avoid warnings

tools/obscuroscan_v3/frontend/src/components/modules/dashboard/index.tsx
=> add `$` to ether price

tools/obscuroscan_v3/frontend/pages/personal/index.tsx, tools/obscuroscan_v3/frontend/src/components/modules/common/connect-wallet.tsx, tools/obscuroscan_v3/frontend/src/components/providers/wallet-provider.tsx, tools/obscuroscan_v3/frontend/src/lib/utils.ts
https://github.com/ten-protocol/ten-internal/issues/2594
Error message for non-MM users: `main-12b4344bfd88e8af.js:1 TypeError: Cannot read properties of undefined (reading 'on')`
=> fix: error page for non-MM users

go/enclave/components/batch_executor.go
Avoid spamming empty batches when there is a rejected tx but no successful transactions.
=> Enclave: produce no batch if all tx failed

go/enclave/enclave.go, go/enclave/evm/ethchainadapter/eth_chainadapter.go, go/enclave/nodetype/interfaces.go, go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go, go/enclave/txpool/txpool.go, go/enclave/txpool/txpool_test.go
the geth mempool has a background go-routine, which must be closed.
We weren't closing it, which might explain the flakyness.
- close the goroutine
- use the defaults from the geth mempool
=> close mempool and use the geth defaults for the mempool

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-upgrade-testnet-l2.yml
Testnet deployments and upgrades are currently failing because the enclave docker image is set to TESTMODE=false (the default).
This means it expects to find required flags from enclave.json but they're not there so it panics.
=> Testnet Deployments: set enclave TESTMODE=true

tools/walletextension/frontend/src/api/ethRequests.ts, tools/walletextension/frontend/src/components/layouts/footer.tsx, tools/walletextension/frontend/src/components/modules/home/connected.tsx, tools/walletextension/frontend/src/components/providers/wallet-provider.tsx, tools/walletextension/frontend/src/services/ethService.ts, tools/walletextension/frontend/src/services/useGatewayService.ts
https://github.com/ten-protocol/ten-internal/issues/2598
- enable support for metamask desktop and mobile support
=> [Gateway] enable metamask desktop and mobile support

go/enclave/evm/ethchainadapter/eth_chainadapter.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go, go/enclave/txpool/txpool_mock_test.go, integration/faucet/faucet_test.go, integration/obscurogateway/tengateway_test.go, integration/simulation/simulation.go, tools/walletextension/test/wallet_extension_test.go
The mempool needs a statedb during processing.
In the current implementation we were ignoring the "state root" passed in and always returned the head.
This might have caused some weird edge cases ( and maybe flakyness!)
avoid db query for each tx with new account
get a green build
- return the statedb for the passed in root
- use cached batches
- skip some tests, and increase timeout
=> fix statedb error during mempool

tools/walletextension/frontend/src/components/providers/wallet-provider.tsx
- no MM loading screen
- fetch connected accounts on reload
=> [Gateway] fix: loading screen and connect accounts on reload

.github/workflows/manual-deploy-testnet-l2.yml
On an L2 deploy the deployer logs are the only way to get all of the L1 and L2 contract addresses at the moment. On a new deploy the e2e tests need the new addresses to be able to run all tests. With a retention of 1 day, should a redeploy happen over the holidays the addresses may be lost, or difficult to access. As they are of very small size, increasing the retention to 7 days should not affect our git disk utilisation.
=> Set retention to 7 days for deployer logs

go/enclave/enclave.go, go/enclave/nodetype/sequencer.go
- remove gas check that is done by the mempool as well to return a consistent error message with ethereum tooling
- fix major flakyness
=> remove check performed in the mempool

.github/workflows/manual-deploy-testnet-validator.yml
=> Add validator flow

go/enclave/components/batch_executor.go
to avoid unexpected statedb mutations, revert to snapshot for ignored batches
=> statedb revert to snapshot for ignored batches

.github/workflows/manual-deploy-ten-scan.yml
As per title - required to merge in first so we can test the deployments.
=> Tenscan workflow

go/enclave/components/batch_executor.go
https://github.com/ten-protocol/ten-internal/issues/2654
Testnet fails to start after deploying dev testnet twice.
Seems to be related with the revert state, commenting it out for now.
=> Fix Testnet start

tools/walletextension/container/walletextension_container.go, tools/walletextension/main/main.go
https://github.com/ten-protocol/ten-internal/issues/1994
WalletExtensionContainer.Start()  was blocking before, now I've made it non blocking.
Wait for errors in separate go-routines and don't use `select` directly to block execution.
E2E tests passing: https://github.com/ten-protocol/ten-test/actions/runs/7338012346/job/19979846117
=> make WalletExtensionContainer.Start() non blocking

docs/_docs/testnet/example-dapps.md, docs/_docs/testnet/obscuroscan.md
Previous link was not working.
It was reported by users
https://discord.com/channels/916052669955727371/930433726792470568/1189848417145466921
=> change tenscan link in gateway and docs

integration/networktest/env/network_setup.go
Update networktest environment Testnet -> UAT Testnet config.
Have verified this config with availability_test and smoke_test.
=> [network-tests] Update UAT config

tools/walletextension/useraccountmanager/user_account_manager.go
On December 31th  Ten Gatewat crashed: 
https://app.datadoghq.eu/logs?query=service%3Aobscuro_gateway_sepolia_testnet&cols=host%2Cservice&event=AgAAAYzAOYx5aCAipAAAAAAAAAAYAAAAAEFZekFPWXlYQUFEbFpRQ1pSdFhYZWdBQQAAACQAAAAAMDE4Y2MwOWEtN2VmYy00MWZkLWFiMjgtMjZmNjMxZDIwYWE1&index=%2A&messageDisplay=inline&refresh_mode=paused&stream_sort=time%2Casc&viz=stream&from_ts=1704027600000&to_ts=1704032100000&live=false
Add mutex to avoid concurrent writes to the map
https://github.com/ten-protocol/ten-test/actions/runs/7397025563
=> fix concurrent map writes

integration/faucet/faucet_test.go, testnet/launcher/docker.go, testnet/launcher/faucet/config.go, testnet/launcher/faucet/docker.go, testnet/launcher/gateway/config.go, testnet/launcher/gateway/docker.go, tools/faucet/cmd/cli.go, tools/faucet/faucet/faucet_config.go, tools/faucet/webserver/web_server.go
https://github.com/ten-protocol/ten-internal/issues/2701
- Adds Faucet + Gateway to the launcher
- Removes unused Port flags in the faucet
- Adds health endpoint to the faucet
=> Adds Faucet + gateway to launcher

tools/walletextension/frontend/src/lib/constants.ts
To avoid warning when adding new network & possibly fix errors getting correct balances
Update network name
=> Change network name

go.mod, go.sum, go/ethadapter/geth_rpc_client.go
We are currently quite inefficient with re-requesting blocks when:
- checking for forks on every block
- if the host is busy when a new block comes in, we re-request it when they're ready to process it (exacerbated by multiple enclaves)
This is especially unfortunate for remote L1 data service like infura, there is a cost in latency and it counts against our request quota.
Add a small cache (using simple, popular LRU cache lib) for recent blocks so that the client doesn't go to RPC for the same data unnecessarily.
I did a test with a hit/miss counter to make sure it's getting used, it's at ~50% hit rate during resyncing (less during live streaming).
[PR …
=> Host: Small cache of blocks by hash

go/host/rpc/enclaverpc/enclave_client.go
Fix the reconnecting to live batch streaming from the enclave after a disconnect.
Currently there's a bug where the guardian receives back a nil channel if the reconnect fails, which it blocks on forever so it will never try to reconnect.
=> Fix the enclave stream reconnect

go/ethadapter/geth_rpc_client.go
I put Max instead of Min to cap the gas multiplier after repeated retries. This meant it was always doing max multiplier from the first attempt.
=> Host: Fix bug causing unnecessary multiplier on L1 gas fees

go/common/log/log.go, integration/common/testlog/testlog.go
I'm getting frustrated fairly regularly by shortened hashes, like the tx hash in this log msg:
```
INFO [01-17|11:36:12.973] Host issuing l1 tx                       node_id=0xE09a37ABc1A63441404007019E5BC7517bE2c43f component=host     tx=27cb85..41b663 size=6 retries=0
```
It means you can't do a lookup by hash for whatever the item is. And it's happening automatically because we use a Terminal log formatter even for loggers that write to files.
Changes the formatter to log formatter unless it's streaming to SysOut.
=> Loggers: use log format rather than terminal format for files

integration/obscurogateway/tengateway_test.go, tools/walletextension/accountmanager/account_manager.go, tools/walletextension/common/constants.go, tools/walletextension/container/walletextension_container.go, tools/walletextension/useraccountmanager/user_account_manager.go, tools/walletextension/useraccountmanager/user_account_manager_test.go, tools/walletextension/wallet_extension.go
We want to use http connections from the gateway to the validator. Having web socket connections open for a lot of users can cause gateway to crash. It is also problematic if we want to have it behind load balancer.
Websocket connections are still needed for subscriptions.
https://github.com/ten-protocol/ten-internal/issues/2505
Changed ws connection to http, creating ws connections for subscriptions + added a test for subscription topics
https://github.com/ten-protocol/ten-test/actions/runs/7504133752/job/20430444139
=> Ten gateway use http instead of ws

go.mod, go.sum, go/enclave/vkhandler/vk_handler.go
Ten encrypts responses and requires entropy.
The default secure entropy source is slow.
This PR introduces a secure CSPRNG
=> use fast CSPRNG for encrypting responses

tools/walletextension/frontend/package-lock.json, tools/walletextension/frontend/src/components/health-indicator.tsx
=> Fix health indicator bug

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-deploy-testnet-validator.yml
L2 deployment workflows currently parallelize jobs for load balancer update with osbscuro-node-healthcheck. In cases where requests are processed via the LB prior to the node-persistence init, calls such as `getTransactionCount` throw `nil` exception.
On the deployment side, correct ordering should be be maintained.
ten-protocol/ten-internal/issues/2828
- Job `update-loadbalancer` in workflows given "needs: check-obscuro-is-healthy` to enforce ordering.
=> Reorder Deploy L2 jobs, loadbalancer must follow check-obscuro-is-healthy

go/enclave/storage/init/edgelessdb/edgelessdb.go
To prevent saturation of the underlying db connections and crashes
=> set max conn

go/host/enclave/guardian.go
We sometimes see enclave failures when it receives transactions before it is ready.
Only send transactions to an enclave when it is live (up-to-date).
=> Host: Drop transactions received when enclave not ready

go/host/enclave/guardian.go
Cherry-pick https://github.com/ten-protocol/go-ten/pull/1762 to release branch (host should not send tx to enclave when enclave unavailable).
=> Host: Drop transactions received when enclave not ready (#1762)

go/enclave/components/batch_executor.go, go/enclave/components/interfaces.go
- to help investigate validator failure 
backport state revert fix and add logging
=> backport state revert fix and add logging

go/common/log/log.go, go/common/log/logformat.go, integration/common/testlog/testlog.go, tools/faucet/faucet/faucet.go, tools/walletextension/common/common.go
In recent PR I tried to fix the shortened hashes in our logs, to make them searchable in etherscan etc. But actually what I did had no effect on testnet logs and put our sim logs into a different, machine readable format.
We wanted to use the terminal format everywhere but with full hashes.
- Create a Ten log Format that we have full control over
- duplicate the utility classes to make this match geth Terminal format
In this screenshot the new format is above and the old format below. You can see the `L1 transaction successful` message now has searchable hashes:
=> Logging: use terminal format with full hashes

go/enclave/enclave.go
Our gas estimation method is lifted (copy-paste) from geth code. They added an optimisation to their binary search that means in average case it goes way quicker (e.g. 4 iterations instead of 37 in my testing).
https://github.com/ethereum/go-ethereum/blob/16ce7bf50fa71c907d1dc6504ed32a9161e71351/eth/gasestimator/gasestimator.go#L162 <-- is the code on their codebase.
=> Add estimate optmisation that geth added

go/enclave/components/batch_executor.go, go/enclave/evm/evm_facade.go
The mix digest ends up being different between the sequencer and the validator as the sequencer treats the context differently due to the excluded transactions that have mutated it. This brings them back to acting identically.
=> [Batch Execution] Fix for desync issue.

.github/workflows/manual-upgrade-testnet-l2.yml
Flag is set on deployment to true but needs to be set on upgrade as well.
=> Deploy scripts: enable debug api on upgrades

tools/walletextension/accountmanager/account_manager.go
Improve the Ten Gateway logic of determining the sender of a request
- add more call specific logic
- only handle "not authorised" logic for platform calls
=> improve multi-acct logic

.github/workflows/build-pr.yml, integration/eth2network/eth2_network.go, integration/simulation/network/geth_utils.go, integration/simulation/network/socket.go
to make our tests more stable
- use microseconds instead of millis to reduce the chance of a folder collision
- "Release" the os.Process for the ethereum node
=> more flakyness fixes

integration/constants.go
ports were colliding because the offsets were higher than the main increment
=> adjust port offset

tools/walletextension/cache/RistrettoCache.go, tools/walletextension/cache/cache.go, tools/walletextension/cache/cache_test.go, tools/walletextension/wallet_extension.go
We want to cache some results on the Ten Gateway and not forward all the requests to the Ten Node
- New cache added (`ristretto.Cache`  is used)
- Simple interface that allows us to simply change the cache library / use different type of caching in the future
- Per method TTL and logic to determine if methods are cacheable and for how long
- Tests
=> Ten Gateway Caching

design/gateway/gateway_caching.md
To discuss if and how to best implement caching on Ten Gateway.
https://github.com/ten-protocol/ten-internal/issues/2851
=> Gateway caching proposal

go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go, go/enclave/txpool/txpool.go, integration/common/utils.go, integration/constants.go, integration/simulation/simulation.go
return more errors when submitting tx on a vaidator node
invoke a different geth function
=> change mempool validation function

go/common/gethencoding/geth_encoding.go, go/enclave/storage/storage.go
This is a naive fix for the OOM.
In a future version we have to make  more rigorous calculations.
- decrease the number of elements to be cached
=> tweak cache params

go/enclave/txpool/txpool.go
Add mutex around statedb operations
=> concurrency fix

tools/walletextension/cache/cache.go, tools/walletextension/cache/cache_test.go, tools/walletextension/wallet_extension.go
Some e2e tests were failing because of caching. 
- Exclude caching of:  "eth_getTransactionCount" and  "eth_getBalance".
- Fix to return the correct request ID
=> cache fixes for e2e tests

tools/walletextension/wallet_extension.go
Disable cache temporarily on v0.22 branch not to block the release and to get a fix for authentication in
Commented out storing requests to cache and returning responses from cache.
=> disable cache temporarily

integration/networktest/actions/context.go, integration/networktest/actions/native_fund_actions.go, integration/networktest/actions/node_actions.go, integration/networktest/actions/setup_actions.go, integration/networktest/env/dev_network.go, integration/networktest/env/network_setup.go, integration/networktest/env/testnet.go, integration/networktest/interfaces.go, integration/networktest/tests/gateway/gateway_test.go, integration/networktest/tests/helpful/availability_test.go, integration/networktest/tests/nodescenario/restart_network_test.go, integration/networktest/tests/nodescenario/restart_validator_enclave_test.go, integration/networktest/tests/nodescenario/restart_validator_test.go, integration/networktest/userwallet/authclient.go, integration/networktest/userwallet/gateway.go, integration/networktest/userwallet/user.go, integration/simulation/devnetwork/config.go, integration/simulation/devnetwork/dev_network.go, integration/simulation/devnetwork/node.go, tools/walletextension/api/utils.go
The network tests are useful for end-to-end testing from the IDE against a local network or against the testnet environments.
But they could only test the direct to node 'AuthClient' connections and so they couldn't be used to debug or test GW issues.
- Add `WithGateway()` option to the LocalDevNetwork so it starts a (debuggable) gateway process alongside the network nodes.
- Add `UseGateway` boolean option to the `CreateTestUser` action to allow users to be created that would register and communicate with the gateway instead of directly. (Create User abstraction so both types of user can be used in all tests).
- Fix issue in the gateway where it was expecting params key to always be set even for methods like eth_gasPrice that have no params. This is an issue because the geth client does …
=> NetworkTests: add options for test users to use gateway

tools/walletextension/useraccountmanager/user_account_manager.go
We experienced crashes on testnet and this is the most likely cause of them.
We were using only read mutex, but we also need write mutex to avoid concurrent write
Change read mutex to read+write mutex
=> fix mutex error

tools/walletextension/wallet_extension.go
The gateway was crashing because of modifying of requestID values after returning from cache
creating shallow copy of return value before modifying and returning it
=> create a shallow copy of a map before modifying it

tools/walletextension/cache/cache.go, tools/walletextension/cache/cache_test.go, tools/walletextension/wallet_extension.go
We need to cache authenticated requests per user to prevent from unauthenticated access of cached responses
=> fix cache for authenticated method calls

integration/networktest/actions/setup_actions.go, integration/networktest/env/network_setup.go, integration/networktest/env/testnet.go, integration/networktest/tests/helpful/accs_and_contracts_test.go, integration/networktest/tests/helpful/spin_up_local_network_test.go, integration/networktest/userwallet/authclient.go, integration/simulation/devnetwork/dev_network.go
We want to be able to quickly debug at every layer with a local network.
- add gateway to long running local network
- add function to fund accs with faucet on any network (useful for local network)
- fix some stuff
=> Network test: local network QoL

tools/tenscan/frontend/styles/globals.css, tools/walletextension/frontend/src/styles/globals.css
https://github.com/ten-protocol/ten-internal/issues/3015
The primary and secondary fonts have been switched to ff the brand guidelines
=> switch primary & secondary font-family in TS & TG

changelog.md
=> Change log

.github/workflows/manual-deploy-obscuro-gateway.yml
We have intermittent issues with the Gateway not being accessible on redeploy from what is believed to be DNS delay from the dynamic IP. Static IPs on the VM will solve this.
Note: originally I had planned to introduce a LoadBalancer, but decided against as the backend pools will balance as well and  the static IPs will be more cost effective. (however this will be deprecated when migration to terraform is in place as the below workflow doesn't accommodate multiple instances / horizontal scaled gateways.
- check/create a static ip for use
- assigns the vm the existing ip
**N/A for workflow**
=> Adjusts gateway VM deployment to use static ip address.

tools/walletextension/cache/cache.go, tools/walletextension/cache/cache_test.go
We cache also the results where data was not found, that caused problems with come libraries.
Commented out 
=> Disabled caching.

go/enclave/enclave.go, go/enclave/rpc/EstimateGas.go, go/enclave/rpc/rpc_encryption_manager.go
to improve performance of the "Estimate Gas call" use the cached version of some methods
=> performance fix

integration/networktest/env/network_setup.go, integration/networktest/env/testnet.go, integration/networktest/runner.go, integration/networktest/tests/gateway/gateway_test.go, integration/networktest/tests/helpful/spin_up_local_network_test.go
It's useful to be able to test against a local gateway running against a remote testnet, lets you debug the interactions and run with code changes.
Add `WithLocalTenGateway()` option to the Sepolia/UAT/DevTestnet environments in network tests.
=> Networktests: run local gateway against testnets

integration/obscurogateway/tengateway_test.go, tools/walletextension/api/routes.go, tools/walletextension/config/config.go, tools/walletextension/main/cli.go, tools/walletextension/storage/database/mariadb/002_store_incoming_txs.sql, tools/walletextension/storage/database/mariadb/mariadb.go, tools/walletextension/storage/database/sqlite/sqlite.go, tools/walletextension/storage/storage.go, tools/walletextension/storage/storage_test.go, tools/walletextension/wallet_extension.go
For debugging purposes we would like to store unencrypted transactions in the gateway to be able to reproduce some errors if they occur.
Additional database table, storing transactions
https://github.com/ten-protocol/ten-test/actions/runs/8143119529
=> store incoming transactions in a database

go/config/enclave_cli_flags.go, go/node/docker_node.go, integration/common/constants.go, integration/simulation/devnetwork/node.go, integration/simulation/network/network_utils.go
=> Updated batch size limit.

integration/constants.go, integration/networktest/README.md, integration/networktest/tests/ci/simulation_test.go, integration/simulation/devnetwork/config.go
Network tests might run things slightly differently to existing sims so get extra coverage with another sim. Longer term if it works out easy to work and we extend it sufficiently then it might replace the existing sim.
Add a basic network test which will not be skipped on CI. It spins up network, runs light load of transactions and verifies the state.
=> Network tests: basic sim to run in CI builds

tools/walletextension/frontend/src/components/head-seo.tsx
https://github.com/ten-protocol/ten-internal/issues/3139
To prove we own the site
added a meta tag with the Beagle security signature
=> Add Beagle Security meta tag

go/node/docker_node.go, testnet/docker-compose.debug.yml, testnet/docker-compose.non-sgx.yml, testnet/docker-compose.yml
Missed some flag usages when I changed the flag name on this recent PR https://github.com/ten-protocol/go-ten/pull/1852
`enclaveRPCAddress` -> `enclaveRPCAddresses` in host flags.
=> Host config: renamed flag fix

.github/workflows/runner-scripts/create-vm.txt, go/common/docker/docker.go
Containers (nodes) were crashing due to overflow of container logs (default is persisting internally to json-file) which had no rotation scheme.
This is a patch PR for inclusion to a v0.23.3 compared to https://github.com/ten-protocol/go-ten/pull/1850 which is against main.
Added some log options to the standard rolling behavior of 10m per log file -> creation of new file when exceeding -> maximum historic files of 3 -> delete oldest on next rotation.
This is a passive approach and won't affect relaying to datadog etc as it maintains the same default format on the log-type.
[PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops …
=> v0.23 release patch for rotating/trimming docker logs (#3116)

go/rpc/encrypted_client.go, tools/walletextension/rpcapi/filter_api.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/wallet_extension.go
Improve resource consumption
use the existing pool for UnauthRPC
=> Use conn pool for plaintext rpc

go/obsclient/authclient.go, go/obsclient/test_util.go, go/rpc/client.go, go/rpc/encrypted_client.go, go/rpc/network_client.go, integration/simulation/p2p/in_mem_obscuro_client.go, lib/gethfork/rpc/client.go, tools/walletextension/rpcapi/filter_api.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/wallet_extension.go
The internal RPC interface did not match the geth interface so we had to create a confusing adapter object
align interfaces and remove adapter
=> Align RPC interfaces

go/common/viewingkey/viewing_key.go, go/enclave/vkhandler/vk_handler.go
avoid crashing enclave when the vk is invalid
validate the vk before processing
=> add vk check

go/host/enclave/guardian.go, go/host/enclave/state.go, go/host/l2/batchrepository.go
The L2 batch repo only notifies subscribers of new batches from p2p source. This was convenient but confusing.
It is more re-usable if it notifies on every batch that is new to the host, so it will work for sequencers.
=> Host: notify batch subscribers of new batches from any src

.github/workflows/runner-scripts/create-vm.txt, go/common/docker/docker.go
Containers (nodes) were crashing due to overflow of container logs (default is persisting internally to `json-file`) which had no rotation scheme.
Added some log options to the standard rolling behavior of 10m per log file -> creation of new file when exceeding -> maximum historic files of 3 -> delete oldest on next rotation.
=> 3116 - Adds a log configuration to docker containers to roll

tools/walletextension/frontend/src/components/head-seo.tsx
https://github.com/ten-protocol/ten-internal/issues/3140
Add security headers as proposed by Beagle Security mitigation techniques
- set `X-Frame-Options` to `deny` to prevent the page from being loaded in an iFrame
-  set `X-Content-Type-Options` to `nosniff` to indicate the browser shouldn't interpret the response as something other than the specified content type
=> Add security headers

go/common/host/services.go, go/host/enclave/guardian.go, go/host/l2/batchrepository.go
Currently when you subscribe for L2 batches you don't get an unsubscribe callback. This means the L2 repo's Subscribe method can't be used for temporary subscriptions like newHeads requests.
=> Host: Fix L2 repo to use the subscriptions utility

tools/walletextension/httpapi/utils.go
This is a temporary fix that enables local testnet again.
In a separate PR I will provide full solution with consistent usage of `0x` prefix and fixed gateway issues.
Local testnet was successfully started with this branch: https://github.com/ten-protocol/ten-test/actions/runs/8543430314/job/23407243846
accept both tokens with `0x` prefix and without it.
=> Fix parsing both tokens with 0x prefix and without it

go/common/subscription/new_heads_manager.go, tools/walletextension/cache/RistrettoCache.go, tools/walletextension/cache/cache.go, tools/walletextension/rpcapi/blockchain_api.go, tools/walletextension/rpcapi/ethereum_api.go, tools/walletextension/rpcapi/filter_api.go, tools/walletextension/rpcapi/gw_user.go, tools/walletextension/rpcapi/transaction_api.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/wallet_extension.go
Many values stored in the Ten Gateway's caching layer expire as soon as a new batch is created.
This PR adds this feature.
- change the CacheConfig to return some cache strategy types instead of durations
- implement a cache eviction check 
=> improve cache

tools/walletextension/cache/cache.go, tools/walletextension/rpcapi/blockchain_api.go, tools/walletextension/rpcapi/ethereum_api.go, tools/walletextension/rpcapi/transaction_api.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/wallet_extension.go
clean up and fixes
- fix cache eviction for Long caching
- add cache to transaction methods
- add  head subscr retry when starting gateway server
=> Misc fixes after refactoring the gateway RPC 

tools/walletextension/storage/database/001_init.sql
We need alter permission for migrations on the obscurouser
=> add alter permission to obscurouser

tools/walletextension/httpapi/routes.go
https://github.com/ten-protocol/ten-internal/issues/3232 
EIP712 message format was not user friendly to use and users needed to perform manipulations on it to make it work.
This needs to be done in the gateway so that users can use it out of the box.
=> fix the EIP712 getmessage response

.github/workflows/manual-deploy-testnet-l2.yml
https://github.com/ten-protocol/ten-internal/issues/3244
* New GH action step to find any databases with host_ prefix and delete them 
=> Cleanup Host Databases

.github/workflows/manual-deploy-testnet-l2.yml, go/host/storage/init/postgres/postgres.go, integration/simulation/p2p/in_mem_obscuro_client.go, integration/simulation/validate_chain.go
The dev host node errored late last night:
```
CRIT [04-11|21:36:08.096] failed to add batch to L2 repo           node_id=0xd6bCf7694fc4Ed7c7C61B3fC5757919E237D0bf5 component=host enclave_id=0x281330F7a477e1e525687b092089480cC1041BF7 batch=0x8ee70adf010b2dee3cee5378d96464a964f6fea10fac715d248d3f4eaf498651 err="could not add batch: failed to begin host db transaction. Cause: pq: remaining connection slots are reserved for roles with privileges of the \"pg_use_reserved_connections\" role"
```
* Set max connections to 100 same as edgelessDB
* (unrelated) Add check to in-mem test for batchByTx to catch any flakeyness 
[PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops-docs/dev-pr …
=> Set max Postgres DB Connections

go/host/storage/hostdb/hostdb.go, go/host/storage/storage.go
https://github.com/ten-protocol/ten-internal/issues/3246
The connections to postgres keep running out and theres a lot of failed rollup insertions that result in idle connections.
```
| idle in transaction (aborted) | -8488598446982951149 | INSERT INTO rollup_host (hash, start_seq, end_seq, time_stamp, ext_rollup, compression_block) values ($1, $2, $3, $4, $5, $6) | client backend |
```
If this doesn't fix it we can try connection pooling via Azure but theres a cost associated. 
* Add rollback to storage interface
=> Fix failed rollup insertion on Host

go/node/cmd/main.go
Missed one of the many hops where the flag has to be wired through.
Have checked that this fixed the deploy (https://github.com/ten-protocol/go-ten/actions/runs/8881374641).
=> Node config: wire through seq addr flag

go/host/p2p/p2p.go
Msg validation was logging spurious errors for new msg type (validator requests to register with the sequencer for broadcasts).
=> P2P: fix msg validation for new msg type

go/common/subscription/utils.go, go/host/rpc/clientapi/client_api_filter.go, go/node/docker_node.go, tools/walletextension/rpcapi/filter_api.go
The `NewHeads` subscription is not working properly.
It appears as though the first "unsubscribe" was killing all connections.
- no longer kill all connections on the first unsubscribe
=> fix newHeads unsubscribe

go/host/storage/hostdb/batch.go, integration/tenscan/tenscan_test.go
https://github.com/ten-protocol/ten-internal/issues/3314
* Trunc the hash and query by the shortened version
=> Batch transactions query accepts full or short hash

go/common/host/services.go, go/host/enclave/guardian.go, go/host/host.go, go/host/l2/batchrepository.go
We have bugs that are likely caused by the host newHeads subscriptions getting notified of new batches before the enclave has processed them.
Separate out the L2 repo's subscribers between those that want to know about a new head added to the DB and a new head batch that has been validated by that node's own enclave. Use the latter for the new heads RPC subscriptions.
=> Host: notify separately for new heads and new validated heads

go/enclave/storage/db_init.go, go/enclave/storage/init/edgelessdb/edb_attestation.go, go/enclave/storage/init/edgelessdb/edgelessdb.go, go/node/docker_node.go, integration/simulation/simulation.go, testnet/launcher/docker.go
Sqlite doesn't work properly under load. The e2e tests running against a "local testnet" deployment fail with "database locked"
replace sqlite with edgeless for the "local testnet"
=> Wire edgeless in simulation mode for local testnet

integration/networktest/actions/setup_actions.go, integration/networktest/actions/subscription_actions.go, integration/networktest/env/network_setup.go, integration/networktest/env/testnet.go, integration/networktest/interfaces.go, integration/networktest/tests/helpful/smoke_test.go, integration/networktest/tests/subscription/subscriptions_test.go, integration/networktest/userwallet/gateway.go, integration/simulation/devnetwork/dev_network.go
Wanted to be able to monitor new heads subscriptions from network tests.
Added an action and a basic test for starting a network heads subscription against the gateway. Had to add support for gateway WS client to the network tests to allow this.
=> Network tests: new heads subscriptions

.github/workflows/manual-deploy-ten-gateway-frontend.yml, tools/walletextension/frontend/Dockerfile, tools/walletextension/frontend/next.config.js
Deploying Ten Gateway frontend separately will simplify Ten gateway and it won't need to serve frontend/static files anymore. Additionally it will give us an option to remove nginx and make it run as a SGX application.
- Dockerfile
- Github actions file
- minor other changes
=> Create separate deployment for Ten Gateway Frontend

go/enclave/storage/enclavedb/block.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql, go/enclave/storage/storage.go
There is a performance degradation when inserting l1 blocks. 
Most likely because the canonical update query does not properly use the indexes.
Optimize the block insertion.
=> tweak performance

tools/tenscan/backend/webserver/webserver_routes_items.go
Realised during testing it was missing
* Add new `/items/transactions/count` path to get the tx count needed on tenscan 
* Group the endpoints so its easier to read 
* Add function names to errors for easier debugging
=> Expose TX count API 

go/common/subscription/utils.go, go/enclave/enclave.go, go/enclave/l2chain/l2_chain.go, go/host/events/logs.go, go/host/rpc/clientapi/client_api_filter.go
the log subscription unsubscribe process is not working properly
- change the order of actions
- reduce lock contention
- make some logs less noisy
=> improve log subscription unsubscribe

tools/walletextension/rpcapi/filter_api.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/wallet_extension.go
We seem to have a resource leak on the TG RPC conn pool
- return connection in some error cases
- add context to the borrowing method
- improve logging
=> improve rpc conn pool

go/host/enclave/service.go
Some poorly thoughtout placeholder code was returning a nil enclave guardian when the guardian wasn't healthy. Needs revisiting in the HA failover work.
=> Host: fix nil pointer when enclave not healthy

go/enclave/rpc/GetCustomQuery.go, go/enclave/storage/enclavedb/batch.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go
- "The personal transactions" displayed on tenscan are very slow because there is no index on the `tx. sender`
- the host db took over some responsibilities that were in the enclave before
- add index
- remove dead code
- clarify some method naming
=> add index on tx.sender, and clean up

go/host/enclave/guardian.go, go/host/l1/publisher.go, integration/simulation/devnetwork/node.go, integration/simulation/network/network_utils.go
* Fix for interval.
* Removed defaulting from guardian as there should already be a default value.
* Made the fromSeqNo to be local.
* Modify how the local cached seq no is set.
* Add missing cfg option.
* Another missing default value.
---------
=> Fix for interval. (#1926)

integration/simulation/p2p/in_mem_obscuro_client.go, integration/simulation/transaction_injector.go
=> Fix log spam.

go/enclave/components/batch_executor.go, go/enclave/crosschain/common.go, go/enclave/genesis/testnet_genesis.go, go/enclave/nodetype/common.go, go/enclave/nodetype/sequencer.go, integration/networktest/tests/gateway/gateway_test.go, integration/networktest/userwallet/gateway.go, tools/walletextension/rpcapi/net_api.go, tools/walletextension/walletextension_container.go
net_version requests weren't supported by gateway and some tools rely on it.
=> Gateway: add net_version support and test

go/enclave/components/batch_executor.go, go/enclave/crosschain/common.go, go/enclave/genesis/testnet_genesis.go, go/enclave/nodetype/common.go, go/enclave/nodetype/sequencer.go, integration/networktest/tests/gateway/gateway_test.go, integration/networktest/userwallet/gateway.go, tools/walletextension/rpcapi/net_api.go, tools/walletextension/walletextension_container.go
We need this fix in sepolia: https://github.com/ten-protocol/go-ten/pull/1934
=> Gateway: add net_version support and test (#1934)

go/common/gethutil/gethutil.go, go/enclave/components/batch_executor.go, go/enclave/components/batch_registry.go, go/enclave/components/block_processor.go, go/enclave/components/interfaces.go, go/enclave/components/rollup_compression.go, go/enclave/crosschain/common.go, go/enclave/enclave.go, go/enclave/genesis/testnet_genesis.go, go/enclave/nodetype/common.go, go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go, go/enclave/storage/enclavedb/batch.go, go/enclave/storage/enclavedb/block.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go, go/host/enclave/guardian.go, go/host/storage/hostdb/batch.go, go/host/storage/storage.go, integration/ethereummock/db.go, integration/simulation/simulation.go, integration/simulation/simulation_in_mem_test.go, integration/simulation/validate_chain.go
Our simulation tests are flaky.
- the main change is a fix to a fork creation bug which causes batches not to be marked as canonical properly
- another fix is around a very subtle corner case where 2 consecutive forks cancel each other
- there are 2 more unrelated fixes
=> fix flakyness errors

go/common/gethencoding/geth_encoding.go, go/enclave/components/batch_executor.go, go/enclave/crosschain/common.go, go/enclave/genesis/testnet_genesis.go, go/enclave/nodetype/common.go, go/enclave/nodetype/sequencer.go, go/enclave/rpc/SubmitTx.go, go/enclave/storage/enclavedb/events.go
We are converting some inputs without checking.
add conversion checks 
=> check conversions

integration/networktest/tests/gateway/gateway_test.go, tools/walletextension/rpcapi/web3_api.go, tools/walletextension/walletextension_container.go
Some tools expect a response from web3_clientVersion. Hardcode one in the gateway for now.
=> Gateway: hardcode response to clientVersion request

go/enclave/storage/storage.go
as the number of batches grows, the health check becomes very slow
replaced the HC query 
=> replace health-check db query

go/ethadapter/geth_rpc_client.go, go/ethadapter/interface.go, go/host/l1/publisher.go, integration/ethereummock/node.go
While retrying a stuck transaction we were incrementing the nonce. These pending transactions eventually all went through together costing the sequencer a fortune in unnecessary gas. Also, I think they were blocking each other which is why the stuck transactions carried on so long.
The nonce is acquired only once when the sending lock is acquired so price updates overwrite the transaction in the mempool.
=> Host: avoid spamming stuck L1 transactions

go/enclave/evm/evm_facade.go, go/enclave/txpool/txpool.go
The mempool integration needs a bit more work. 
The main issue that prevents that work is how we execute transactions to build a batch.
We need to rework them such that we execute them one by one.
Until then, it's useful to make the logs a little less verbose.
- close the mempool properly
- filter out transactions with invalid base fee
- change logging level of tx execution failure
=> small mempool fixes

go/enclave/rpc_server.go, go/host/rpc/enclaverpc/enclave_client.go
To avoid errors like: `grpc: received message larger than max`
Increase some grpc default settings
=> increase max message size grpc config

integration/networktest/env/network_setup.go
Running test against testnets but with local gateway was failing because it started async and wasn't up in time for the test interactions.
=> Network tests: start gateway synchronously to fix race

integration/networktest/tests/helpful/accs_and_contracts_test.go, integration/networktest/tests/helpful/smoke_test.go
Utility test in the network tests that lets you transfer L1 funds from one acc to another (providing PK string, dest address, amount).
Useful for moving/recovering funds on sepolia.
=> Network tests: util func for L1 transfers

.github/workflows/manual-deploy-dexynth-gateway.yml
Due to high amount of traffic we want to give Dexynth separate gateway which points to S2
=> deploy separate Ten gateway for Dexynth

go/host/enclave/state.go
If enclave had issues with db it sometimes failed to report an L1 head, then the guardian in the host started replaying blocks from L2 genesis.
=> Host: ignore empty L1 head status from enclave

.github/workflows/manual-deploy-dexynth-gateway.yml, .github/workflows/manual-deploy-obscuro-gateway-database.yml, .github/workflows/manual-deploy-obscuro-gateway.yml, .github/workflows/manual-deploy-testnet-l1.yml, .github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-deploy-testnet-validator.yml
Containers for gateway are instantiated manually via docker run which isn't applying the `max-file` and `max-log` logging options to the containers.
Added the logging options to the execution statements in the workflows.
=> Adds log constraints to docker containers not instantiated by the go client

contracts/deployment_scripts/testnet/layer2/001_whitelist_tokens.ts
Previous merge broke the testnet startup due to a mismatch in the actual event and the one put in the interface to process it in the javascript deployment scripts.
=> Properly create the event interface for deployment script in order to fix testnet startup.

.github/workflows/manual-publish-edb-connect.yml
Want to test the EDB Connect changes end to end but can't without the GH action workflow file existing on main.
This will not be actively used until https://github.com/ten-protocol/go-ten/pull/1963 is tested and merged.
=> EDB Connect: placeholder commit for new GH action workflow

contracts/src/bridge/frontend/Dockerfile
update the Dockerfile paths for bridge deployment
=> Initiate bridge deployment

go/enclave/rpc/EstimateGas.go, go/host/enclave/guardian.go
=> Overshoot balance fix on estimate gas.

go/common/docker/docker.go
Add resilience to jammed services. First mitigation is to restart.
Changed the Host Config of the Go docker client to add restart policy
=> Set Restart policy on docker containers

go/common/log_events.go, go/enclave/storage/enclavedb/events.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/storage.go, go/host/l1/statemachine.go, tools/walletextension/rpcapi/filter_api.go, tools/walletextension/rpcapi/utils.go
- the event log query is inefficient because of the "order by" ( the database uses a temporary file).
- when no batch range is passed in, the getLogs query does not use the index, and performs a full table scan 
- the "getLogs" function does not concatenate the results of all the registered accounts for a user at the gateway level
- remove the db order by, and sort in the code
- add more indexes 
- fix the "getLogs" function in the gateway to perform concatenation and deduplication
=> db tweaks + getLogs Fix

go/enclave/crosschain/common.go, go/enclave/crosschain/message_bus_manager.go
There is an issue with representing cross chain messages's hashes currently. When encoded to the batch tree, they end up listed as hash of empty value. This PR addresses this;
=> Fix for empty messages.

go/enclave/events/subscription_manager.go, go/enclave/nodetype/common.go, go/enclave/rpc/GetTransactionReceipt.go, go/enclave/storage/enclavedb/events.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go
The logic for filtering event logs was different between polling and subscriptions.
This change uses the same approach
=> Refactor event log filtering for subscriptions

go/common/enclave.go, go/common/gethencoding/geth_encoding.go, go/common/types.go, go/enclave/enclave.go, go/enclave/rpc/GetCustomQuery.go, go/enclave/rpc/GetPersonalTransactions.go, go/enclave/rpc_server.go, go/host/rpc/clientapi/client_api_eth.go, go/host/rpc/clientapi/client_api_scan.go, go/host/rpc/enclaverpc/enclave_client.go, go/obsclient/authclient.go, go/responses/types.go, go/rpc/client.go, go/rpc/encrypted_client.go, tools/walletextension/rpcapi/blockchain_api.go
Custom query is a tunnel through the ETH RPC API, it shouldn't be mentioned on the node. TEN RPC can support GetPersonalTransactions explicitly.
=> TEN RPC: replace custom query with personal transactions

go/enclave/storage/cache_service.go
The testnet enclaves crash with OOM periodically.
Tweak the cache config. Reduce the `NumCounters` and the total allocated size
=> tweak cache config

lib/gethfork/node/rpc_server.go
Metamask RPC requests from Firefox were failing with CORS errors so TEN Gateway was unusable with FF.
Permit all CORS origins (there is a todo above the line already to review this at some point for safety, for now this unblocks testnet users).
=> Gateway: allow CORS all origins to fix firefox error

tools/tenscan/frontend/api/transactions.ts, tools/tenscan/frontend/pages/tx/[hash].tsx, tools/tenscan/frontend/pages/tx/personal/[hash].tsx, tools/tenscan/frontend/src/components/modules/common/data-table/data-table-pagination.tsx, tools/tenscan/frontend/src/components/modules/common/empty-state.tsx, tools/tenscan/frontend/src/components/modules/dashboard/analytics-card.tsx, tools/tenscan/frontend/src/components/modules/dashboard/index.tsx, tools/tenscan/frontend/src/components/modules/personal/columns.tsx, tools/tenscan/frontend/src/components/modules/personal/personal-txn-details.tsx, tools/tenscan/frontend/src/components/ui/key-value.tsx, tools/tenscan/frontend/src/lib/constants.ts, tools/tenscan/frontend/src/lib/utils.ts, tools/tenscan/frontend/src/routes/index.ts, tools/tenscan/frontend/src/services/useTransactionsService.ts, tools/tenscan/frontend/src/types/interfaces/TransactionInterfaces.ts, tools/tenscan/frontend/src/types/interfaces/index.ts
https://github.com/ten-protocol/ten-internal/issues/3611
https://github.com/ten-protocol/ten-internal/issues/3171
https://github.com/ten-protocol/ten-internal/issues/3615
- add personal transaction details page
- disable next button if page size is more than rows
- handle loading states on the dashboard
=> [Tenscan] personal transaction/contract deployment details page

go/host/rpc/clientapi/client_api_eth.go, integration/obscurogateway/tengateway_test.go
MaxPriorityFeePerGas RPC was missing on the node
This adds a very dummy implementation
=> implement mock MaxPriorityFeePerGas

contracts/package.json
One of the dependencies has a soft lock on a dependency version, which was going too high up and being incompatible with the rest of our stuff.
=> Fix for hardhat deployer dependency being incorrect.

tools/walletextension/rpcapi/blockchain_api.go
Ethers6 tries to read the `transactions` field of the returned "block" and fails 
- add the dummy field
=> add dummy fields to keep ethers6 happy

go/common/types.go, go/enclave/nodetype/interfaces.go, go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go, go/host/enclave/guardian.go
We have a memory leak which kills our node every few days on sepolia.
Upon investigation, it turns out there is a memory leak inside RLP decoding when submitting a sepolia block. More specifically when decoding the L1 transactions.
We only need very few L1 transactions inside the enclave, and we are sending all of them. 
Filter out transactions that are irrelevant before submitting an L1 block to the enclave.
=> filter out irrelevant l1 txs, before sending into the enclave

go/common/docker/docker.go, go/node/docker_node.go, testnet/launcher/eth2network/docker.go, testnet/launcher/faucet/docker.go, testnet/launcher/fundsrecovery/docker.go, testnet/launcher/gateway/docker.go, testnet/launcher/l1contractdeployer/docker.go, testnet/launcher/l2contractdeployer/docker.go
We only need the main containers to restart. Currently, even the helper containers have the setting, which is causing unexpected behaviour.
=> only configure docker autorestart on the main containers

go/host/l1/publisher.go, integration/networktest/tests/helpful/spin_up_local_network_test.go
UAT and Sepolia get stuck when publishing bundles due to a lacking return nil statement for republished bundles. This stuck happens on restart, as the node restarts from the 0th bundle and keeps forwarding until it synchronizes the state. 
=> Stopped returning errors on republish.

testnet/launcher/docker.go, testnet/launcher/gateway/config.go, testnet/launcher/gateway/docker.go, tools/walletextension/ratelimiter/rate_limiter.go
Disable rate limiting on local testnet by default, because we run some tests that require a lot of requests.
It includes also:
- usage of read locks where possible in rate limiting
=> disable rate limiting on local testnet

tools/walletextension/rpcapi/wallet_extension.go
Gateway usually crashed when doing L2 deploy or especially L2 upgrade.
This was due to:
```
CRIT [08-01|12:46:52.745] could not connect to new heads:          component=wallet_extension err="cannot subscribe to new heads to the backend timed out after 10m0s (16 attempts) - latest error: cannot fetch rpc connection to backend node could not create RPC client on ws://erpc.dev-testnet.obscu.ro:81. Cause: dial tcp 51.11.135.65:81: connect: connection timed out"
```
Increasing timeout to 20 minutes solves this issue.
=> increase new heads timeout

tools/walletextension/common/common.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/wallet_extension.go
using file logging was a temporary solution and is not needed anymore
=> remove file logger from the gateway

go/enclave/nodetype/common.go, tools/walletextension/rpcapi/transaction_api.go, tools/walletextension/rpcapi/utils.go
- the context exceeded error is not user-friendly
- increase the deadline for "send transaction"
=> improve deadline error

integration/constants.go
[Please provide a description and a link to the underlying ticket](https://github.com/ten-protocol/ten-internal/issues/3771)
Switched to unused 25000 port
=> Fix Network Test Port

tools/walletextension/common/constants.go, tools/walletextension/httpapi/routes.go, tools/walletextension/rpcapi/wallet_extension.go
We need gateway endpoint for getting network config:
[Ticket](https://github.com/ten-protocol/ten-internal/issues/3754)
=> Add network config endpoint

.github/workflows/manual-deploy-ten-bridge.yml, contracts/src/bridge/frontend/Dockerfile
manual-deploy-ten-bridge.yml and Dockerfile
=> [Bridge] Update environment variables for network config

integration/constants.go, integration/eth2network/main/cli.go, integration/eth2network/main/main.go, integration/eth2network/pos_eth2_network.go, integration/eth2network/pos_eth2_network_test.go, integration/eth2network/start-pos-network.sh, integration/noderunner/noderunner_test.go, integration/simulation/network/geth_utils.go, integration/smartcontract/smartcontracts_test.go
https://github.com/ten-protocol/ten-internal/issues/3777
* Check for active beacon network on startup
* Dial beacon network after startup
* Reduce unnecessarily long timeouts since merge happens in 2min
=> Beacon health check

design/ux/on_tx_hook.md
=> Design for EVM hook per tx

tools/walletextension/ratelimiter/rate_limiter.go
the Gateway crashes with concurrent RW errors
add mutex per user
=> fix concurrent rw error

tools/walletextension/ratelimiter/rate_limiter.go
=> fix concurrent rw error (#2027)

tools/walletextension/ratelimiter/rate_limiter.go
Last week I gateway crashed with the following error:
```
fatal error: concurrent map iteration and map write
goroutine 684 [running]:
github.com/ten-protocol/go-ten/tools/walletextension/ratelimiter.(*RateLimiter).SumComputeTime(0xc000440180, {0xb7, 0xe8, 0x4, 0xf1, 0x51, 0x44, 0xee, 0xe7, 0x5, ...})
/home/obscuro/go-obscuro/tools/walletextension/ratelimiter/rate_limiter.go:108 +0x10f
github.com/ten-protocol/go-ten/tools/walletextension/ratelimiter.(*RateLimiter).Allow(0xc000440180, {0xb7, 0xe8, 0x4, 0xf1, 0x51, 0x44, 0xee, 0xe7, 0x5, ...})
/home/obscuro/go-obscuro/tools/walletextension/ratelimiter/rate_limiter.go:197 +0x1a8
github.com/ten-protocol/go-ten/tools/walletextension/rpcapi.ExecAuthRPC[...]({0x1762fd0, 0xc0037ee690}, 0xc0005c0000, 0xc000297400, {0x13345f3, 0xe}, {0xc003a5cde0, …
```
=> fix concurrency issue in SumComputeTime

contracts/package.json
This change locks down the peer dependency for hardhat ethers to a concrete version that works with the current hardhat version we are using.
=> Lock down dependency.

go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql
Slow queries for getting head batch (6+ seconds with 1million batches).
=> Enclave DB: add composite index for canonical batch height

.github/workflows/manual-deploy-obscuro-gateway-database.yml, .github/workflows/manual-deploy-obscuro-gateway.yml, go/common/log/log.go, tools/walletextension/main/main.go, tools/walletextension/rpcapi/wallet_extension.go
There is an issue with Logging. 
`gethlog.<LEVEL>` does not translate correctly to actual log levels used in `log.New`.
I temporary fixed this, but bigger logging refactoring will be required in the future.
+ I removed also Datadog agents on the gateway as there is no use for them (we don't use Datadog anymore) and we switched to Grafana.  
=> Fix gateway logging and remove Datadog agents from gateway

tools/tenscan/frontend/src/routes/index.ts
Quick Fix/mask for anti-cheat of battleship
To prevent cheating on Battleships Game using the decryption feature
Temporarily removed the "Decrypt" option from the frontend
=> Remove Decryption feature from Tenscan frontend

go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/edgelessdb/edgelessdb.go
Grant full permissions to the user at creation time because it can't be changed later and that limits our testnet maintenance/debug options.
Get rid of obscuro naming.
=> EDB: rename user to ten and grant full db permissions

.github/workflows/manual-deploy-obscuro-gateway.yml
Chenged the format of env variable names to include `_` instead of `-`.
Github only allows aplhanumeric + `_` in env var names.
=> use "_" instead of "-" in Github env variables for the gateway

.github/workflows/build-pr.yml, integration/constants.go, integration/contractdeployer/contract_deployer_test.go, integration/eth2network/build_number.go, integration/eth2network/pos_eth2_network.go, integration/eth2network/pos_eth2_network_test.go, integration/eth2network/start-pos-network.sh, integration/faucet/faucet_test.go, integration/noderunner/noderunner_test.go, integration/simulation/devnetwork/config.go, integration/simulation/devnetwork/dev_network.go, integration/simulation/simulation_full_network_test.go, integration/simulation/simulation_geth_in_mem_test.go, integration/simulation/simulation_in_mem_test.go, integration/smartcontract/smartcontracts_test.go, integration/tengateway/tengateway_test.go, integration/tenscan/tenscan_test.go
https://github.com/ten-protocol/ten-internal/issues/3897
* Filter out the upload of `geth.ipc` on failure as this broke the build
* Add test name to l1 logs so you can tell which test is running for that scenario 
* Switch to `pkill` from `killall` on closing of processes so we don't have to exactly match the versions
=> Fix geth network on PR build

contracts/deployment_scripts/testing/001_gas_testing_deployment.ts, contracts/deployment_scripts/testing/003_simple_withdrawal.ts, go/common/crosschain.go, go/enclave/components/batch_executor.go, go/enclave/nodetype/sequencer.go, go/host/l1/publisher.go
Currently logging is insufficient for determining what is happening with cross chain messages. This PR adds some odd bits here and there in order to help us determine if a message has went in and was published.
=> Minor logging improvements to the cross chain messaging components

design/architecture/db_schema.puml, go/enclave/components/batch_executor.go, go/enclave/components/batch_registry.go, go/enclave/components/interfaces.go, go/enclave/components/rollup_compression.go, go/enclave/core/event_types.go, go/enclave/core/utils.go, go/enclave/enclave.go, go/enclave/evm/evm_facade.go, go/enclave/l2chain/interfaces.go, go/enclave/l2chain/l2_chain.go, go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go, go/enclave/rpc/GetBalance.go, go/enclave/storage/cache_service.go, go/enclave/storage/enclavedb/events.go, go/enclave/storage/enclavedb/interfaces.go, go/enclave/storage/enclavedb/utils.go, go/enclave/storage/events_storage.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go, go/host/storage/hostdb/block.go
We need to restructure the responsibilities to prepare for the configurable contract visibility.
- update database
- create placeholder for calling the evm config method
- refactor to use better data structures
- clarify responsibilities around event visibility
- remove account owner check when calling "getBalance", because it's not doing much
=> add plumbing for visibility config

.github/workflows/manual-deploy-testnet-l1.yml, .github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-deploy-testnet-validator.yml
Fixed hostname env var for promtail config
=> fixed host name for promtail config

go/common/tracers/debug_logs.go, go/enclave/core/event_types.go, go/enclave/storage/enclavedb/events.go, go/enclave/storage/enclavedb/interfaces.go, go/enclave/storage/events_storage.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql
This is part 2 for https://github.com/ten-protocol/go-ten/pull/2056
Part 3 will follow shortly.
This change should not break existing functionality.
- change the query logic to use the new configs
- clarify and fix the event type and event topic storage logic
=> event visibility config part 2

go/enclave/rpc/TenStorageRead.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go
Part 4 of the visibility work.
-allow storageAt for transparent contracts
=> allow storage at for transparnet contracts

go/enclave/rpc/TenStorageRead.go
The position of a storage slot needs to be in a certain format.
Fix the format
=> fix get_storage_at

go/enclave/storage/enclavedb/events.go
- to implement the event.sender_can_view functionality 
- update the event logs SQL 
=> wire sender in the events sql

tools/bridge-frontend/Dockerfile, tools/tenscan/frontend/Dockerfile, tools/walletextension/frontend/Dockerfile
=> add pnpm installation to Dockerfiles

.github/workflows/manual-deploy-ten-bridge.yml
=> Refactor deployment workflow for TEN Bridge

.github/workflows/manual-deploy-obscuro-gateway.yml, .github/workflows/manual-deploy-ten-gateway-frontend.yml
There were some problems with dexynth gateway deployment because some variable names containing `-` or `_`. It is fixed and deployed from that branch now.
Minor fixes in github actions scripts for the gateway.
=> github actions fix for dexynth gateway

go/enclave/evm/evm_facade.go
gen_ten_40 has revealed an issue with baseFee being payed twice for transactions. This is due to the zen token issuing.
Made it so execution gas payment only happens for evm runs that are configured to burn the baseFee from the sender, which is not the case for synthetic transactions.
=> Fix for gas payment overmint

go/enclave/core/event_types.go, go/enclave/enclave.go, go/enclave/evm/evm_facade.go, go/enclave/rpc/GetTransactionReceipt.go, go/enclave/rpc/rpc_encryption_manager.go, go/enclave/storage/cache_service.go, go/enclave/storage/enclavedb/events.go, go/enclave/storage/events_storage.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go, go/enclave/system/hooks.go
Retrieving tx receipts is expensive because the SQL query is complex.
The most common use case is that users will request receipts for recent transactions.
- introduce a cache of the most recent transactions
- implement the event visibility logic in-memory to filter out the logs from the cached receipts
- unrelated - there was an issue in the caching service where the 'cost' of some cache entries was wrong
- unrelated - remove unnecessary `tx.content` column from the receipt SQL query
=> cache receipts

.github/workflows/build-release-images.yml
currently images built every CI run and overwriting latest, this will set checkpoint images which can be reused and easier to manage.
new workflow to build and push images based on release tags.
=> tagged release images

testnet/launcher/gateway/docker.go
For hosted gateway we use grafana and we have agents running which use `std_out` to get logs. 
When stating the gateway from `go run testnet/launcher/cmd` we then have no way of getting logs for the gateway.
Changed log output from `std_out` to logfile.
=> Use log file when starting Ten Gateway from launcher

tools/walletextension/rpcapi/debug_api.go
the debug endpoint didn't work properly with "from"  blocks, because we were serialising the wrong type
serialise the correct type
=> fix debug log endpoint

go/config/enclave_cli_flags.go, go/enclave/evm/evm_facade.go, go/enclave/rpc/EstimateGas.go
Gas estimation currently is doing a binary search for the most optimal gas. This maxes it out and makes it run at maximum returning the gas used. Inefficient for complex contracts that have non deterministic logic based on provided gas, but those should potentially be handled through a separate rpc. 
Removed the binary search doEstimateGas in favour of estimateGasSinglePass
=> Single pass gas estimation.

testnet/launcher/gateway/docker.go
=> change default log path in local testnet gateway back to sys_out

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-upgrade-testnet-l2.yml
UAT deploy is broken
* use env vars the _correct_ way
=> Set beacon env vars for dev/uat/sep

go/ethadapter/geth_rpc_client.go, go/host/l1/publisher.go, integration/smartcontract/debug_mgmt_contract_lib.go, integration/smartcontract/debug_wallet.go, integration/smartcontract/smartcontracts_test.go
https://github.com/ten-protocol/ten-internal/issues/4148
* Increase gas fee cap for blob txs 
* use same timeout/ retry logic on debugWallet as SimWallets
* add check for isHostStopping in `ExtractRelevantTenTransactions` to prevent CRIT being thrown during network shutdown
=> Tweak blob gas pricing and improve debug wallet timeout

go.mod, go.sum, tools/walletextension/cache/cache.go, tools/walletextension/httpapi/routes.go, tools/walletextension/rpcapi/blockchain_api.go, tools/walletextension/rpcapi/debug_api.go, tools/walletextension/rpcapi/ethereum_api.go, tools/walletextension/rpcapi/filter_api.go, tools/walletextension/rpcapi/net_api.go, tools/walletextension/rpcapi/transaction_api.go, tools/walletextension/rpcapi/txpool_api.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/rpcapi/web3_api.go, tools/walletextension/services/conn_utils.go, tools/walletextension/services/gw_user.go, tools/walletextension/services/utils.go, tools/walletextension/services/wallet_extension.go, tools/walletextension/walletextension_container.go
In preparation for adding session keys, we need to clear responsibilities, because a lot of the services will be reused
- move the "services" to a separate package
- move all cache logic to its own package
=> clear responsibilities

testnet/docker-compose.local.yml, testnet/launcher/gateway/docker.go, testnet/testnet-local-build_images.sh, tools/walletextension/Dockerfile
This reverts commit a98ee3dd1b2cb1e621d8ca44b4c5eae25e40092b.
Those changes were causing problems in local testnet on linux VMs.
Reverting now and fixing it later.
=> Revert "log local testnet gateway logs to file (#2118)"

.github/workflows/manual-deploy-ten-gateway-frontend.yml, tools/walletextension/frontend/Dockerfile
Currently docker container doesn't build. It needs fixing to be able to be deployed from main.
- Changes in Dockerfile to allow it to build and start a contaner.
- minor fix in deployment script
=> Fix Gateway frontend dockerfile 

contracts/deployment_scripts/testing/003_simple_withdrawal.ts, contracts/deployment_scripts/testnet/layer2/001_whitelist_tokens.ts
Hardcoded msg bus address was breaking local network deployments.
Request msg bus address from cfg endpoint
=> Deploy scripts: load message bus address dynamically

go/enclave/system/hooks.go
Merging the code from main into the branch where it was cut off from has introduced a bug in the number of expected receipts. This pr fixes it.
=> Fix for load after keyless synthetic transactions

go.mod, go.sum, tools/walletextension/storage/database/cosmosdb/cosmosdb.go
We need to implement optimistic locking for CosmosDB.
Two threads could read an user from the database at the same time and then both can modify and store the user.
With current implementation both writes to database are successful which can cause us to loose some data without seeing an error anywhere. (Example: in both threads we add an account to user and the second thread overwrites the account being added by the first one).
Using ETag from CosmosDB to check if the version that we are overwriting is the same as the one that we read from.
=> use ETag with CosmosDB

testnet/launcher/gateway/docker.go, tools/walletextension/Dockerfile
Use the same Dockerfile as in deployed version (but in simulation mode) for local testnet and log to file and not to `std_out`
At the moment we are sticking to non SGX version of the gateway for local testnets, due to a problem with creating files inside SGX mode in simulation mode. Priority is to implement other tasks more crucial for mainnet release.
=> Log Gateway logs to a file

go/config/defaults/testnet-launcher/1-testnet-launcher.yaml
Recent chance to default logs level for sims has changed the log level on testnet to error which means we don't have good visibility on issues.
=> Default testnet launcher to info level logs

testnet/launcher/gateway/docker.go
Verbosity flag is a boolean flag and it should not have (true/false) set. 
This caused it to ignore all the other flags.
Fixed parameter passing in the local testnet gateway.
=> Disable rate limiting for local testnet and fix verbosity flag

tools/walletextension/httpapi/routes.go, tools/walletextension/rpcapi/blockchain_api.go, tools/walletextension/rpcapi/session_key_api.go, tools/walletextension/services/sk_manager.go, tools/walletextension/walletextension_container.go
To fix a few bugs raised after testing
- create a dedicated rpc endpoint: "sessionkeys_create" ,"sessionkeys_activate" ,"sessionkeys_deactivate" ,"sessionkeys_delete"
-  "sessionkeys_create" - returns a checksum address
- move validation logic to the "sk_manager"
=> fix session keys issue and add new dedicate rpc endpoint

tools/walletextension/rpcapi/session_key_api.go
- fix copy paste error on Activate
- return string from the sk.Create endpoint
=> Session Key -small fixes

go/host/enclave/guardian.go, integration/networktest/env/dev_network.go
Multi-enclave sequencer network test was failing because secret exchange takes a bit longer now and timeout was too low.
Also guardian wasn't including the enclave ID in its status logs which was very unhelpful.
=> HA: include enclaveID in guardian logs, fix HA netw test

.github/workflows/manual-deploy-obscuro-gateway-database.yml, .github/workflows/manual-deploy-obscuro-gateway.yml, .github/workflows/manual-deploy-testnet-l1.yml, .github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-deploy-testnet-validator.yml
We are missing container and node metrics in grafana 
Deployed cAdvisor and Node Exporter on each VM for system and container-level metrics collection.
Configured Prometheus on the VMs to scrape metrics from cAdvisor and Node Exporter.
Integrated Prometheus with a central metrics endpoint for unified monitoring and visualization.
=> Add cAdvisor and Node Exporter to VMs, Configure Prometheus for Central Metrics

.github/workflows/runner-scripts/wait-node-healthy.sh
Health end has been updated    to ten_health
endpoint method is update to ten_health from obscro_health
=> fixed ten_health endpoint in wait-node-health script

go/enclave/components/batch_registry.go, go/enclave/components/eth_chainadapter.go, go/enclave/components/interfaces.go, go/enclave/components/rollup_compression.go, go/enclave/enclave.go, go/enclave/enclave_admin_service.go, go/enclave/nodetype/interfaces.go, go/enclave/nodetype/sequencer.go, go/enclave/nodetype/validator.go, go/enclave/rpc/SubmitTx.go, go/enclave/rpc/TenStorageRead.go, go/enclave/rpc/rpc_encryption_manager.go, go/enclave/txpool/txpool.go, integration/eth2network/pos_eth2_network.go
- In preparation for HA, we need more flexibility on how the mempool behaves.
- The logic to start the mempool was unnecessarily complex
- remove "submitTransaction" from node type
- add additional logic to the mempool
- simplify the mempool start logic
=> remove "submitTx" from nodeType and improve mempool

go/enclave/storage/cache_service.go, go/enclave/storage/storage.go
Cache reads after node was promoted to sequencer were still returning old node type value in HA testing.
=> Enclave: update cache on nodetype change

go/enclave/rpc/GetTransactionReceipt.go, go/host/enclave/service.go, integration/networktest/tests/nodescenario/sequencer_multi_enclave_test.go
This addresses the performance issue we've been seeing.
The receipt cache was not used
- compare Addresses instead of pointers to addresses. (thanks golang)
=> fix address compare

.github/workflows/manual-deploy-obscuro-gateway-database.yml, .github/workflows/manual-deploy-obscuro-gateway.yml, .github/workflows/manual-deploy-testnet-l1.yml, .github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-deploy-testnet-validator.yml
We are migrating VM based monitoring stack to k8s 
Updating loki and prometheus push URIs
=> Replaced loki and prometheus push uris

go/host/rpc/clientapi/client_api_ten.go, go/rpc/network_client.go, tools/walletextension/common/common.go, tools/walletextension/services/conn_utils.go
Cache the RPC key on the client side ( the Ten gateway).
The previous implementation made an extra RPC call for every RPC.
- cache the rpc key on the client
- cache the rpc key on the host
=> cache rpc key

tools/walletextension/storage/cert_storage.go, tools/walletextension/storage/database/cosmosdb/cert_storage_cosmos.go, tools/walletextension/walletextension_container.go
We want to have static https certificate (using the same private key) even after restarts & certificate renewals etc.
Certificate and private key were previously stored in memory and in file on attached volume. 
This is not ideal as it is stored unencrypted and in case of volume is deleted the private key and certificate are deleted.
Much better solution is to store both private key and certificate in encrypted CosmosDB.
- implementation of `autocert.Cache` in which we store certificate and private key in cosmosDB and encrypt it.
- using this approach only for CosmosDB (for other databases - sqlite, we still use file storage for certificate and private key)
- 
[PR …
=> Store certificate and private key in encrypted CosmosDB database

tools/walletextension/rpcapi/net_api.go
net_version call was not working on the gateway
change name of the function called to match actual endpoint
=> fix bug with net_version call on the gateway

go.mod, go.sum, lib/gethfork/debug/flags.go
There's a library called memsize that geth was using which is broken by Go 1.23 and the author of memsize is advising geth forks to remove the dependency with this patch: https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644
Remove memsize dep.
=> gethfork: remove broken memsize dependency

tools/walletextension/frontend/src/components/providers/wallet-provider.tsx
In out current frontend code we don't refresh the page after adding new account.  Instead it shows us the page like we never added a network, etc.
PR with video: https://github.com/ten-protocol/ten-internal/issues/3567
- Improved frontend code with page refresh when new account is added to update everything needed.
=> refresh when new account is added to improve UX

go/enclave/components/batch_executor.go
In order to have better book keeping on the message bus, the native transfers that get sent back to l1 need to be burned (as they are minted when they are inbound)
A new function in the batch executor that goes over the transfers and burns the value.
=> Remove balance of message bus for burned native value.

.github/workflows/manual-deploy-testnet-l2.yml, contracts/scripts/sequencer/001_grant_sequencers.ts, testnet/launcher/docker.go, testnet/launcher/l1grantsequencers/cmd/cli.go, testnet/launcher/l1grantsequencers/cmd/cli_flags.go, testnet/launcher/l1grantsequencers/cmd/main.go, testnet/launcher/l1grantsequencers/config.go, testnet/launcher/l1grantsequencers/docker.go
Pre-requisite for HA sequencer stuff in testnets we need to empower the sequencer enclaves on the L1.
- Make grant permission script accept a node host to request enclaveID instead of only accepting enclaveIDs
- have that script called by GH action script
=> Testnets: grant sequencer enclaveID permission on L1

.github/workflows/manual-deploy-testnet-l2.yml, integration/common/constants.go, integration/contractdeployer/contract_deployer_test.go
We need to make the private keys for the L2 a secret.
Added new secrets to github:
L2_DEPLOYER_KEY (main account that deploys)
L2_HOC_KEY ( this is still an artefact that needs removal )
L2_POC_KEY ( this too )
=> Remove hardcoded PKs concerning deployment.

go/common/types.go, go/enclave/rpc/vk_utils.go, go/enclave/storage/cache_service.go, go/enclave/storage/enclavedb/events.go, go/enclave/storage/enclavedb/interfaces.go, go/enclave/storage/events_storage.go, go/enclave/storage/storage.go, go/rpc/encrypted_client.go
- to improve performance
- fix for gateway when running against a different network ( which happens during redeploys)
- add caching for event topics
- use the contract cache everywhere
- add error handling when executing sensitive requests to read the key and retry
=> caching for event topics and contract address

go/config/defaults/0-base-config.yaml, go/config/enclave.go, go/enclave/config/config.go, go/enclave/crosschain/message_bus_manager.go, go/enclave/enclave_rpc_service.go, go/enclave/evm/evm_facade.go, go/enclave/genesis/genesis_test.go, go/enclave/l2chain/interfaces.go, go/enclave/l2chain/l2_chain.go, go/enclave/main/enclave.json, go/enclave/rpc/GetLogs.go, go/enclave/rpc/GetPersonalTransactions.go, go/enclave/rpc/GetTransaction.go, go/enclave/rpc/GetTransactionReceipt.go, go/enclave/rpc/TenEthCall.go, go/enclave/rpc/rpc_utils.go, go/enclave/storage/storage.go, go/enclave/system/contracts.go, go/node/cmd/cli.go, integration/common/constants.go, integration/simulation/devnetwork/node.go, integration/simulation/network/network_utils.go, integration/simulation/transaction_injector.go, integration/tengateway/tengateway_test.go, testnet/launcher/docker.go, tools/hardhatdeployer/contract_deployer.go
- To reduce the overhead of the sequencer enclave. Also reduces the memory requirements.
- The GasLimit per batch was wrong by orders of magnitude. Now it is set by default to 1/3 of an Ethereum block.
- add a new config
- execute the logic that stores receipts and logs only when the flag=true
- check in the rpc calls that the flag is true 
- some minor name refactors
- set the gas limit to a sane value
- reduce the batch size in bytes by 10%. Hopefully, this is a value that can be processed without delays
=> New config flag to store executed transactions

dockerfiles/enclave.Dockerfile, tools/edbconnect/Dockerfile, tools/walletextension/enclave.Dockerfile
upgrade to latest ego docker image
=> upgrade ego

.github/workflows/manual-deploy-testnet-l2.yml, go/common/types.go, go/enclave/crosschain/interfaces.go, go/enclave/crosschain/message_bus_manager.go, go/enclave/enclave.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go, go/enclave/system/contracts.go, go/enclave/system/hooks.go, integration/networktest/tests/helpful/spin_up_local_network_test.go
Currently we have a bug in hooks.go:Load() method; It does not initialize the message, bus and upon change of the bytecode is unable to find the correct receipt for the unmarked synethic transaction. 
Removed dependence on the receipt and moved to use config table. First time init will write into it, Load fetches.
=> Changed how loading works.

go/config/defaults/testnet-launcher/2-sequencer.yaml, go/config/defaults/testnet-launcher/2-validator.yaml, testnet/launcher/docker.go
[This PR](https://github.com/ten-protocol/go-ten/pull/2201) broke the local testnet starter script (which breaks the e2e tests).
Auto-refactor of a method had it trying to start the nodes with 0 enclaves instead of 1.
Missed updating launcher config with new indexed naming convention for enclaves.
Fix the param and config.
=> Local testnet: fix node starter param

go/common/custom_query_types.go, integration/tengateway/tengateway_test.go, packages/ui/routes/index.ts, tools/walletextension/frontend/src/api/ethRequests.ts, tools/walletextension/frontend/src/components/providers/wallet-provider.tsx, tools/walletextension/frontend/src/services/ethService.ts, tools/walletextension/frontend/src/services/useGatewayService.ts, tools/walletextension/rpcapi/blockchain_api.go, tools/walletextension/storage/database/sqlite/sqlite.go
At the moment we are using local getStorageAt with argument 0x0 to get userID/token that is used in Metamask.
This is very risky and security vulnerability since any app that we connect to can make this call and it will be able to see token and with it our private data.
- sqlite fix that allows us to run it locally 
- removing getStorageAt part where the gateway returns usedID and test that tests that
- frontend change to use local storage instead of getStorageAt calls
=> remove getStorageAt returning token and use local storage instead 

integration/simulation/network/geth_utils.go, integration/simulation/network/socket.go
Soon the enclaves will require that batches are signed by permissioned enclave IDs. The testnets already permission the enclaveID for their sequencer but the sim doesn't so this brings the sim in-line.
=> Sim: permission enclaveID for sequencer

go/common/errutil/evm_serialisable.go, go/enclave/evm/evm_facade.go, go/enclave/l2chain/l2_chain.go, go/enclave/rpc/EstimateGas.go, go/enclave/rpc/TenEthCall.go, go/enclave/rpc/rpc_utils.go, go/responses/responses.go, go/responses/types.go, integration/simulation/network/network_utils.go
- convert EVM errors at a higher level 
- estimate gas was losing a revert error
- remove intrinsic gas low check because we are doing a single gas estimate pass
=> fix errors and gas estimate

tools/edbconnect/edb-connect.sh, tools/edbconnect/main/main.go
We changed the edb default host name (obscuronode-edgelessdb-0). Allowing us to set it means the tool can still be used for sepolia and for the HA db (obscuronode-edgelessdb-1).
=> edb-connect: fix edb default host and allow caller to set it

.github/workflows/manual-deploy-obscuro-gateway.yml
At the moment when we redeploy TEN Gateway we delete and recreate whole VM which deletes also the volume where the encryption key is sealed. Since we store certificates in cosmosDB encrypted and we don't get the encryption key from previous version of the gateway we cannot read old certificates resulting in certificate error.
New option when deploying to redeploy to the same VM (volume and sealed encryption key stays there) so we can easily redeploy the gateway without issues with the certificate.
Since we don't need to delete and recreate VM on Azure it also reduces deployment time. In case we want to make fresh deployment when we have some larger changes we can still do it by selecting it in github actions.
Please indicate below by ticking the checkbox that you have read and performed …
=> persistent volume and option to deploy to the same VM

go/config/defaults/0-base-config.yaml, go/enclave/components/batch_executor.go, go/enclave/components/txpool.go, go/enclave/enclave.go, go/enclave/enclave_admin_service.go, go/enclave/limiters/batchlimiter.go
- this enables batches and rollups to be created in parallel. (to avoid pauses in batch creation when rollups are created)
- bump the batch size to 128kb - which is the max tx size (to avoid txs remaining in the mempool)
=> optimize mutexes and increase batch size

.github/workflows/manual-deploy-obscuro-gateway.yml
Previously docker sometimes used cached version of the gateway image to redeploy. Now we force pull and we get the latest image.
force docker pull
=> force docker pull on each redeploy

tools/walletextension/cache/RistrettoCache.go, tools/walletextension/cache/cache.go, tools/walletextension/common/config.go, tools/walletextension/services/wallet_extension.go
the `newHeads` subscription is not entirely reliable, and in case of delays, we can get inconsistent results.
- introduce a ticker to evict the cache even if the new Head is delayed
=> introduce a more robust cache eviction mechanism

.github/workflows/manual-deploy-obscuro-gateway.yml, tools/walletextension/common/config.go, tools/walletextension/main/cli.go, tools/walletextension/storage/cert_storage.go, tools/walletextension/storage/database/cosmosdb/cert_storage_cosmos.go, tools/walletextension/walletextension_container.go
At the moment we always encrypt our https certificate. In case we need to do hard redeploy (often during testing different things) we need to request the certificate again from LetsEncrypt. It also has some weekly limits that we started to hit.
By using unencrypted certificate it can be used over redeploys even in case when the encryption key is lost/changed due to a redeploy of a whole VM.
This flag should be set to `true` in mainnet, but for testnets we can use the default value (`false`).
- new flag that can disable certificate encryption & decryption on testnets.
=> Add an option to disable certificate encryption

go/common/host/services.go, go/host/enclave/guardian.go, go/host/enclave/service.go, tools/walletextension/common/config.go
Treating single-enclave nodes and backup enclaves as being critical made some things more fragile than they needed to be.
Also evicting enclaves was happening a bit too quickly, causing race conditions at startup etc.
Slow down eviction. Enclave service only evicts active sequencers (no need for single-enclave validators).
=> Host: only evict HA sequencer enclaves

contracts/scripts/net-cfg.ts, go/enclave/enclave_rpc_service.go, go/enclave/system/hooks.go
Contract addresses are not loaded properly resulting in an NPE on restarts.
=> Fix for NPE on restart

go/enclave/crosschain/interfaces.go, go/enclave/crosschain/message_bus_manager.go, go/enclave/crosschain/processors.go, go/enclave/enclave.go, go/enclave/rpc/SubmitTx.go
We don't use this now we've got keyless transactions. 
* Removing a bunch of unused code from message bus interface
=> Remove message bus owner key

tools/walletextension/rpcapi/utils.go
A segmentation fault was occurring during the audit function call while formatting RPC call results (res) and errors (err).
More details: https://github.com/ten-protocol/ten-internal/issues/4479
- replaced %s with %+v for res and err in audit logs to handle complex or nil values gracefully.
- changed var resp *R to var resp R to avoid unnecessary pointer dereferences
- added separate audit calls for success and error scenarios to prevent undefined behavior
=> Fix Segmentation Fault in UnauthenticatedTenRPCCall in audit

tools/walletextension/metrics/metrics.go, tools/walletextension/rpcapi/utils.go, tools/walletextension/services/wallet_extension.go, tools/walletextension/storage/database/cosmosdb/metrics_storage.go, tools/walletextension/storage/storage.go, tools/walletextension/walletextension_container.go
We would like to have some metrics of the gateway usage. We were able to get some of those metrics from the unencrypted database before. But with encrypted database we don't have that ability anymore.
- new metrics package that allows us to count number of users, accounts registered and active users in last month
- we are displaying those statistics every day in logs where we can easily see them
- Metrics are available also in cosmosDB (which is also used to persist metrics in case of app restarts, etc)
=> Collect metrics from the gateway

go/host/enclave/guardian.go, integration/simulation/devnetwork/dev_network.go, tools/walletextension/rpcapi/utils.go
Backup sequencer was spending a lot of time unhealthy because it wasn't receiving batches directly from the seq host.
Allow backup sequencer to be in L2 catchup mode.
=> Backup sequencer: fix catchup issues

go/enclave/components/interfaces.go, go/enclave/components/rollup_consumer.go, go/enclave/enclave_admin_service.go
https://github.com/ten-protocol/ten-internal/issues/4483
* If multiple rollups are found in the same block, check they have unique tx hashes before storing the block/ rollup
* change the logger warning to trace as it will only reach that point if we have multiple rollups with unique txs in the block (ie in mem test) 
=> Prevent multiple blobs/ rollups in the same tx 

go/enclave/components/rollup_consumer.go, go/enclave/components/sigverifier.go, go/enclave/enclave_admin_service.go, go/enclave/nodetype/validator.go, integration/ethereummock/mock_sigverifier.go
https://github.com/ten-protocol/ten-internal/issues/4437
* new mock signature verification and check for in memory DB to set it 
=> Mock Signature Verificaiton

integration/ethereummock/node.go
This manifested as split brains on the mock l1
Properly set the l1 head during forks
=> fix mock l1

tools/walletextension/common/common.go, tools/walletextension/services/wallet_extension.go
At the moment we log userIDs to logs in plain text. This is a security issue as even we shouldn't be able to see that userIDs are.
https://github.com/ten-protocol/ten-internal/issues/4523
- Double hash userIDs before logging them
Double hashing prevents us or anyone who can see the logs from getting userID and being able to see what is happening with this user. 
Using double hash still gives us some information about which user is performing which action so we are still able to debug things.
=> use double hash for userID logging

.github/workflows/manual-deploy-obscuro-gateway.yml
We want to be able to disable caching by setting github env. variable `GATEWAY_DISABLE_CACHING` to `true`.
Changed github actions script
=> disable caching with github env variable

integration/simulation/transaction_injector.go
There is a panic happening during valid database closed error being returned as the test is finishing. This fixes it.
Added a return without doing anything meaningfull when this error is encountered, which stops the gorotuine.
=> Fix flakiness.

go/enclave/storage/enclavedb/batch.go, go/enclave/storage/enclavedb/events.go
There was a bug in the "personal transactions" query.
The requester condition was part of the join instead of part of "where"
- fix the query
=> fix personal txs query

go/common/crosschain.go, go/enclave/components/batch_executor.go, go/enclave/components/rollup_compression.go, go/enclave/components/rollup_consumer.go, go/enclave/components/shared_secret_process.go, go/enclave/crosschain/block_message_extractor.go, go/enclave/crosschain/common.go, go/enclave/crosschain/interfaces.go, go/enclave/crosschain/message_bus_manager.go, go/enclave/enclave_admin_service.go, go/enclave/rpc/vk_utils.go, go/enclave/system/contracts.go, go/ethadapter/erc20contractlib/erc20_contract_lib.go, go/ethadapter/mgmtcontractlib/mgmt_contract_lib.go, go/host/l1/dataservice.go, go/host/l1/publisher.go, go/host/rpc/enclaverpc/enclave_client.go, go/responses/responses.go, integration/ethereummock/erc20_contract_lib.go, integration/ethereummock/mgmt_contract_lib.go, integration/ethereummock/mock_l1_network.go, integration/ethereummock/node.go, integration/simulation/output_stats.go, integration/simulation/simulation.go, integration/simulation/transaction_injector.go, integration/simulation/validate_chain.go, integration/smartcontract/smartcontracts_test.go
We were panicking in some improbable scenarios. Mostly leftovers from the early days when we didn't handle errors.
Return errors instead of panic.
=> improve error handling

integration/networktest/env/network_setup.go, integration/networktest/tests/gateway/gateway_test.go
Network tests failing against testnet gateways because URLs are wrong
=> Tests: fix rpc urls to match testnet gateways

go/host/l1/dataservice.go
We've got a bug when a new node has to do a long L1 catch-up where it's taking minutes searching backwards to find the next block to feed.
Compare with the canonical block at the remote head height, don't need to build full fork path to head.
=> Host: shortcut the next canonical block lookup

.devcontainer/devcontainer.json, .devcontainer/install-deps.sh
As we updated ego and raised the go version, the dev container became stale at 1.21
Upped the version; However the official one is 1.22.10 in the dev container docker image, thus added a manual part that downloads 1.22.11 (claude did it, seems to work, hurray) 
=> Update dev container to match new required go version.

go/enclave/components/rollup_compression.go, go/host/enclave/guardian.go, integration/simulation/simulation.go, integration/simulation/simulation_in_mem_test.go
Flakyness fixes
- in the sim, wait for the nodes to be ready using polling
- only publish a rollup if the compression block has not been reorged
=> flakyness fix

go/host/p2p/p2p.go
Health check fails for health sequencers in all environments, because the p2p health check is failing unnecessarily. Sequencers don't receive batches so have no expected p2p traffic currently.
```
> curl http://obscuronode-0-uat-testnet.uksouth.cloudapp.azure.com:80  -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"ten_health","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"OverallHealth":false,"Errors":["[p2p] not healthy - no message received from peers"],"Enclaves":[{"StatusCode":0,"L1Head":"0x5a86a913366b01ea9304b5b38a9d155ea1c7e1d2cdf946da509ee4e1765395c8","L2Head":370086,"EnclaveID":"0x09abfd84a5a0fbbed92d8933293c0621a91dadd5"},{"StatusCode":0,"L1Head":"0x5a86a913366b01ea9304b5b38a9d155ea1c7e1d2cdf946da509ee4e1765395c8","L2Head":370086,"EnclaveID":"0xfa14ffa …
```
=> Host: fix failing p2p check for sequencers

go/enclave/enclave.go, go/enclave/enclave_admin_service.go, go/enclave/storage/enclavedb/batch.go, go/enclave/storage/enclavedb/block.go, go/enclave/storage/init/edgelessdb/001_init.sql, go/enclave/storage/init/sqlite/001_init.sql, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go, integration/simulation/transaction_injector.go
An enclave can die while processing an L1 block. 
Because the processing itself is not atomic (for performance reasons), it can leave the database in an intermediary state.
- Create a new field in the "block" table to mark when the processing is finished
- On startup, check and remove any dirty (un-finished) blocks.
- Remove a field that was no longer necessary from the "batch" table.
=> make sure blocks are fully processed

go/host/storage/hostdb/batch.go, go/host/storage/hostdb/batch_test.go, go/host/storage/hostdb/block_test.go, go/host/storage/hostdb/rollup_test.go, go/host/storage/hostdb/transaction_test.go, go/host/storage/hostdb/utils.go, go/host/storage/storage.go, go/host/storage/storage_test.go
Getting a lot of batch duplicate key errors on the UAT validators due to bad error handling
* return nil if the record exists and check for it in the `dbTx.Commit()` as well
* add storage unit test for the logic 
=> Fix duplicate key error on host batch insertion

go/host/storage/hostdb/rollup.go, go/host/storage/storage.go
https://github.com/ten-protocol/ten-internal/issues/4619
* Add same error handling if we encounter a duplicate key error on rollup insertion as we added for writing batches
=> Duplicate rollup error handling 

go/common/subscription/new_heads_manager.go, go/enclave/components/batch_registry.go, go/enclave/enclave_admin_service.go, go/enclave/events/subscription_manager.go, go/enclave/storage/enclavedb/batch.go, go/enclave/storage/storage.go
To avoid deadlocks
- reduce the scope of various mutexes
- remove a query that is no longer necessary ( because of a previous PR)
=> optimize locks

go/enclave/enclave_admin_service.go
This info level log msg was getting spammed by enclave during initial L1 catchup of a new node (because it doesn't see its own attestation until it gets close to the latest L1 blocks, it was only just sent).
Downgrade spammy log msg
=> Enclave: avoid log spam during initial L1 catchup

go/enclave/components/rollup_consumer.go, go/enclave/core/utils.go, go/enclave/enclave_admin_service.go, go/host/rpc/enclaverpc/enclave_client.go
ERRORs in the logs that are definitely not errors, not even warnings in some functions that take longer - rollup creation/ consumption for example.
* Add an optional `RelaxedThreshold` parameter you can provide to the `LogMethodDuration` to set the values to longer timescales. 
=> Add relaxed log method duration threshold

.github/workflows/manual-deploy-obscuro-gateway.yml, tools/walletextension/rpcapi/utils.go, tools/walletextension/services/wallet_extension.go
We experienced crashes in the gateway when testing in UAT.
- Auto restart will enable the gateway container to auto restart if the crash happens again
- Crash is very likely coming from collecting metrics on active users and it needs to be refactored. Commenting this out to confirm and in the next PR I will introduce new way of measuring user activity in the GW.
=> Auto restart TEN Gateway and comment out collecting metrics

go/config/defaults/0-base-config.yaml, go/enclave/components/rollup_consumer.go, go/host/l1/dataservice.go
Rollups not being found in blocks on k8s validator and no way to determine why currently. 
* Debug logging on the host and enclave side
=> Debug logging for rollups to see if we're losing any

go/ethadapter/utils.go
Hitting maxRetries error on sepolia for blob txs
* Add 2x multiplier to `BlobFeeCap` enforced by the blobpool when retrying the blob txs
=> Add blob fee cap retry multiplier

go/enclave/rpc/GetPersonalTransactions.go, go/enclave/rpc_server.go, go/enclave/storage/enclavedb/batch.go
- We were returning a system error and an "internal error" - to the user - when there were no personal txs.
- Fix the error log for the encrypted rpc
=> Fix personal txs

go/host/storage/init/postgres/postgres.go, go/host/storage/storage.go
We're getting connection issues on postgres
This adds some parameters and also closes resources more reliably
=> postgres tweaks

testnet/launcher/docker.go
Both containers start at the same time with diff hardhat instances using hte same private keys and sending transactions.
Made the process sequential as it should be. 
=> Fix for race condition on underpriced tx

go/enclave/gas/oracle.go, go/enclave/rpc/EstimateGas.go
When estimating gas, we were ignoring all fields except "data".
For value transfers, without "data", the l1 cost for estimation differed a lot from the actual execution.
This was apparent when blob prices were high.
=> fix gas estimation

go/enclave/components/batch_executor.go, go/enclave/components/interfaces.go, go/enclave/components/rollup_compression.go, go/enclave/enclave.go, go/enclave/evm/evm_facade.go, go/enclave/nodetype/sequencer.go, go/enclave/restore_statedb.go, go/enclave/rpc/TenStorageRead.go, go/enclave/storage/enclavedb/batch.go, go/enclave/storage/interfaces.go, go/enclave/storage/storage.go
On testnet we experienced a bug after a node restart where the root hash was different.
- refactor batch execution to avoid a separate commit function
- this avoids the use of "statedb.IntermediateRoot"
- remove some satedb.finalize calls  - unclear why they were needed
- refactor the statedb/main db synch to only mark batches as unexecuted, instead of trying to execute them.
=> refactor and fix statedb

go/config/defaults/0-base-config.yaml, go/enclave/components/batch_executor.go, go/enclave/components/txpool.go, go/enclave/core/batch.go, go/enclave/enclave.go, go/enclave/evm/l1_publishing_gas.go, go/enclave/rpc_server.go
Check l1 costs on validators to return a meaningful error to the users
- on validators check that the tx is submitted with enough gas to pay the l1 costs
=> Add mempool l1 gas check

go/common/host/host.go, go/common/host/services.go, go/host/host.go, go/host/l2/batchrepository.go, go/host/rpc/clientapi/client_api_chain.go
We get a lot of errors like this:
> ERROR[02-21|10:43:11.640] Error getting receipt                    node_id=0xBD0D613bCbDbcC93abE025117564cc4435896A5F cmp=enclave err="unable to get balance - unable to get blockchain state - batch with requested height 249443 could not be retrieved. Cause: not found"
because the host returns batches that were not processed yet by the enclave.
only return confirmed batches as the head
=> host should return only confirmed batches

go/host/l1/dataservice.go
=> fix increment

tools/walletextension/ratelimiter/rate_limiter.go, tools/walletextension/storage/database/common/db_types.go, tools/walletextension/storage/database/cosmosdb/cosmosdb.go, tools/walletextension/storage/database/sqlite/sqlite.go, tools/walletextension/storage/storage_test.go
To return clean error on GW requests without a valid userid
- create user not found error
- fix metric logging
=> add userNotFound error

go/enclave/rpc/EstimateGas.go
Bump the gas estimation overhead to 33%.
=> bump the estimation overhead

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-upgrade-testnet-l2.yml
Reduce risk by requiring user to type 'confirm' to deploy/upgrade sepolia.
=> Deploy: require confirmation for sepolia deployments

testnet/eth2network.Dockerfile
bookworm has the glibc version we need
=> base image to bookworm

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-upgrade-testnet-l2.yml, integration/networktest/env/network_setup.go
We turned off the second enclave because of fragility in testnets but with recent commits that should be solved on main now.
=> Testnet: re-enable HA enclaves in testnet deployments

go/config/defaults/0-base-config.yaml, go/enclave/core/batch.go, go/enclave/crosschain/message_bus_manager.go, go/enclave/evm/no_op_engine.go, go/enclave/rpc_server.go, go/enclave/storage/storage.go, go/ethadapter/geth_rpc_client.go, go/ethadapter/interface.go, go/ethadapter/utils.go, integration/ethereummock/node.go, integration/simulation/simulation.go, integration/simulation/validate_chain.go
Move to the go-ethereum statedb "Path scheme" (from the "Hash scheme" which is deprecated).
General cleanup
- use PathScheme
- remove todos
- remove unnecessary functions from the `EthClient` and move to utils
=> small fixes

go/config/defaults/0-base-config.yaml, go/enclave/components/rollup_compression.go, go/enclave/components/rollup_consumer.go, go/enclave/enclave_admin_service.go
To match the production setup, rollups must be able to be produced less frequently, when usage it low, to optimize costs
- increase the rollup timeout to 2hrs
- optimize rollup processing. The validator can skip when the last batch exists and the hash matches.
Todo: as part of a different PR, the sequencer will produce rollups on the backup enclave.
=> optimize rollup processing and increase rollup timeout

go/host/enclave/service.go
This change addresses an issue with single enclave nodes where the host would not promote the enclave after it was restarted.
Host changed to behave the same with promoting dead enclaves, regardless of how many enclaves are configured.
=> Host: handle promotion for single-enclave node recovery

go/ethadapter/blob_beacon_client_test.go, go/host/l1/blobresolver_test.go
One of the providers has deprecated their API. Need to spend time finding the right mixture of request params to trigger a failure on one provider to fall to the next. 
Skipped them for now as low priority
=> Skip beacon provider tests for now 

go/common/retry/retry.go, go/host/l1/publisher.go
Silent failures making it hard to diagnose testnet issues. Particularly for L1 tx (non-blobs) which retry forever.
Also Tudor recently added a WithCount version for the retry func so seems like a good fit here.
=> Host: log l1 tx failures between retries

go/common/storage/driver_wrapper.go, go/enclave/storage/init/edgelessdb/edgelessdb.go, go/host/storage/db_init.go, go/host/storage/init/postgres/postgres.go
When the host database dies, we encounter unexpected behaviour. It's better to just panic the host process and let it restart automatically when the db is back up
- move the SQL driver wrapper to common
- use it for postgres
- small refactor and adding custom "isCritical" function
=> move driver wrapper to common and use it for the host postgres db

.github/workflows/manual-decommission-testnet-l1.yml, .github/workflows/manual-decommission-testnet-l2.yml
Adds workflows to allow us to decommission an L1 or L2 network on UAT and Dev to allow us to save costs when not requiring them to be running.
=> Add decommission workflows

.github/workflows/build-gateway-lib.yml, .github/workflows/build-pr.yml, .github/workflows/golangci-lint.yml, .github/workflows/hardhat-pr-check.yml, go/host/host.go
To make publishing l1 txs more reliable
=> bump l1 receipt wait time

go/enclave/rpc/SubmitTx.go
Check tx.chainId before adding to the mempool to avoid weird behaviour
=> check tx.chainId before adding to the mempool

go/enclave/enclave_admin_service.go
Stop backup enclave killing itself when it's asked to produce a rollup.
Allowing direct access to this service smells a bit, I think this services thing might need a slight refactor to more clearly fit the validator/sequencer/active-sequencer enclave types but couldn't see a clean way to achieve that under time pressure.
=> Enclave: tweak to allow non-active sequencer to use CreateRollup

go/host/storage/hostdb/batch.go, go/host/storage/hostdb/sql_statements.go, go/host/storage/init/postgres/001_init.sql, go/host/storage/init/sqlite/001_init.sql
This PR adds a new `txs_size` column to the `batch_host` table, modifying database schema and related SQL statements.
This allows us to more accurately estimate roll-up size.
Now we see that rollups are being triggered by interval timeout rather than size caps but the size is non-zero and the queries are working. There will still be tuning required of course but that's config based.
=> Host: include estimated transactions size in batches table

go/common/viewingkey/viewing_key_messages.go, tools/walletextension/frontend/src/api/ethRequests.ts, tools/walletextension/frontend/src/lib/constants.ts, tools/walletextension/frontend/src/services/useGatewayService.ts
With recent Metamask update field `verifyingContract` became mandatory. 
In the past we used EIP-712 message without it, because no contract is verifying it and we only check it in the gateway.
We added `verifyingContract` to both FE and BE inside EIP-712 message.
Verifying contract is set to `0x0` address. Is there any good reason why we should use the address of `management contract`.
=> add verifying contract to gateway eip712 message

tools/tenscan/frontend/src/services/useContractsService.ts
After splitting ManagementContract: 
https://github.com/ten-protocol/go-ten/commit/848428fdbb5c7e3493f04d9d0257645ebc42cc1b#diff-6d91c392b4adaf4cc04af487236a674e93068b7066aeb2c7cc0e2ce65d40f45aL113
We are using multiple addresses and not just a single ManagementContract address and this needs to be reflected also in Tencan.
=> Fix displayed contract addresses on Tenscan

go/common/rollups.go, go/common/rpc/converters.go, go/enclave/components/rollup_consumer.go, go/enclave/core/rollup.go, go/enclave/core/utils.go, go/enclave/debugger/tracers.go, go/enclave/enclave_admin_service.go
- we were getting "rollup not found" errors on the host
- `LogMethodDuration` is annoying
- remove hash caching for the rollup because we mutate the rollup header during construction
- tweak LogMethodDuration to log at Info or lower only
=> fix rollup not found errors and tweak duration logging

tools/walletextension/httpapi/routes.go
We changed the message format and we were still not displaying verifyingcontract which caused the message to be wrong.
=> fix /getmessage endpoint in the GW

go/host/l1/dataservice.go, integration/simulation/network/inmemory.go
Currently, the integrity of the host L1 block storage depends on the reliability of the "newHeads" subscription.
Introduce an extra check and logic to fetch missing blocks during the "newHeads" subscription handling
=> Fix missing blocks from L1 "newHeads" subscription

go/host/container/host_container.go, go/host/l1/dataservice.go, integration/simulation/devnetwork/node.go, integration/simulation/network/network_utils.go
To fix a bug that appears on testnet
- instead of comparing to genesis, compare to the `cfg.L1StartHash` when stopping the recursive `fetchAncestors`
=> fix newHeads logic for fetchAncestors

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml, .github/workflows/manual-deploy-k8s-testnet-before-nodes.yml
To start testing the before/after node deployment k8s scripts we need to get them merged so they are available in the GH actions workflows.
=> k8s: placeholder scripts for initialise and finalise testnet

.github/workflows/manual-deploy-k8s-testnet-before-nodes.yml
Accidentally duplicated main testnet deploy name, need to fix that to avoid confusion.
=> GH Actions: fix script name to avoid chaos

.github/workflows/manual-deploy-obscuro-gateway.yml, tools/walletextension/common/config.go, tools/walletextension/keymanager/keymanager.go, tools/walletextension/main/cli.go
It was confusing which value was read and there were some issues in the recent version of the code preventing gateway to get the keys we wanted.
- Changed `KeyExchangeURL` to `EncryptionKeySource` for better clarity of purpose
- The new parameter name better reflects its role in the key management process
The `EncryptionKeySource` parameter now supports three distinct modes:
- Attempts to unseal an existing encryption key
- If no key is found, fails with a clear error message
- Requires operator intervention to either:
- Provide a key source
- Generate a new key
- First checks for an existing sealed key
- Only generates a new key if no existing key is found
- Prevents unnecessary key regeneration
- Preserves existing keys when possible
- Performs secure key exchange with the specified …
=> Fix gateway encryption key handling

go/enclave/components/gas_estimate.go, go/enclave/components/txpool.go, go/enclave/rpc/EstimateGas.go
A new check added to the mempool validation was too strict and was failing valid transactions
- make it more lenient by allowing a 20% margin
=> tweak mempool validation

go/enclave/storage/init/edgelessdb/edgelessdb.go
Fail the enclave on "invalid connection" to avoid the enclave entering an invalid state
=> Add new catastrophic error to edb

go/enclave/storage/enclavedb/enclave_sql_db.go
We had a weird error on the testnet where the "value" was nil. It failed at db "commit" time, because it violated the NULL db constraint
- check for nil early to fail the offending transaction
=> implement key-value nil check

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml, go/config/defaults/0-base-config.yaml, go/config/deployment.go, testnet/launcher/docker.go, testnet/launcher/l2contractdeployer/config.go, testnet/launcher/l2contractdeployer/docker.go, tools/hardhatdeployer/scripts/entrypoint.sh
RPC HTTP port has changed for the L2 nodes but it wasn't configurable for the L2 contract deployer script.
Unfortunately this needed wiring through in a few places so it can be set on the gateway at startup (but it looks less weird now, before it only accepted a WS port as config and assumed the HTTP port was static).
Add flag to the script that spins up the gateway for the deployer to allow http port to be set. Wire that through to the ten config that configures the deploy script.
=> L2 contract deploy: update node http port

.github/workflows/manual-deploy-testnet-l2.yml, .github/workflows/manual-deploy-testnet-validator.yml, .github/workflows/manual-upgrade-testnet-l2.yml, go/config/defaults/0-base-config.yaml, go/config/network.go, go/host/config/config.go, go/host/host.go, go/host/l1/publisher.go, go/node/cmd/cli.go, go/node/cmd/cli_flags.go, integration/simulation/network/socket.go
If blob gas prices spike and we fill up the blobpool we have to manually unblock the transactions which will be a pita for mainnet. Given consistency is favoured over latency for rollups we can set a very conservative wait time on the blob gas retry to ensure it gets published. 
* Add new `L1_ROLLUP_RETRY_INTERVAL` config param to set a longer retry so we don't fill the blobpool 
* Set to 4m for sepolia
=> Set blob TX retry wait to half the rollup interval

contracts/deployment_scripts/testnet/recoverfunds/001_recover_funds.ts
Funds are recovered on the new bridge contract, not the message bus.
=> Enable funds recovery for new bridge

go/enclave/components/batch_executor.go
To prevent extreme races that would corrupt the statedb
- introduced a mutex to execute batches serially ( and remove the other mutex that is now superseded)
- introduce an extra check to avoid reexecuting an already executed batch
=> Fix batch execution race

tools/edbconnect/main/edb-enclave.json
Main enclave now has debug=false so this needs to match it to be able to unseal the credentials correctly.
=> EDB connect: set enclave image debug=false

go/host/enclave/guardian.go
We were seeing 'Batch produced' messages twice from sequencer host for each batch and it would have sent out each batch twice on P2P broadcast because of this minor guardian bug.
Don't think either of those things were especially impacting but they caused confusion and the duplicate broadcast could potentially be a problem.
=> Host: only broadcast new batches from active seq enclave

tools/walletextension/frontend/Dockerfile, tools/walletextension/frontend/package-lock.json, tools/walletextension/frontend/package.json
Fixes the UI build failing due to dependency upgrade
Refactors docker container to use NPM over pnpm allowing use of lock-file.
=> Uses npm during Docker build and forces use of lock file.

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml, .github/workflows/manual-deploy-k8s-testnet-before-nodes.yml, .github/workflows/manual-deploy-testnet-l2.yml, testnet/launcher/l1contractdeployer/cmd/main.go
We were returning successful status code when L1 contract deploy failed to make sure the log artifacts always get captured.
This change allows logs to be captured even on failure so we can fail fast and not make people debug the issue when the nodes eventually fail to start up.
=> Deploy: always upload log artifacts even on failure

contracts/package.json, package-lock.json, package.json
Contract builds were failing because OpenZeppelin upgraded requiring a newer version of hardhat-verify and we weren't set up to support that.
Align verifier plugin version requirements with OZ's requirements.
=> Build: set compatible version for hh-verify

go/config/config.go
PKs getting into output and logs during deployment. Might not be publicly visible but unnecessary.
=> Deploy: censor PKs in config dump

go/host/storage/hostdb/batch.go, go/host/storage/hostdb/block.go, go/host/storage/hostdb/rollup.go, go/host/storage/hostdb/transaction.go, tools/enclavesigner/main/main.go, tools/walletextension/rpcapi/transaction_api.go
The PG driver expects the pagination limit and offset to be `int64`
- cast to int64
=> fix pagination on pg

go/config/config.go
Wasn't correctly deep copying part of the config tree that I modified when censoring for the pretty print so the PK was getting lost and L1 deploys were failing.
Deep copy the entire config structure, it only gets pretty printed once at startup so no worries about efficiency.
=> Config: fix pretty-print censoring bug

integration/tengateway/tengateway_test.go, tools/walletextension/httpapi/routes.go, tools/walletextension/rpcapi/transaction_api.go
To remove confusing behaviour.
`SendRawTransaction` already sends a signed transaction.
- remove sk logic from `SendRawTransaction`
=> remove tx signing with SK on `SendRawTransaction`

go/enclave/storage/enclavedb/config.go, go/enclave/storage/init/migration/db_migration.go
We try to insert the migration version value but that fails after the first time because key already exists, so we should so an update if present.
=> DB: fix migration config update to upsert

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml
Fix `line 7: syntax error near unexpected token `echo'` errors in k8s after deployment (L2 deployment) script runs.
=> Deploy: fix typo in k8s GH action script

go/enclave/core/event_types.go, go/enclave/evm/visibility_reader.go
An invalid visib config can crash the network
Ignore invalid configs
=> Fix visibility config crash

go/enclave/core/event_types.go, go/enclave/evm/visibility_reader.go
Port of https://github.com/ten-protocol/go-ten/pull/2615
=> Fix visibility config crash (#2615)

testnet/launcher/l1contractdeployer/docker.go
L1 deploys are taking wildly varying amounts of time in sepolia and it keeps tripping the timeout. Sometimes at the last step, sometimes quite early on.
Making this half hour should hopefully account for slowness while still failing eventually if it's going ridiculously slowly.
=> L1 deploys: bump timeout up to half hour to avoid sepolia deploy pain

testnet/launcher/directupgrade/docker.go, testnet/launcher/fundsrecovery/docker.go, testnet/launcher/l1challengeperiod/docker.go, testnet/launcher/l1contractdeployer/docker.go, testnet/launcher/l1grantsequencers/docker.go, testnet/launcher/l1upgrade/docker.go, testnet/launcher/l2contractdeployer/docker.go, testnet/launcher/multisigsetup/docker.go
20% gas multiplier should help prevent transactions from getting stuck in the mempool during Sepolia congestion by providing a buffer above the estimated gas price. This should significantly improve deployment reliability during high network activity periods.
=> L1 deploys: 1.2 mult on gas price

.github/workflows/runner-cleanup.yml
https://github.com/ten-protocol/ten-internal/issues/5534
New script which runs every 2 hours. It clears everything in the `/tmp/ten-persistence/` directory except the most recently added dir which should prevent any in-progress runs. 
=> Clean GH runner workflow

tools/walletextension/common/types.go, tools/walletextension/services/sk_manager.go, tools/walletextension/storage/database/common/db_types.go, tools/walletextension/storage/database/cosmosdb/cosmosdb.go, tools/walletextension/storage/database/sqlite/sqlite.go
In the future we will add expiration to the sessionKeys. It will be much easier to update it, if we already have createdAt field in the database.
Added CreatedAt to each session key.
=> add createdAt to the sessionKey

integration/tengateway/tengateway_test.go
* test log had `fail` in it which flags when searching for failed tests
=> Remove sacred "failed" from logs

integration/networktest/actions/setup_actions.go, integration/networktest/env/network_setup.go, integration/networktest/env/testnet.go
Now we're using a different chain ID per env we need to make sure they are configurable in network tests.
=> Network tests: configurable chain IDs per env

go/enclave/storage/init/edgelessdb/002_unique_ky.sql
To prevent duplicates from the statedb tables
- delete duplicates
- add unique index
=> add unique index on key

contracts/deployment_scripts/funding/layer1/001_fund_accounts.ts
Auto-bridging $2k dollars in a mainnet launch dry run is an unnecessary risk.
The last run against sepolia used 0.0003 eth and the gas price in mainnet is normally around 2x sepolia's price so 0.005 allows plenty of cushion in all environments. We can adjust if any problems but less risk to start low.
=> Deploy: change bridged deployment eth from 0.5 to 0.005

go/enclave/components/txpool.go
When enclave doesn't receive its first batches within 2mins of starting up it kills itself with a CRIT message. This can happen for a variety of reasons, especially when node is not starting immediately after L1 contract deployments and has some catching up to do.
I think we originally put this in because when we had some major bugs then the sim tests would hang instead of failing but we don't see them any more (and if we did then better to have timeouts in the test structure rather than in the production code).
The CRITs add noise and timing issues to the node startup and catch-up process.
Instead of CRIT after 2mins, we log how long the enclave has been waiting every 2 mins at ERROR level.
[PR …
=> Enclave: log error instead of crit when enclave waiting for initial batches

.github/workflows/runner-cleanup.yml, go/enclave/storage/init/edgelessdb/002_unique_ky.sql
Lots of queued jobs
* Switch cleanup from 2 hours to 30 mins
=> Increase GH runner cleanup frequency

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml, testnet/launcher/l1contractdeployer/git_config.go
Mainnet deploys fail to write and read the L1 contract addresses to the github config repo.
=> Deploy: fix github paths for mainnet config

go/host/storage/hostdb/rollup.go, go/host/storage/hostdb/rollup_test.go
https://github.com/ten-protocol/ten-internal/issues/5790
* Return 0 if no rows are found in the DB instead of error so FE can return N/A
=> Fix GetRollupListing

go/host/enclave/guardian.go, go/host/enclave/state.go, go/host/enclave/state_test.go
Fixes race condition where enclaveL2HeadHash was updated via polling (OnEnclaveStatus) while enclaveL2Head sequence number was updated via streaming (OnProcessedBatch), causing:  `Active sequencer's L2 head conflicts with the host's L2 head` log messages (~90/hour on Sepolia).
Changed OnProcessedBatch() to accept both sequence number and hash, updating both fields atomically to get rid of window where they're out of sync.
=> fix: atomically update L2 head sequence number and hash in StateTracker

go/enclave/components/batch_executor.go, go/enclave/storage/init/edgelessdb/003_statedb_val_nullable.sql, go/enclave/storage/init/sqlite/001_init.sql
to fix bugs
- Statedb.val is nullable
- remove  unused `executor.lastExecutedBatch`
=> Statedb.val is nullable, remove  unused `executor.lastExecutedBatch`
