ten-protocol/go-ten

- go/common/common.go
- go/common/l1_types.go
- go/obscuronode/enclave/db.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/node.go
- integration/ethereummock/node.go
- integration/simulation/transaction_manager.go
major changes:
1. Remove dependency on ethereum_mock.
2. Submit both the current L1 block and the parent on the RPC call to the l2 node.
> Fix race condition and remove ethereum_mock dependency

- integration/simulation/output_stats.go
- integration/simulation/simulation_test.go
Adds a new struct that process data from both the stats and the network and prints it.
Ideally we can create a ticket to decouple the many features of the Stats struct.
Right now the Stats collects data from the mock node, the obscuro node and the tests, while also serving as test argument and end-run-summary display.
> added output stats

- go/obscurocommon/block_resolver.go
- go/obscurocommon/common.go
- go/obscurocommon/encoding.go
- go/obscurocommon/l1_types.go
- go/obscurocommon/log.go
- go/obscurocommon/utils.go
- go/obscuronode/common/types_test.go
- go/obscuronode/enclave/crypto.go
- go/obscuronode/enclave/db.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/state.go
- go/obscuronode/enclave/types.go
- go/obscuronode/enclave/types_test.go
- go/obscuronode/enclave/utils.go
- go/obscuronode/header.go
- go/obscuronode/host/node.go
- go/obscuronode/nodecommon/encoding.go
- go/obscuronode/nodecommon/types.go
- integration/ethereummock/db.go
- integration/ethereummock/node.go
- integration/ethereummock/utils.go
- integration/simulation/cmd/main.go
- integration/simulation/l1_network.go
- integration/simulation/l2_network.go
- integration/simulation/output_stats.go
- integration/simulation/simulation.go
- integration/simulation/simulation_test.go
- integration/simulation/stats.go
- integration/simulation/transaction_manager.go
- integration/simulation/utils.go
* Instead of `common2`/`common3`/etc., uses `obscurocommon` and `nodecommon` (`common` is taken by geth's `common`)
* Deletes some unused common functions
* Moves host code into host package (was previously directly under `obscuronode` directory)
> Fixes imports of common packages. Cleans up unused common functions.

- go/obscuronode/host/host.go
- go/obscuronode/host/main/main.go
- go/obscuronode/host/p2p/p2p.go
- integration/simulation/l2_network.go
- integration/simulation/simulation.go
We were panicking too much on connection errors before. There were lots of spurious errors at the end of the simulation, when the listeners were being closed and failed connections are to be accepted.
> Pushes waiting for enclaves start-up to inside host. More graceful handling of connection errors.

- go/obscuronode/host/p2p/factory.go
- go/obscuronode/host/p2p/local_p2p.go
- go/obscuronode/host/p2p/p2p.go
- integration/simulation/cmd/main.go
- integration/simulation/l2_network.go
- integration/simulation/simulation.go
- integration/simulation/simulation_test.go
Easier to debug.
L2 Network now uses the P2P library instead of hardcoding the comunication.
> Implementing the P2P interface in chans

- integration/simulation/simulation_docker_test.go
Main merge tests are failing at a 0.4 effiency, bumping to 0.5 so it doesn't hide other major issues.
> bumping docker expected efficiency

- go/obscuronode/enclave/db.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/state.go
- go/obscuronode/enclave/storage.go
- go/obscuronode/enclave/utils.go
- integration/simulation/validate_chain.go
The main difference is that "Withdrawals" are now somewhere inside the mock EVM state, and are transformed into withdrawal instructions in a post processing step
> Refactor withdrawals in preparation for evm integration

- go/obscurocommon/utils.go
- integration/simulation/simulation_tester.go
- integration/simulation/transaction_injector.go
- integration/simulation/validate_chain.go
Fixes bug introduced by the previous PR where `atomic.LoadInt32(m.interruptRun) == 1` instead of `atomic.LoadInt32(m.interruptRun) == 0`.
Also changed from `avgblockduration` from uint to `time.duration` and added a RandomBetweenTime.
> fixing the injector

- tools/azuredeployer/main/azure_deployer.go
Tiny PR to log out the IP of the new VM in the azure_deployer script for convenience. (And so I can test out the github PR process!).
> Log out IP for the Azure VM in deploy script

- go/obscuronode/enclave/core/crypto.go
- go/obscuronode/enclave/core/l2tx.go
- go/obscuronode/enclave/core/rollup.go
- go/obscuronode/enclave/core/rollup_test.go
- go/obscuronode/enclave/core/test_utils.go
- go/obscuronode/enclave/db/db.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/db/types.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/enclave_test.go
- go/obscuronode/enclave/state.go
- go/obscuronode/enclave/utils.go
- integration/ethereummock/db.go
- integration/ethereummock/node.go
- integration/ethereummock/utils.go
- integration/simulation/transaction_injector.go
- integration/walletmock/wallet.go
- prerequisite for adding the geth StateDB
- this PR doesn't change any functionality
- moves all db stuff in a new package
- to avoid circular dependencies, it also move some core types to a "core" package
> isolate the db logic in own package

- go/obscuronode/enclave/db/db.go
- go/obscuronode/enclave/db/interfaces.go
- go/obscuronode/enclave/db/obscurostatedb.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/db/types.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/state.go
- go/obscuronode/enclave/utils.go
Introduce a per-block database with a similar lifecycle to the evm statedb.
Note: This work is just a step towards the final goal, so it's quite unpolished.
> Road to statedb - part 2

- go/ethclient/mgmtcontractlib/handler.go
- go/obscurocommon/utils.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/state.go
- go/obscuronode/host/host.go
- go/obscuronode/nodecommon/encoding.go
- integration/gethnetwork/geth_network.go
- integration/simulation/network/basicsocket.go
- integration/simulation/network/dockerenclave.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network.go
- integration/simulation/network/oneAzureEnclave.go
- integration/simulation/params/params.go
- integration/simulation/simulation.go
- integration/simulation/simulation_docker_test.go
- integration/simulation/simulation_geth_in_mem_test.go
- integration/simulation/simulation_in_mem_test.go
- integration/simulation/simulation_socket_test.go
- integration/simulation/simulation_tester.go
This PR is a result of debugging the very flaky geth test:
- made the logging consistent and easy to follow.
- slightly refactored the geth test according to the general pattern, and fix the duration 
- tweak the parameters of geth, as it turns out it takes a few seconds to publish a transaction
> Improve logging, fix geth test

- go/obscuronode/enclave/enclave.go
Prerequisite for the state db work, because there seems to be a bug in the speculative execution logic
> Add flag to toggle speculative execution

- tools/walletextension/wallet_extension_test.go
Previously, there was a race condition whereby the wallet extension tests could fire off a request before the wallet extension had opened its port. We add a retry to prevent this causing a test failure.
> Prevents test failure if wallet extension is connected too soon.

- go/obscuronode/enclave/server.go
- go/obscuronode/host/host.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/inmemory.go
- integration/simulation/simulation_tester.go
Some goroutines are leaking from simulations and are still running when the next simulation starts. This seems to be causing some issues and it would be good to reduce them over time/be able to rule it out as a contributor to flakey builds.
This change just adds logging at the beginning and end of sims to output number of running goroutines and does some refactors that might help (or at least shouldn't hurt). My very unscientific testing suggests it's knocked out about 50 leaked goroutines by the time the 3 sims have finished.
The changes mostly just add defers to try to guarantee cleanups will happen in the case of unexpected errors (reduce red herrings at least, even if the tests fail anyway). And I noticed from the log dump that about 15-20 goroutines were from the monitorBlocks() in …
> Monitor goroutine leaks

- integration/gethnetwork/geth_network.go
- integration/simulation/network/geth_network.go
This just adds a crude check of all the ports that the geth binaries will be running with are available before the simulation network is started and fails quickly if not.
I don't know if this is a big problem or if this is the best way to deal with it but it's bitten me multiple times locally and it would be nice to rule it out on the build servers.
I managed to get myself into the bad state somehow locally, can see the processes lurking here while no test is running:
And on this branch the test fails immediately with:
Then I resolve it with something like:
And the test starts running fully again.
> Fail fast in geth nodes test when ports are not available

- integration/simulation/utils.go
Quite often see nil pointer when failing to get a current blockhead because a node has been knocked out for some reason, sticking an error on it so it can be more recognisable.
> More meaningful error for the missing blockhead nil pointer in sims

- go/obscuronode/config/host_config.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/server.go
- go/obscuronode/host/host.go
- integration/simulation/simulation_full_network_test.go
- integration/simulation/simulation_geth_in_mem_test.go
- integration/simulation/simulation_tester.go
Joel found examples of failures to decrypt secrets and the smoking gun was that the node in question had generated its private key more than once.
This PR moves the generateKeyPair() call to be done once at initialization rather than checking the key has been generated when the IsReady() rpc request is made.
> ensure generateKeyPair() not called multiple times

- go/obscuronode/enclave/state.go
- go/obscuronode/host/host.go
- go/obscuronode/host/hostdb.go
- integration/ethereummock/mock_l1_network.go
- fix a flakyness where there was no root trie available when asking for the head 
- check that the rollup wasn't submitted already
> Fix duplicate rollups flaky tests

- go/obscuronode/config/enclave_config.go
- go/obscuronode/enclave/db/interfaces.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/enclaverunner/cli.go
- go/obscuronode/enclave/enclaverunner/cli_flags.go
- go/obscuronode/enclave/enclaverunner/test.toml
- integration/simulation/network/azureenclave.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/socket.go
As a pre-cursor to the edgeless DB work we need a way to tell nodes what DB setup to use. I think there are 3 situations worth using in testing:
- in-memory (quick and clean, default for test scenarios)
- persistent, SQL (integration tests to verify the persistence and the SQL implementation of ethdb key-value store work)
- persistent in-enclave, Edgeless DB (dev testnet, testnet, prod)
> Add config to turn-on persistent enclave database

- integration/simulation/validate_chain.go
Why is this needed
- It's counter productive to panic as it does not allow to see how the other nodes are handling the rollup validation
> Don't panic on missing rollups when in validation

- go/obscuronode/host/host.go
- Connected with https://github.com/obscuronet/obscuro-internal/issues/483
- Streams blocks instead of loading into a slice
- Added `bootstrappingComplete` to signal when the node is bootstrapping / processing blocks
- Added a `bootstrapNode` method to stream blocks into the enclave
- L1 blocks are now monitored from the start, but ignored until the node is in processing mode
- Host file
> stream blocks at bootstrap

- go.mod
- go.sum
- go/obscuronode/enclave/db/interfaces.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/enclaverunner/cli_test.go
- go/obscuronode/enclave/sql/README.md
- go/obscuronode/enclave/sql/batch.go
- go/obscuronode/enclave/sql/iter.go
- go/obscuronode/enclave/sql/sql.go
- go/obscuronode/enclave/sql/sql_test.go
- go/obscuronode/enclave/sql/sqlite.go
- integration/simulation/network/socket.go
- integration/simulation/simulation.go
- As a pre-requisite for using Edgeless DB for the enclave persistence we need a SQL implementation of the ethdb.Database interfaces
- To be able to test that without an SGX-powered enclave we need to be able to start enclave with a basic SQL database
- SQL implementation of the parts of the ethdb.Database interfaces that we're using
- Add a dummy sqlite database that spins up with non-secure, persistent enclave servers
- the dummy sqlite database setup and its use in the full-network integration test
- the sql implementation of the interfaces - a lot of the code in there is copy-paste from the geth in-mem db and there's some basic test coverage that we can extend if we find gaps
> SQL implementation for enclave persistence

- integration/simulation/network/azureenclave.go
- integration/simulation/simulation_azure_enclaves_test.go
- tools/azuredeployer/enclavedeployer/README.md
To test the enclave inside an sgx enabled machine not in simulation mode
- The azure enclave test was changed to rely on a geth network, and to bring it more in line with the docker test.
- It also now outputs the docker commands that have to be run manually because they rely on the addresses of the deployed contracts. Also updated the readme with this new info
- This is a functional PR. A further refactoring pr is required to extract the common functionality between the geth tests into some utilities.
- the azure test
> fix azure enclave test

- dockerfiles/plain_go_enclave_local.Dockerfile
- We might want to debug the enclave without running it in ego, and this is a handy docker file to help with that.
- A docker file that uses a plain go image that is able to run the enclave was added.
- functional PR
N/A
> add plain go runner enclave docker file for testing

- .github/workflows/build-pr.yml
- .github/workflows/manual-build-test.yml
We still occasionally see failures where geth nodes fail to start because the test ports are still occupied.
- replace the kill commands from before with a port-range based command that covers the range 30000-39999 where we run our tests
- happy the command does what it's supposed to do?
- happy it can replace the commands that were there before or should we keep some/all of them?
I ran a build and ran the commands to convince myself they worked as intended. With no build running I saw no output for `lsof -ti:30000-39999`.
With a build running I saw:
Then I ran `lsof -ti:30000-39999|kill` twice and the second time it output saying there was no input to the kill command (they were dead)
> During cleanup in CI builds: kill processes on ports 30000-39999

- go/obscuronode/host/hostrunner/host_runner.go
- go/obscuronode/wallet/wallet.go
- integration/datagenerator/wallet.go
- integration/simulation/simulation_tester.go
- integration/simulation/transaction_injector.go
- tools/azuredeployer/networkdeployer/run.sh
- tools/networkmanager/deploy_contract.go
- tools/networkmanager/inject_txs.go
As part of https://github.com/obscuronet/obscuro-internal/issues/448, we need the ability to injects txs into an Obscuro devnet.
Functional.
* Updates `run.sh` script that runs devnet to give nodes P2P addresses (required for injecting and broadcasting txs)
* Some clean-up in transaction_injector.go:
* Timeout if hangs for too long trying to get nonce to inject transaction
* Handles edge cases when trying to select random client/wallet when there is only one
Key changes are in the `run.sh` script.
> Allows injection of transactions into devnet Obscuro network

- go/obscuronode/enclave/db/interfaces.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/rawdb/schema.go
- go/obscuronode/enclave/utils.go
- to remove the last vestige of the old in memory db 
- functional PR
- remove the tempDb, and the functions that were using it, since the transactions were already in the rollup
- N/A
> Remove unusued tempdb

- integration/simulation/network/azureenclave.go
- integration/simulation/network/docker_utils.go
- integration/simulation/network/dockerenclave.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/geth_utils.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
- integration/simulation/simulation.go
- integration/simulation/transaction_injector.go
- integration/simulation/utils.go
- integration/simulation/validate_chain.go
- tools/networkmanager/inject_txs.go
- tools/obscuroscan/obscuroscan.go
The integration tests became quite hard to follow. 
There is a general pattern for all tests except the pure in-memory test:
1. Start a geth network , deploy the contracts, and return the addresses
2. Start up obscuro components
a) Enclaves. Which can be started inside the obscuro node, standalone process, inside docker or manually in azure
b) The Obscuro node which can be in memory or standalone and it has to know the address of the enclave.
The stopping order should be:
- first stop the obscuro host. Because this glues everything together, and needs everything up and running until the very end.
- then stop the enclaves and the ethereum network
This is mostly a refactoring PR. The only thing that changed functionally is the sequence of stopping resources in TearDown. 
- the geth setup …
> refactor integration tests

- go/obscuronode/host/host.go
- to prevent leaving ports open in case an obscuro host is getting stuck
- functional PR
- kill the rpc before writing on the exit channel
- N/A
> Shut down the rpc before the main loop on the host

- integration/simulation/transaction_injector.go
The timeout kept getting hit. It's not clear to me whether this is a genuine timeout or a failure. But increasing it should reduce flaky failures.
Also panics if remote nonce exceeds local nonce, which should never happen.
- Functional
N/A
> Bumps timeout for retrieving nonce.

- integration/simulation/transaction_injector.go
- integration/simulation/validate_chain.go
Previously, the sim could deadlock after one or two transactions, and still be considered a success. We want to catch that edge-case.
- Functional
N/A
> Increases threshold of txs to consider simulation failed

- dockerfiles/README.md
- tools/azuredeployer/networkdeployer/run.sh
We should default to the most "production-like" mode, which includes adding the `willAttest` flag outside of simulation mode.
- Functional
- Adds flag to run script and Docker readme
N/A
> Adds willAttest flag when running enclave outside of simulation mode.

- tools/azuredeployer/enclavedeployer/README.md
- tools/azuredeployer/enclavedeployer/vm-template.json
- when you run the enclave azure deployer at the moment it fails to get the IP and so fails to run the script that sets up docker and docker image
- tweak enclave deploy config to match the network deploy config so the script they both use works for enclave deploy
- also updated an out of date part of the readme
- the config change
Failure before the change:
Success after the change:
> fix enclave deploy IP retrieval

- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
Simulation socket nodes don't currently expose an RPC websocket port. This will block the integration testing of the wallet extension.
Functional.
Enables websocket ports for socket simulation nodes.
> Enables websockets for simulation nodes.

- go/obscuronode/host/host.go
- go/obscuronode/host/hostdb.go
The Obscuro host service needs a database to keep track of the interactions with the outside world and the enclave.
Until now, this db was implemented as a series of maps. 
The problem with that is that on a long running process it will run out of memory, and it can't be persisted.
- functional PR 
- replace the maps with the geth KeyValueStore object for which there are both memory and leveldb implementations available
- Note: in a subsequent work, the type of db that is created will be driven by the configuration
- the hostdb
> Add KV store support to the host db

- go/obscuronode/enclave/enclave.go
- go/obscuronode/host/client_api_eth.go
- go/obscuronode/host/client_api_obscuro.go
- go/obscuronode/host/enclave_client.go
- go/obscuronode/host/in_mem_obscuro_client.go
- go/obscuronode/nodecommon/enclave.go
- go/obscuronode/nodecommon/types.go
- go/obscuronode/obscuroclient/obscuro_client.go
- integration/simulation/utils.go
Allows calls to be made against Obscuro nodes (via the wallet extension) without app-side changes.
- Refactoring?
- Replaces `ObscuroAPI.ExecContract` with `EthereumAPI.Call`, the standard Eth API
- Changes GetBalance to use `EncryptedResponse` type
> Uses EncryptedResponse for GetBalance. Shifts ExecContract to Eth standard.

- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/viewingkeymanager/viewing_key_manager.go
- integration/simulation/wallet_extension_test.go
This is a refactor. Previously, the logic for viewing keys was mixed in with the enclave. This logic will extend in the future, so best to split it out now.
Refactoring.
> Splits viewing key management into dedicated type.

- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/sql/sqlite.go
- Joel spotted odd test failures that are likely caused by sqlite DB files being overwritten by parallel tests
- In future we will need to be able to pass in a path to the db so that we can test persistence and recovery for an enclave
- use random path instead of the node ID
- add possibility for configurable DB and make sure we wouldn't overwrite an existing DB
- the creation of a temp DB in sqlite.go
> Fix sqlite file clashes in tests

- go/obscuronode/enclave/enclave.go
- go/obscuronode/nodecommon/enclave.go
- tools/walletextension/wallet_extension.go
To prevent MitM attacks, viewing keys should be encrypted before they are sent to the enclave.
Functional.
- Encrypts the viewing key on the wallet side
- Decrypts the viewing key on the enclave side
> Renables encryption of viewing keys on wallet extension side.

- go/ethclient/erc20contractlib/obscuro_ERC20_contract_ABI.go
- go/obscuronode/enclave/core/crypto.go
- go/obscuronode/enclave/core/rollup.go
- go/obscuronode/enclave/core/types.go
- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/evm/evm_facade.go
- go/obscuronode/enclave/mempool/interface.go
- go/obscuronode/enclave/mempool/manager.go
- go/obscuronode/enclave/state.go
- go/obscuronode/enclave/utils.go
- integration/simulation/transaction_injector.go
- integration/simulation/transaction_injector_counter.go
- tools/obscuroscan/obscuroscan_test.go
To align with geth, and be able to call geth functions, we have to use pointers to transactions.
- refactoring PR 
- use pointers
- core/types.go - L2Txs
> Use pointers to transactions

- integration/walletextension/wallet_extension_test.go
The wallet extension integration tests were in the same folder as the sim tests due to a DB file overwriting issue. This is now fixed.
Refactoring.
- Moved file.
> Moves wallet extension tests to own package.

- go/obscuronode/enclave/enclave.go
- tools/walletextension/wallet_extension.go
Refactors various RPC encryption methods to make them simpler to follow.
Refactoring.
> Extracts the logic to parse Call request params, and to encrypt request params.

- go/obscuronode/enclave/enclave.go
- go/obscuronode/enclave/rpcencryptionmanager/rpc_encryption_manager.go
- integration/simulation/wallet_extension_test.go
Encapsulates the decryption of sensitive RPC requests to reduce the amount of logic in enclave.go.
Refactoring.
> Extend viewing key manager to handle decryption of sensitive RPC requests

- go/obscuronode/enclave/core/rollup.go
- go/obscuronode/enclave/db/interfaces.go
- go/obscuronode/enclave/db/storage.go
- go/obscuronode/enclave/rawdb/README.md
- go/obscuronode/enclave/rawdb/accessors_chain.go
- go/obscuronode/enclave/rawdb/accessors_indexes.go
- go/obscuronode/enclave/rawdb/accessors_receipts.go
- go/obscuronode/enclave/rawdb/schema.go
- go/obscuronode/enclave/state.go
We need to store tx receipts and other metadata, so that we can expose them via RPC to be used by wallets (in a subsequent PR).
In a previous PR, the Merkle root of the receipts was added to the rollup header.
- functional PR 
- a bunch of accessor methods were copy-pasted from geth and slightly modified
- pass in the "receipts" to the storage function that saves the rollup, and store more metadata
- storage - "SaveNewHead"
> store receipts and more rollup metadata to the db

- go/obscuronode/enclave/core/transaction_blob_crypto.go
- go/obscuronode/enclave/enclave.go
- tools/obscuroscan/obscuroscan.go
- tools/obscuroscan/obscuroscan_test.go
- tools/obscuroscan/static/block_decoder.html
- tools/obscuroscan/static/block_decoder.js
- tools/obscuroscan/static/index.html
https://github.com/obscuronet/obscuro-internal/issues/508
The existing Obscuroscan design assumed that the entire rollup would be encrypted, rather than just the transactions.
Obscuroscan now decrypts encrypted tx blobs instead. These can be grabbed via the monitor page.
Functional.
- Updated Obscuroscan so that encrypted transaction blobs could be decrypted
- Removed the fake UI box where the enclave private key was supposed to be pasted, as not needed for now
> Obscuroscan now allows decrypting of transaction blobs grabbed via the monitor.

- integration/simulation/network/geth_utils.go
An NPE can occur if the contract fails to deploy, as there is never a receipt to check the status of.
Functional.
- Avoids NPE
> Avoids NPE in case contract fails to deploy.

- .github/workflows/manual-deploy-l1network.yml
- [Ticket](https://github.com/obscuronet/obscuro-internal/issues/543)
- Manually deploys an l1 network to the testnet machines in azure ( First part )
- This change will add a manual action that allows to trigger the functionality
- Adds a docker file that can run a geth network
- Adds a Github manual action that can start a network
- Pushes the image to dockerhub 
- Functional
- Github action files
- Dockerfile on the testnet folder ( the folder might be removed if it has few files)
> Testnet: Manual Github Action to deploy a geth network ( Second Part )

- .github/workflows/manual-deploy-l1network.yml
- integration/gethnetwork/geth_network.go
- [Ticket](https://github.com/obscuronet/obscuro-internal/issues/543)
- Manually deploys an l1 network to the testnet machines in azure ( First part )
- This change will add a manual action that allows to trigger the functionality
- Adds a docker file that can run a geth network
- Adds a Github manual action that can start a network
- Pushes the image to azure container registry 
- Functional
- Github action files
- Dockerfile on the testnet folder ( the folder might be removed if it has few files)
> Testnet: Manual Github Action to deploy a geth network ( Third Part )

- integration/walletextension/wallet_extension_test.go
It makes the test faster to run, and gives the sim less space for mistakes.
Functional.
- Creates a single node network in the wallet tests, rather than a two-node network
> Drops down to a single node in the wallet extension tests. Second node is not needed.

- dockerfiles/README.md
- dockerfiles/enclave.Dockerfile
- dockerfiles/enclave_local_build.Dockerfile
- dockerfiles/plain_go_enclave_local.Dockerfile
- go/obscuronode/enclave/main/enclave.json
- The enclave needs to be able to persist certificates for connection to Edgeless DB
- Anything the enclave persists should be sealed using its built-in private keys
- We may wish to persist other things here going forwards to make enclave restart smoother (e.g. the sealed and encrypted secret)
- change dockerfiles to create directories `/home/obscuro/go-obscuro` for the code and `/home/obscuro/data` for the data
- change enclave.json to add a file mount, make `/home/obscuro/data` available inside the enclave as `/data` (as per https://docs.edgeless.systems/ego/#/reference/config?id=mounts)
- The config change
- The dockerfile changes:
-- I have tested the enclave_local_build on the SGX server as part of my edb branch testing
-- I'll watch the build for this PR closely, it will build and …
> Setup /data folder for enclave secure persistence

- tools/azuredeployer/networkdeployer/run.sh
- tools/obscuroscan/main/cli.go
Network deployer script could not start enclaves correctly.
Obscuroscan used `localhost` in defaults, which could break things.
Functional.
- Fixed script
- Fixed use of localhost
> Correct enclave flags. Use 127.0.0.1 instead of localhost.

- integration/simulation/utils.go
- integration/simulation/validate_chain.go
- tools/networkmanager/README.md
- tools/networkmanager/inject_txs.go
Currently, the smoketest only checks L1 transactions. It should check L2 transactions as well.
Functional.
- Checks success of L2 transactions
> Smoketest checks L2 transactions

- go/common/log/logutil/README.md
- go/common/log/logutil/logutil.go
- integration/noderunner/noderunner_test.go
- integration/simulation/simulation_azure_enclaves_test.go
- integration/simulation/simulation_docker_test.go
- integration/simulation/simulation_full_network_test.go
- integration/simulation/simulation_geth_in_mem_test.go
- integration/simulation/simulation_in_mem_test.go
- integration/simulation/utils.go
- minor refactor because test log setup is duplicated and I was about to duplicate it again (for wallet extension)
- refactor test logging to a logutil
- happy with naming, generic-ness etc? I went for logutil rather than log because it'll be annoying to have SetupTestLog start showing up as an option when you're looking for log.Info
> Move test log setup to util for reuse

- tools/obscuroscan/obscuroscan.go
- tools/walletextension/README.md
- tools/walletextension/wallet_extension.go
Serving of static files was previously broken. The Go binary would simply point to the location of the static files on disk, outside the binary. This worked fine when compiling the binary yourself, since it pointed to your files. But if the binary was moved to another machine, the files couldn't be found.
Functional.
- Embeds static files
- Adds `.exe` to Windows binary in readme instructions
> Fixes serving of static files.

- integration/walletextension/wallet_extension_test.go
In the wallet extension tests, if the request to add a viewing key returns successfully but with a non-200 error code, this is treated as a success. We should fail the test instead. Otherwise, we get confusing errors later on.
Functional.
- Catch broader set of failures to add viewing key
> Checks whether HTTP request to add viewing key failed.

- .github/workflows/build-pr.yml
- integration/walletextension/wallet_extension_test.go
- hard to debug wallet ext tests when the nodes in the network are a black box
- add log file per test
- add the config for github to include those files in the downloadable bundle
- my main concern is that this might be a bit heavy handed, it spams out a lot of these files. But we can always rethink it once things have settled down I suppose...
> Add logging for wallet ext simulations

- go/enclave/rollupchain/rollup_chain.go
- go/host/client_api_eth.go
- go/host/client_api_net.go
- go/host/rpc_server.go
Fixes various issues related to contract deployment via Remix.
Functional.
- Introduces additional RPC methods expected by Remix/MetaMask
- Fixes bug whereby we returned wrong network ID
> Adds dummies for eth RPC methods required by Remix. Fixes network version

- go/config/enclave_config.go
- testnet/docker-compose.yml
- we don't want to use in-memory db for long running nodes (memory leak)
- set useInMemory flag to calse
- add todos to make persistence and attestation the default
> Set useInMemory=false on enclave docker-compose wiring

- go/config/enclave_config.go
- go/enclave/db/db.go
- go/enclave/enclaverunner/cli.go
- go/enclave/enclaverunner/cli_flags.go
- testnet/docker-compose.yml
- ego doesn't let you write to arbitrary file path without mounting them. Out testnet is using ego on docker
- there's a /data folder available but we didn't have the ability to configure where the sqlite file goes
- Wire through a sqliteDBPath config flag
- add /data/sqlite.db as the default file for the testnet
Comparing the sqliteDBPath flag to the edgelessDBPath flag etc. to make sure it follows the same usage pattern as it is analogous
> Add config for sqlite db path

- go/enclave/db/storage.go
Previously, the incorrect signer type was used to get the sender for tx receipts, preventing tx receipts from being retrieved.
Functional.
- Switches to correct signer type
> Fixes signer for tx receipts.

- go/ethadapter/erc20contractlib/obscuro_ERC20_contract_ABI.go
to fix a bug:
```anic: runtime error: slice bounds out of range [:4] with capacity 0
goroutine 368 [running]:
github.com/obscuronet/obscuro-playground/go/ethadapter/erc20contractlib.DecodeTransferTx(0x7f9d14101320)
/home/obscuro/go-obscuro/go/ethadapter/erc20contractlib/obscuro_ERC20_contract_ABI.go:34 +0x365
github.com/obscuronet/obscuro-playground/go/enclave/bridge.(*Bridge).RollupPostProcessingWithdrawals(0x7f9d1416e380, 0x7f9d14704690, 0x7f9d14183380, 0xcacc86480d1e346f?)
/home/obscuro/go-obscuro/go/enclave/bridge/bridge.go:260 +0xdd
github.com/obscuronet/obscuro-playground/go/enclave/rollupchain.(*RollupChain).produceRollup(0x7f9d143e2a20, 0x7f9d1459cb40?, 0x7f9d141f12c0)
/home/obscuro/go-obscuro/go/enclave/rollupchain/rollup_chain.go:539 +0xa85 …
```
> fix tx decoding bug

- go/enclave/db/storage.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/main/main.go
- tools/walletextension/wallet_extension.go
The `from` field in `eth_call` requests is optional. If it's missing, we have nothing to encrypt the response with, and we cannot send it in plaintext. So we set the `from` field to the viewing key address if it's missing.
Functional.
- Set `from` field in `eth_call` requests iff missing
> Set from field if missing in eth_call requests

- go/host/client_api_eth.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/wallet_extension.go
Correctly formats the returned JSON for `eth_getTransactionReceipt`, so that MetaMask can detect a successful transaction.
Also adds the `eth_getBlockByHash` method that MetaMask needs.
Functional.
- As described above.
> Further fixes to enable MetaMask and Remix

- go/enclave/core/rollup.go
- go/enclave/rollupchain/rollup_chain.go
The logic to process the transactions in a rollup was implemented slightly different in the rollup checking function and in the rollup producing function.
This might have been the cause of the elusive bug where the calculated state of a rollup doesn't match the root hash from the header.
Refactoring.
Make the `process` function a bit more generic and use it in both the checkRollup and produceRollup
- produceRollup
> Fix state calculation logic

- go/enclave/enclave.go
Previously, if there was no head rollup, `GetRollupByHeight` would panic.
Refactoring.
- Avoids panic
> Avoids panic if there is no head rollup.

- integration/simulation/network/socket.go
The todo being removed is incorrect. There is no need to stop the enclaves, since they are automatically pulled down by the hosts when they are shut down.
> Removes incorrect todo.

- docs/testnet/deploying-a-smart-contract.md
It is unclear in the docs why the viewing key must be regenerated upon restart.
Functional.
- Clarifies docs
> Explains why viewing key must be regenerated on restart.

- .github/workflows/manual-deploy-l1network.yml
- integration/gethnetwork/geth_network.go
- integration/gethnetwork/main/cli.go
- integration/gethnetwork/main/main.go
- Keeps the testnet up for longer
- fixed geth arguments
- changed the deployment from 1 blk/sec to 1 blk/min
> Fixing geth config + slowing down block production

- go/common/l1_types.go
- go/host/enclave_client.go
- go/host/host.go
- integration/ethereummock/node.go
Encoding or decoding a block panics if there's an issue. This isn't always the correct behaviour. Often (e.g. when receiving blocks via RPC), it is better to handle the error (e.g. to prevent bad blocks from being sent over and crashing the node).
Functional.
- `EncodeBlock` now returns an error instead of panicking
- `DecodeBlock` now returns an error instead of panicking
> Surfaces errors during encoding and decoding of blocks.

- go/common/logging.go
- go/enclave/enclave.go
- go/enclave/rollupchain/rollup_chain.go
- go/host/enclave_client.go
- go/host/host.go
We have introduced `LogWithID` and similar methods to automate prefixing a node's ID to a log message. But we used it inconsistently, in part because we didn't have similar methods for `log.Panic` and `log.Trace`.
Functional.
- Introduces `TraceWithID` and `LogWithID` everywhere
- Uses the logging methods everywhere they apply
- Creates a `nodeShortID` field on the enclave client to avoid endless recalculation of the node's short ID
> Use `LogWithID` and similar everywhere

- go/common/utils.go
- integration/common/utils.go
- integration/ethereummock/mock_l1_network.go
- integration/simulation/network/network_utils.go
- integration/simulation/p2p/mock_l2_network.go
- integration/simulation/transaction_injector.go
- integration/simulation/utils.go
Some test utilities ended up in the `go/common/` package, where they were at risk of being used by non-test code. In this particular instance, the issue was that the functions panicked, but in general we should try to segregate our test vs production code.
Functional.
- Creates new `common` package inside `integration`
- Moves certain test utils to that package
> Moves test utils out of common, and into test-specific common.

- integration/simulation/transaction_injector.go
We always use the first L2 client for transfers in the simulation. This might hide issues.
Functional.
- Uses random L2 client for transfers in the simulation
> Use random L2 client for transfers in sim, not always the first

- go/enclave/crypto/crypto.go
- go/enclave/crypto/transaction_blob_crypto.go
- go/enclave/enclave.go
- go/enclave/rpc_server.go
- tools/obscuroscan/obscuroscan_test.go
The `TransactionBlobCrypto` class exposes `Encrypt` and `Decrypt` methods, but these should be encapsulated and not used directly.
Functional.
- Removes `Encrypt` and `Decrypt` from `TransactionBlobCrypto` interface
- Fixes tests to work around the encapsulation of these methods
> Shrink TransactionBlobCrypto interface to not expose encrypt and decrypt methods.

- tools/walletextension/static/javascript.js
MetaMask's `eth_requestAccounts` method returns an array. I previously assumed that the user should be able to select any of these accounts, and left a todo to that effect. But actually, upon inspecting the APIs docs, it's clear that this array is always only contains one element.
Functional.
- Removes todo
- Adds clarifying comment
> Removes a todo that incorrectly assumes that multiple MetaMask accounts can be returned.

- go/enclave/enclave.go
- go/enclave/rpcencryptionmanager/rpc_encryption_manager.go
Addresses a todo in the codebase. Viewing keys were previously decrypted by the enclave before being passed to the `RPCEncryptionManager`, but that wasn't a good separation of duties.
Functional.
- Encapsulates decryption of viewing key
> Encapsulates decryption of the viewing key.

- docs/testnet/essentials.md
- docs/testnet/wallet-extension.md
- go/enclave/rollupchain/rollup_chain.go
- go/enclave/rpcencryptionmanager/rpc_encryption_manager.go
- tools/walletextension/main/cli.go
- When the enclave fails to parse a JSON request, it doesn't provide sufficient information to diagnose it
- The wallet extension should default to the testnet nodes for ease of use, but doesn't
- There's a typo in the docs ("PRC" instead of "RPC")
Functional.
- Fixes the above
> Docs fix. Defaults to testnet node addresses. Better error message on failed request parse.

- testnet/docker-compose.non-sgx.yml
- testnet/docker-compose.yml
Testnet should be using viewing keys. Otherwise, sensitive messages will not be encrypted.
Functional.
- Enable viewing keys for testnet
> Enable viewing keys for testnet.

- .golangci.yml
- go/common/logging.go
- go/enclave/evm/evm_facade.go
- go/enclave/rollupchain/rollup_chain.go
- integration/simulation/transaction_injector.go
Transactions with too little gas kill the enclave. 
Logging needs to also be a bit better to help diagnose issues
1. Fix a bug where an account was credited even though the transaction that triggered that crediting would fail. 
2. Improve some log messages, and standardise them
3. Previously all transactions that errored were excluded which is not the right behaviour. Now only transactions that fail because the nonce was too high are excluded.
4. Disable the "ifshort" lint check because it's broken.
- The evm_facade
> Fix tx execution bug, and improve logging

- .gitignore
- tools/walletextension/main/cli.go
- tools/walletextension/wallet_extension.go
The wallet extension is too loud by default, logging ~four lines for every request (there can be 1+ requests per second).
Ticket: https://github.com/obscuronet/obscuro-internal/issues/633.
Functional.
- Removes unnecessary logging of request encryption/response decryption
- Pushes logging to optional log file, with the exception of errors, which are always printed as well
> Pushes wallet extension noise to logs.

- .golangci.yml
- go/enclave/evm/evm_facade.go
- Reenables the `ifshort` linter 
- Adds a comment that ignores ALL linters in the problem line
> enables ifshort in the linter

- go/enclave/rpcencryptionmanager/rpc_encryption_manager.go
- integration/walletextension/wallet_extension_test.go
The wallet extension tests had two bugs that were cancelling each other out:
- We were asserting that the result of an ERC20 getBalance call should be empty bytes, when it should be nil bytes
- We were not waiting for the ERC20 contract to be deployed, so we were calling a non-existent contract and getting empty bytes
Functional.
- Fixes the two bugs above
> Fix wallet extension tests

- go/enclave/rpcencryptionmanager/rpc_encryption_manager.go
When the EVM returns nothing in response to an `eth_call`, we need to encrypt _something_ to return (we cannot encrypt empty bytes). So we encrypt a placeholder. However, the old placeholder made Remix unhappy. We should replace it with a placeholder in a form Remix can understand.
Functional.
- Switches to placeholder Remix can handle
> Management placeholder for ERC20

- testnet/start-obscuro-node.sh
- Easy to forget to setup at least one node as the genesis
- Leads to confusing errors
- Made is_genesis=true as part of the default sugestion
> Setting the sugested node execution as is_genesis = true

- testnet/docker-compose.non-sgx.yml
- testnet/docker-compose.yml
- Enables viewing keys as a default in testnet
> enabling viewing keys

- go.mod
- go/enclave/enclave.go
- go/enclave/rpcencryptionmanager/rpc_encryption_manager.go
- go/host/in_mem_obscuro_client.go
- go/rpcclientlib/README.md
- go/rpcclientlib/obscuro_client.go
- integration/simulation/transaction_injector.go
- integration/simulation/utils.go
- integration/walletextension/wallet_extension_test.go
- tools/obscuroscan/main/cli.go
- tools/walletextension/main/main.go
- tools/walletextension/static/javascript.js
- tools/walletextension/wallet_extension.go
- We want to re-use the viewing key encryption/decryption for tests and scripts
- Communicating to the obscuro node is done a bit differently in many places, adding the enc/dec into the rpc client should give us a single codepath to worry about
- move the `isSensitive(method)` function and the encrypt/decrypt if necessary out from wallet extensions to be part of rpc client lib
- change wallet extension to use rpc client lib
- fix simulation tests (transaction injector) to use rpc client in a way that is consistent
- `obscuro_client.go` in the rpcclientlib, the wallet_extension changes and the transaction injector changes
- there will be follow-ups to:
* make viewing key enc/dec mandatory (means updating lots of test code and removing the viewing key disabled flag/codepaths from enclave …
> Add viewing key encryption/decryption to rpc client lib

- tools/walletextension/static/javascript.js
testing is difficult since MM has to be reinstalled every time
by using the latest created account, we can avoid this problem
-functional
- use the last account in the array
> Use last account

- go/enclave/core/utils.go
- go/enclave/rollupchain/rollup_chain.go
- go/ethadapter/erc20contractlib/obscuro_ERC20_contract_ABI.go
investigate when testnet crashes
- functional PR
- always print the hex of a tx to be able to trace it from metamask
- dump the entire state every time a rollup is created to allow a more accurate diff when it crashes
> Improve logging

- go/ethadapter/geth_rpc_client.go
- go/ethadapter/interface.go
- go/host/hostrunner/host_runner.go
- go/host/interfaces.go
- integration/ethereummock/mock_l1_network.go
- integration/ethereummock/node.go
- integration/gethnetwork/geth_network_test.go
- integration/simulation/network/geth_utils.go
- integration/simulation/stats/stats.go
- integration/simulation/validate_chain.go
- integration/smartcontract/smartcontracts_test.go
- tools/contractdeployer/contract_deployer.go
- tools/networkmanager/deploy_contract.go
- tools/networkmanager/inject_txs.go
- There was a todo to be addressed re: the Geth client having two constructors, when one would do
- The Geth client's ID field was used confusingly. Sometimes it was not set, sometimes it was set to a random ID, sometimes it was set to the L2 node ID
Refactoring.
- Removes secondary constructor for Geth client
- Forces passing of L2 ID when constructing Geth client
- Clarifies role of L2 ID in Geth client
- Encapsulates ID field in ethereummock.Node
- Removes unused param in `Stats.NewRollup`
> Removes second constructor for Geth client. Cleans up Geth client ID field.

- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/evm/evm_facade.go
- go/enclave/rollupchain/rollup_chain.go
The EVM facade and rollup chain both require the same chain config, but we have hardcoded it twice. We should use a single chain config that's passed around.
Refactoring.
- Uses a single chain config across the EVM facade and rollup chain
> Uses shared chain config across EVM facade and rollup chain.

- go/common/types.go
- go/enclave/core/rollup.go
- go/enclave/core/types.go
- go/enclave/crypto/transaction_blob_crypto.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/mempool/interface.go
- go/enclave/mempool/manager.go
- go/enclave/rollupchain/rollup_chain.go
- integration/simulation/transaction_injector_counter.go
- tools/obscuroscan/obscuroscan.go
Addresses a todo by deleting a useless type alias.
Refactoring.
- Removes `L2Txs` type
> Removes L2Txs type, per todo.

- go/enclave/enclave.go
to avoid crashing the evm 
Functional PR.
It turns out that each fork has to be enabled one by one. It's not enough to enable a later one.
What happened is that some prereqs were not run because they were introduced by an earlier fork, and used in a later fork.
> enable all forks up to london

- docs/_data/navigation.yml
- docs/testnet/handling-sensitive-data.md
We do not have any documentation currently on which RPC methods are supported, which ones are encrypted, and the visibility rules on who can decrypt them.
- Adds docs page explaining the above.
> Documents supported and sensitive RPC methods

- integration/common/viewkey/viewkey.go
- integration/simulation/network/azureenclave.go
- integration/simulation/network/dockerenclave.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
- integration/simulation/output_stats.go
- integration/simulation/simulation.go
- integration/simulation/simulation_tester.go
- integration/simulation/transaction_injector.go
- integration/simulation/validate_chain.go
- integration/walletextension/wallet_extension_test.go
- tools/networkmanager/inject_txs.go
- we want to make sure we test the viewing key encryption paths with the simulations
- we want to use a version of transaction injector to smoke test for testnet issues
*functional*
- Create rpc client per wallet for testing, register viewing key for it
- Bundled together the different types of client that come out of create network
- transaction_injector.go (where the correct client for the wallet is now used with its viewing key for encryption)
- obscuro_node_utils.go (where the wallet clients are setup and viewing keys registered)
- network.Clients struct in network.go (where some convenience methods for interacting with the networks are provided)
> Add viewing keys in tx injector

- .gitignore
- README.md
- docs/testnet/deploying-a-smart-contract-programmatically.md
- docs/testnet/deploying-a-smart-contract-programmatically.py
- Adds a section to the top level readme that references docs on how to deploy a contract with metamask
- Adds a section to demonstrate how to programmatically deploy and interact with a contract on to Obscuro Testnet
- update the top level readme for referencing docs on using metamask for manual deployment 
- added deploying-a-smart-contract-programmatically.md and deploying-a-smart-contract-programmatically.py into docs/testnet and referenced the md file in the top level readme. 
- check that deploying-a-smart-contract-programmatically.md supplies enough information to be useful to a user and whether more detail is required
> Moray/readme metamask + programmatic deployment 

- testnet/testnet-deploy-contracts.sh
- tools/contractdeployer/README.md
- tools/contractdeployer/cli.go
- tools/contractdeployer/cli_flags.go
- tools/contractdeployer/contract_deployer.go
- tools/contractdeployer/main/main.go
- we want to deploy L1 and L2 contracts as part of testnet setup, this is to pave the way for that
- I think most flexible way to be able to use this tool for that stuff is to have it be called once per contract it is deploying rather than having preset hardcoded bundles of contracts to deploy
*refactor*
- add 'contract' param that for now accepts 'MGMT' or 'ERC20' as a value, and then deploys the associated bytecode
- output deployed address as final line of output (to replace the json blob that was getting output before)
- `testnet-deploy-contracts.sh` for change in how it is called (and how the output is read)
- `contract_deployer.go` for whether refactor is sensible (it prepares us to be able to add an --L1Deployment boolean flag that will build the client etc. differently)
> Refactor contract deployer to do single contract deployments

- go/ethadapter/geth_rpc_client.go
- go/host/host.go
- https://github.com/obscuronet/obscuro-internal/issues/659
- Functional
- After restarting the subscriber, reingests any missing blocks
> re-ingests blocks

- go/enclave/bridge/bridge.go
- go/enclave/enclave.go
- integration/simulation/network/azureenclave.go
- integration/simulation/network/dockerenclave.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/socket.go
- integration/simulation/params/params.go
- integration/simulation/params/wallet_utils.go
- integration/simulation/transaction_injector.go
- integration/simulation/validate_chain.go
- integration/walletextension/wallet_extension_test.go
At the moment the two hardcoded ERC20 contracts are called BTC and ETH. I'm going to rename the BTC one to OBX if there are no objections. Long term we might not be modelling OBX as an ERC20, but for now we want one of our bridge-able tokens should be 'canonical' OBX
*refactor*
- rename BTC to OBX
- some tidying up
> Rename BTC dummy token to OBX

- go/enclave/enclave.go
From my understanding, there's either postState (root) set as the state Hash or Status field set as true/false.
That's from and interpretation from https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md: 
`For blocks where block.number >= BYZANTIUM_FORK_BLKNUM, the intermediate state root is replaced by a status code, 0 indicating failure (due to any operation that can cause the transaction or top-level call to revert) and 1 indicating success.`
And it seems like that is what hardhat thinks should happen.
```
Formatter.prototype.receipt = function (value) {
var result = Formatter.check(this.formats.receipt, value);
// RSK incorrectly implemented EIP-658, so we munge things a bit here for it
if (result.root != null) {
if (result.root.length <= 4) {
// Could be 0x00, 0x0, 0x01 or 0x1 …
```
> removes setting both poststate and status fields

- tools/walletextension/main/main.go
See https://github.com/obscuronet/obscuro-internal/issues/665.
Previously, the wallet extension would immediately start taking requests and trying to send them to the host. These requests would eventually lead to timeouts, but it wasn't always clear whether it was a genuine timeout, or the host just couldn't be reached.
Functional.
- Wallet extension pauses at start-up for 30 seconds to try and connect to host, and exits if it cannot connect
> Waits for host when starting wallet extension.

- go/enclave/db/interfaces.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/host/client_api_eth.go
- go/host/enclave_client.go
- go/host/in_mem_obscuro_client.go
- go/rpcclientlib/obscuro_client.go
- integration/walletextension/wallet_extension_test.go
Geth returns `nil` if you request a transaction receipt that does not exist via RPC. Our RPC API returns an error instead. We should follow their approach.
Functional.
- Return `nil` receipt for transaction receipt if transaction cannot be found
- Skip decryption in RPC client if result is `nil`
> Return nil rather than error for non-existent receipt

- tools/obscuroscan/static/index.js
ObscuroScan's front-end code can sometimes await the text for a single response twice, causing an error.
Functional.
- Stores response text in a constant, and reuses that
> Avoids case where the text for a single response is awaited twice, causing an error.

- go/common/enclave.go
- go/enclave/db/interfaces.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/host/client_api_eth.go
- go/host/in_mem_obscuro_client.go
External tooling will work better if we align ourselves to the Geth API, which returns nil rather than error for the following API methods:
* `GetBlockByNumber`
* `GetBlockByHash`
* `GetTransactionByHash`
Functional.
- Methods above now return `nil` instead of error
> Return nil rather than error for unfound transactions and blocks

- tools/obscuroscan/obscuroscan.go
- tools/walletextension/wallet_extension.go
Linter was complaining about Slowloris attack, because ObscuroScan and the wallet extension never timeout requests.
Functional.
- Adds a ten-second timeout for requests to ObscuroScan and the wallet extension
> Prevents potential Slowloris attack.

- go/host/client_api_obscuro.go
- go/host/hostdb.go
ObscuroScan requires the ability to retrieve a rollup by number. Currently, we have to walk the entire chain back until we find the rollup we want. This is very inefficient.
Refactoring.
- KV store now has mapping from rollup number to rollup hash, providing an efficient lookup
> Efficiently retrieve a rollup by number

- go/host/client_api_obscuro.go
- go/rpcclientlib/obscuro_client.go
- tools/obscuroscan/obscuroscan.go
- tools/obscuroscan/static/index.js
Currently, to retrieve the five latest transactions, ObscuroScan makes an RPC request for each rollup in turn, and checks its transactions. This is fine when there is reasonable network traffic, since only a few rollups will be checked. However, if the network is quiet (e.g. during a weekend initially, or before opening to external devs), you can have to work through thousands of rollups to find five transactions. This is very slow.
Refactoring.
- There's a single HTTP request between ObscuroScan and the host to get all the latest transactions, rather than one per rollup
> Avoids endless HTTP hops when retrieving latest transactions.

- go/host/client_api_obscuro.go
- go/host/host.go
- go/host/hostdb.go
ObscuroScan needs the ability to retrieve rollups based on a transaction hash. Currently, it does this by walking the entire chain back to find the transaction hash. This will be very slow as the number of rollups grows.
Refactoring.
- Greatly speeds up the recovery of the rollup for a given tx hash
> Efficient retrieval of rollup given a tx hash

- tools/obscuroscan/obscuroscan.go
- tools/obscuroscan/static/index.js
Previously, the wrong JSON array was returned to the front-end, leading to fields of `Undefined` rather than `N/A`.
Functional.
- Fixes bug where latest transactions initially shows `Undefined`
- Removes info on causes from front-end (this is pushed to the logs now)
> Was converting wrong array to JSON.

- tools/obscuroscan/static/index.js
Previously, if looking up a rollup or transaction failed, it wouldn't reset the transaction blob or scroll the screen to display the result.
Functional.
- Resets transaction blob view and scrolls screen correctly on rollup lookup failure
> Resets transaction blob view and scrolls screen correctly on rollup lookup failure.

- go/ethadapter/obscuro_rpc_client.go
- go/rpcclientlib/client.go
- go/rpcclientlib/network_client.go
- go/rpcclientlib/viewing_key_client.go
- integration/common/viewkey/viewkey.go
- integration/noderunner/noderunner_test.go
- integration/simulation/network/obscuro_node_utils.go
- tools/networkmanager/inject_txs.go
- tools/obscuroscan/obscuroscan.go
- tools/walletextension/wallet_extension.go
- getting rid of viewing key enabled flag in the enclave requires we support VK enc/dec in the in-memory client
- separating the view key enc/dec logic means we won't duplicate it
- separated the viewing key layer from the RPC layer in our client 
- ViewingKeyClient now wraps an underlying client and in a follow-up I'll have it wrap the in-memory version for the tests
- rpcclientlib changes
> Separate view key layer from low-level node client

- go/common/types.go
- go/enclave/crypto/transaction_blob_crypto.go
- tools/obscuroscan/obscuroscan.go
Currently, we reuse the same nonce every time we encrypt a transaction blob. This is insecure.
Refactoring.
- Uses a unique nonce per transaction blob encrypted
> Avoid nonce reuse when encrypting transaction blobs

- go/host/client_api_eth.go
MetaMask expects the `eth_feeHistory` endpoint to exist. Not having it is not an issue, but causes log noise.
Functional.
- Adds dummy `eth_feeHistory` endpoint
> Adds dummy fee history method.

- README.md
- missed important step for local testnet to have parity with main testnet
> Add L2 contract deployments to local testnet readme

- docs/testnet/essentials.md
See https://github.com/obscuronet/obscuro-internal/issues/685: "Rather than use ObscuroScan a Testnet participant might want to independently decrypt the encrypted transaction blob. To achieve this they will need to use the shared secret used in Testnet. Make the shared secret available on the docsite for Testnet."
Functional.
- Adds the shared secret to the docsite
> Documents the rollup encryption key.

- go/enclave/crypto/crypto.go
We left a todo to check that the way we were generating randomness in the enclave was secure. Upon further research, it turned out it was.
Refectoring.
- Removes todo
- Uses helper to automate length check
> Removes todo around generating randomness in the enclave

- integration/simulation/utils.go
Requesting the receipt for a non-existent transaction now returns the empty string, not an error. The simulation utils need to be updated to account for that.
Refactoring.
- Handles the special case of the receipt being empty
> Adds special handling for the fact that non-existent tx receipts now returns empty string.

- go/enclave/core/rollup.go
Needed so that we can report average rollup time easily in ObscuroScan. It's also an expected field in headers.
Functional.
- Sets the time in rollup headers
> Sets time field in rollup headers.

- go/config/host_config.go
- go/host/hostrunner/cli.go
- go/host/hostrunner/cli_flags.go
- go/host/p2p/p2p.go
See https://github.com/obscuronet/obscuro-internal/issues/704.
Currently, host P2P connections never time out (possibly the OS eventually cuts them off, not sure). In addition, P2P messages are not broadcast in parallel. So a single unreachable node can block broadcast for the entire network.
Functional.
- Adds timeout for P2P connections
- Makes timeout configurable
- Broadcasts P2P messages in parallel
> Adds timeouts for host to host P2P connections

- go/common/types.go
- go/enclave/bridge/bridge.go
- go/enclave/core/rollup.go
- go/enclave/core/types.go
- go/enclave/crypto/crypto.go
- go/enclave/crypto/transaction_blob_crypto.go
- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_metadata.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/rollupchain/rollup_chain.go
- tools/obscuroscan/obscuroscan_test.go
`TransactionBlobCrypto` is currently aware of specifics of rollups and how they're mapped back and forth. Its only responsibility should be encrypting and decrypting tx blobs.
Refactoring.
- Moves logic for creating rollups and ext rollups out of `TransactionBlobCrypto`
- Makes a few methods and constants non-public
> Separation of duties for transaction blob crypto.

- go/common/httputil/httputil.go
- go/enclave/attestation.go
- go/enclave/core/egoutils/egoutils.go
- go/enclave/db/sql/edb_attestation.go
- go/enclave/db/sql/sqlite.go
- go/ethadapter/obscuro_rpc_client.go
- go/rpcclientlib/network_client.go
- go/rpcclientlib/viewing_key_client.go
- integration/common/viewkey/viewkey.go
- integration/gethnetwork/geth_network.go
- integration/simulation/network/obscuro_node_utils.go
- integration/smartcontract/smartcontracts_test.go
- tools/networkmanager/inject_txs.go
- tools/walletextension/wallet_extension.go
There is an edgecase where the JSON fails to be marshalled when verifying an attestation. This case should be caught and flagged.
Functional.
- Catch JSON marshalling error in attestation verification
> Handle case where JSON can't be marshalled in attestation

- go/host/rpc/clientapi/client_api_eth.go
- https://github.com/obscuronet/obscuro-internal/issues/596
- Fixes the expected strings returns in the block number field
- functional
> Adds latest/earliest block fetch to eth_getBlockByNumber

- .github/workflows/golangci-lint.yml
- .golangci.yml
- go/enclave/db/sql/edb_attestation.go
- go/enclave/db/sql/sqlite.go
- go/enclave/evm/evm_facade.go
- go/ethadapter/mgmtcontractlib/mgmt_contract_lib.go
- go/host/p2p/p2p.go
- integration/gethnetwork/geth_network.go
- integration/walletextension/wallet_extension_test.go
- tools/azuredeployer/azure_deployer.go
- tools/walletextension/wallet_extension.go
- To fix the linter
- Updated to version 1.48.0
- Fixed the go version of the linter to 1.17
- Updated config to skip some directories (design and docs)
```
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
```
And update the tooling using the new path: 
```
> which golangci-lint
/Users/otherview/go/bin/golangci-lint
```
> Fixes Golangci-lint

- go/rpcclientlib/viewing_key_client.go
- integration/common/viewkey/viewkey.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/static/javascript.js
- tools/walletextension/wallet_extension.go
Currently, when using the viewing key client, the viewing key's address is only passed when submitting the viewing key, not when generating it.
As we move towards supporting multiple viewing keys in a single wallet extension, we'll need to pass the address at generation time, so we can store the generated viewing key against the address.
> Moves setting of VK address earlier in lifecycle. Clean up.

- go/rpcclientlib/viewing_key_client.go
- go/rpcclientlib/viewing_key_client_test.go
Currently, the WE sets the `from` field on an eth_call request using the current VK. However, as we start supporting multiple VKs, this will not be possible.
We add logic to try and find the `from` field in the eth_call's `data` field, as a fallback.
Functional.
- If `eth_call` has missing `from` field, try and determine how to set it based on the `data` field
> Adds logic to set eth_call `from` field using `data` field as a fallback.

- go/ethadapter/obscuro_rpc_client.go
- go/rpcclientlib/client.go
- go/rpcclientlib/viewing_key_client.go
- we can't populate the typed pointer in the rpc client when we have a nil response
- we return a specific Nil Response error so that caller can check for it (no more onerous than if they had to nil-check their data type, and this is more idiomatic Go)
- add nil response to client
- add nil transaction response to higher-level client
The contract deployment now succeeds against testnet:
```
Preparing contract deployer with config: {
"NodeHost": "obscuronode-0-testnet-1.uksouth.cloudapp.azure.com",
"NodePort": 13000,
"IsL1Deployment": false,
"PrivateKey": "6e384a07a01263518a09a5424c7b6bbfc3604ba7d93f47e3a455cbdd7f9f0682",
"ChainID": 777,
"ContractName": "L2ERC20",
"ConstructorParams": [
"JAM",
"JAM",
"1000000000000000000000"
]
}
0xdDb7b4973DfC4F151BF7DEf4fD3ABFd899Bc1778
```
> Use error for RPC nil response

- go/rpcclientlib/viewing_key_client.go
- go/rpcclientlib/viewing_key_client_test.go
- integration/common/viewkey/viewkey.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/static/javascript.js
- tools/walletextension/wallet_extension.go
Another step in enabling multiple viewing keys. We still use a single key for decryption, but we allow registration of multiple viewing keys now.
Functional.
- Allows multiple viewing keys to be stored, keyed by address
> Allow multiple viewing keys to be stored (still a single key used for decryption)

- integration/walletextension/wallet_extension_test.go
Pulls registering an account into a helper in the wallet extension tests.
Refactoring.
> Uses helper to reduce duplication in WE tests.

- tools/walletextension/wallet_extension.go
- some methods return nil and that should be propagated to the WalletExtension caller as `"result": null`
- Change wallet extension to check for ErrNilResponse and return the null result instead of an error
> Handle nil response in wallet extension

- go/enclave/db/storage.go
The API for `eth_getBalance` requires that we can check the balance at any block. Currently, there is no API to grab the rollup with a specific height.
Functional.
- Adds API to get rollup with a specific height
> Adds method to retrieve a rollup by height.

- go/enclave/db/interfaces.go
- go/enclave/rollupchain/rollup_chain.go
Currently, `eth_getBalance` returns the latest balance, not the balance at a specific block.
Functional.
- Returns the balance at a specific rollup
> Gets balance at specific rollup, not always latest.

- go/ethadapter/obscuro_rpc_client.go
the nonce call fails
- functional
- add latest block as default param to the nonce call
-
> add block number to the nonce call

- go/enclave/db/sql/sqlite.go
testnet failing with:
```[35mCRIT [0m[08-16|10:31:37.050] Failed to store block body               [35merr[0m="Error 1406: Data too long for column 'val' at row 1"```
functional
-increase the size of the blob field
> increase the size of the `val` column

- go/ethadapter/obscuro_rpc_client.go
Previously, we tried to get the result directly as a uint64, but it is returned as a string.
Functional.
- Correctly converts result from string
> Correctly handles returned value from eth_getTransactionCount request.

- .github/workflows/manual-deploy-dev-testnet.yml
- testnet/testnet-deploy-contracts.sh
- testnet/testnet-deploy-l2-contracts.sh
- Fixes reported issue of https://github.com/obscuronet/go-obscuro/runs/7872816190?check_suite_focus=true
- fix
> Dev testnet uses it's own deployer image

- go/common/enclave.go
- go/enclave/enclave.go
- go/enclave/rpc_server.go
- go/host/node/node.go
- go/host/rpc/enclaverpc/enclave_client.go
I've started seeing test failures where a block submission happens after we've shut down the node. Shutting down the node causes it to break its connection to the enclave, which causes panics in subsequent RPC calls to submit further blocks (since the connection is broken) if these happen before the test concludes.
Here is the failure message:
```
Aug 17 12:35:49.990 INF Stopped monitoring for l1 blocks
Aug 17 12:35:49.990 PNC >   Agg0: Failed to submit block. Cause: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:31301: connect: connection refused"
```
You can see by the "Stopped monitoring for l1 blocks" message that this is happening at the end of the test, during shutdown.
Functional.
- `Enclave.SubmitBlock` now returns …
> Returns an error instead of panicking if cannot submit block.

- integration/walletextension/wallet_extension_test.go
Previously, we used `defer` instead of `t.Cleanup` in the wallet extension tests. This forced us to write lots of duplicated codes so that the `defer`s were called in the right places.
Refactoring.
- ...
> Uses t.Cleanup to simplify wallet extension tests.

- go/enclave/enclave.go
- go/enclave/rpc/rpc_utils.go
- integration/gethnetwork/geth_network_test.go
- pull_request_template.md
- tools/walletextension/wallet_extension.go
Just some spelling/wordings that keep catching my eye
- change PR placeholder to be deploy into dev-testnet instead of merge, think that's what is meant by it
- marshal has single "l" (it was mostly me misspelling them in first place 😳)
- typos
> minor wording fixes

- integration/walletextension/wallet_extension_test.go
With non-zero gas prices becoming mandatory, we need to do faucet transfers in the wallet extension tests.
As a precursor to that, I wanted to introduce logic in the tests to wait for a tx's receipt (this will be useful to wait for the preallocation). This helped refactor out some other duplicated code.
Refactoring.
- Introduces method to wait for transaction receipt
- General clean-up
- ...
> Waits for receipt when submitting tx in wallet extension tests

- integration/simulation/simulation.go
- integration/simulation/transaction_injector.go
- integration/walletextension/wallet_extension_test.go
More clearing of the way to enable setting of a gas price in the WE tests.
Functional.
- WE tests now retrieve nonce via wallet extension, rather than going directly via clients (which is not what we're trying to test here)
- Some more clean-up
- ...
> WE tests: More tidying. Retrieves nonce via wallet extension, not directly via clients

- integration/gethnetwork/geth_network.go
- integration/simulation/simulation.go
- integration/walletextension/wallet_extension_test.go
- tools/contractdeployer/contract_deployer.go
Before we can enable a mandatory minimum gas price, the wallet extension tests have to support prefunding of accounts.
Functional.
- Prefunds accounts in wallet extension tests
- ...
> Adds gas price to wallet extension test transactions.

- integration/datagenerator/common.go
- integration/gethnetwork/geth_network.go
- integration/simulation/network/geth_utils.go
We have had issues on CI that appear to be related to Geth nodes not being stopped correctly.
Functional.
- Print out message when Geth nodes are stopped, to identify missing, unstopped nodes
- ...
> Prints message to indicate when a Geth node is stopping, to detect unstopped Geth nodes

- integration/walletextension/wallet_extension_test.go
- we are seeing Wallet Extension failures on CI and need more info, suspect an error is being returned and not logged
- log the repsonse json for failed nonce request
> identify nonce-req failure in walext

- docs/testnet/changelog.md
- go/config/enclave_config.go
- go/enclave/enclave.go
- go/enclave/enclaverunner/cli.go
- go/enclave/enclaverunner/cli_flags.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/simulation.go
Currently, enclaves accept any gas price. They should be able to choose to reject txs with insufficient gas.
Functional.
- Enclave can configure minimum gas price for accepting transaction
- Transactions with an insufficient gas price are rejected
- ...
> Allows enclaves to configure the minimum gas amount they'll accept

- go/enclave/rollupchain/faucet.go
The faucet was running out of funds.
Functional.
- Faucet allocation is now a billion times larger
- ...
> Bumps faucet prealloc by a factor of one billion.

- go/ethadapter/obscuro_rpc_client.go
- go/rpcclientlib/encrypted_client.go
- go/rpcclientlib/network_client.go
- go/rpcclientlib/viewing_key.go
- integration/common/viewkey/viewkey.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/walletextension/wallet_extension_test.go
- tools/networkmanager/inject_txs.go
- tools/walletextension/multi_acc_helper.go
- tools/walletextension/multi_acc_helper_test.go
- tools/walletextension/wallet_extension.go
- Pre-requisite for the go-obs client
- (hopefully) makes the RPC client logic layers easier to reason about
- The EncRPCClient introduced here is used in *both* the wallet extension and the AuthClient that's coming.
This change also moves the multi-acc fuzzy stuff out of the core client and just into wallet extension now for cleanliness.
- Add viewing key type per Tudor's suggestion to wrap account with viewing key and signature
- Rename ViewingKeyClient -> EncRPCClient, a VK-encrypting/decrypting client which is bound to a single account for its lifespan
- rework wallet extension to use a map of acc addresses -> EncRPCClients, with logic to pick the right one or retry them all
Note: this change means we will round-robin all registered clients when it's not obvious which to use, we …
> refactor wallet extension to use a map of clients

- go/ethadapter/geth_rpc_client.go
- go/ethadapter/interface.go
- go/ethadapter/obscuro_rpc_client.go
- go/rpcclientlib/client.go
- integration/common/utils.go
- integration/contractdeployer/contract_deployer_test.go
- integration/ethereummock/node.go
- integration/simulation/simulation.go
- integration/simulation/simulation_in_mem_test.go
- integration/simulation/transaction_injector.go
- tools/contractdeployer/contract_deployer.go
- tools/contractdeployer/main/main.go
The contract deployer is sent funds every time the deployer is run, even if they already have lots of funds (e.g. due to previous failed contract deploy attempts). This can drain the faucet.
Functional.
- Contract deployer is only given new funds if needed
- Adds integration test of the above
- Extends original contract deployer integration test to actually check contract is deployed
- ...
> Only send funds to contract deployer if needed. Extend contract deployer tests.

- tools/walletextension/static/index.html
- tools/walletextension/static/javascript.js
We should display public-facing addresses in this format, so that people don't accidentally make mistakes in them (e.g. when copy-and-pasting them to us to dispense funds).
Functional.
- Displays account in checksummed form in wallet extension
- ...
> Returns checksummed address in wallet extension.

- go/host/node/node.go
- go/host/rpc/clientapi/client_api_obscurotest.go
- go/host/rpc/clientrpc/rpc_server.go
- integration/simulation/network/obscuro_node_utils.go
It's clear from CI that hosts are often not being shut down properly.
Functional.
- Previously, host shutdown was run on an unawaited goroutine, so shutdown would end as soon as the process exited
- ...
> Waits for host shutdown, instead of spinning off goroutine.

- go/rpcclientlib/encrypted_client.go
- common cause of confusing errors during development is not giving the correct result pointer to encRPCClient.Call()
- perform assert on the result to make sure:
1. It is a pointer
2. It is initialized
> Assert for initialized pointer in rpc client Call

- integration/erc20contract/contract.go
- testnet/testnet-deploy-contracts.sh
- testnet/testnet-deploy-l2-contracts.sh
- tools/contractdeployer/contract_deployer.go
- there was a bug, the supply parameter in scripts was being ignored during erc20 deployment
- also the supply is too small when we've got 18 decimal places
- respect the supply args in contract
- increase supply
> fix erc20 deployer supply arg

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- README.md
- go/enclave/bridge/bridge.go
- go/enclave/enclave.go
- integration/simulation/network/inmemory.go
- integration/simulation/params/wallet_utils.go
- integration/simulation/simulation.go
- integration/simulation/transaction_injector.go
- integration/simulation/validate_chain.go
- integration/walletextension/wallet_extension_test.go
- testnet/docker-compose.debug.yml
- testnet/docker-compose.non-sgx.yml
- testnet/docker-compose.yml
- testnet/start-obscuro-node.sh
- testnet/testnet-deploy-contracts.sh
- testnet/testnet-deploy-l2-contracts.sh
- There has been confusion between OBX erc20 and OBX native, using a dummy ETH erc20 could be confusing, etc.
- By calling the tokens Hocus (HOC) and Pocus (POC) we make it clear they are just for playing and remove ambiguity
**refactor**
- find/replace all the references and usages of OBX/JAM and ETH erc20 contracts
- mainly in the bridge code and in the scripts that set up our testnets
- the bridge/testnet scripts
> Rename JAM/OBX and ETH erc20s to be HOC/POC

- docs/testnet/essentials.md
- we have 'official' ERC20s deployed to testnet with static addresses, we should publish these so devs (internal and external) can use them
- add erc20 section to testnet essentials page
> Add ERC20 contracts to testet docs

- go/host/node/node.go
- go/host/rpc/clientrpc/rpc_server.go
- integration/gethnetwork/geth_network.go
- integration/simulation/network/azureenclave.go
- integration/simulation/network/dockerenclave.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
Previously, we had to perform the node RPC server shutdown in a goroutine, and we weren't sure why.
Functional.
- Adds explanatory comment explaining why using a goroutine is required
- Waits for host RPC ports to free up, to ensure the RPC server has actually stopped
- Panics instead of logging an error if the ports aren't freed, to highlight issues in the future
- ...
> Fixes node shutdown.

- go/rpcclientlib/client.go
- go/rpcclientlib/encrypted_client.go
- go/rpcclientlib/network_client.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- we want our Go ObscuroClient to support contexts like the geth client does, so we need to add support on the EncClient for it
- add CallContext methods through the rpc clients (not used by anything yet)
- is the EncClient implementation clear with its `internalCall()`? I wanted to re-use the Call() logic, maybe there's a neater way
> Add context support to EncClient

- .github/workflows/manual-deploy-dev-testnet.yml
- testnet/docker-compose.dev-testnet.yml
- testnet/start-obscuro-node.sh
- Fixed the deployment pipeline to use the correct dev image
- docker-compose and bash script
> fix dev testnet to use correct image

- go/common/logging.go
- go/enclave/evm/evm_facade.go
- Log correctly executed txs
- tx log
> bumps the tx execution to info

- integration/gethnetwork/geth_network.go
There was a race condition in the Geth start-up code (I think).
We needed to wait for all the miner-creation goroutines to return before shutting down the nodes if there were any errors. Otherwise, there's a possible race condition whereby if the creation of one node fails, we start shutting down the nodes from that goroutine, but new nodes are being spun up on other goroutines, and these are missed by the shutdown process.
Refactoring.
- Avoids race condition
- ...
> Avoids race condition in Geth shutdown.

- go/ethadapter/geth_rpc_client.go
- go/host/node/node.go
Currently, we do not retry broadcasting transactions to the L1 from the host. We error out after the first failure. This is not resilient.
Functional.
- Sets timeout for all L1 client requests
- Adds retries for L1 transaction broadcast
- ...
> Retry L1 transaction broadcast

- go/enclave/evm/evm_facade.go
Currently, we are selective in terms of what information we print from a transaction's receipt. It would be more useful to print everything.
Functional.
- Prints all non-nil fields in each receipt
One nice thing is that the JSON formatting filters out empty fields. So for regular transactions, you get:
```
Unsuccessful (status != 1). Receipt: {"root":"0x","status":"0x0","cumulativeGasUsed":"0x61b3","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
> Prints entire receipt for transactions.

- go/enclave/enclaverunner/enclave_runner.go
- go/host/hostrunner/host_runner.go
investigate crashing testnet
- functional
- force log level to trace until the config plumbing is in place
- ...
> force trace level until config implementned

- tools/contractdeployer/contract_deployer.go
The contract deployer is deploying guessing game with an erc20 address of 0x00...000, igoring the arg.
Was able to verify with the debugger that the code converting from hex string to erc20 was outputting the zero address.
- fix that conversion
> Fix bug in contract deployer for guessing game arg

- docs/testnet/essentials.md
- HOC/POC were the wrong way round. The correct addresses can be confirmed in `bridge.go` and in the L2 contract deployment logs in the testnet deployment github actions.
- swap the addresses
> Correct hoc/poc addresses in doc site reference

- go.mod
- go.sum
- go/ethadapter/obscuro_rpc_client.go
- go/obsclient/README.md
- go/obsclient/authclient.go
- go/obsclient/authclient_test.go
- go/obsclient/encoding.go
- go/obsclient/obsclient.go
- go/obsclient/test_util.go
- integration/common/utils.go
- integration/contractdeployer/contract_deployer_test.go
- integration/simulation/network/azureenclave.go
- integration/simulation/network/dockerenclave.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
- integration/simulation/simulation.go
- integration/simulation/transaction_injector.go
- integration/simulation/utils.go
- integration/simulation/validate_chain.go
- tools/networkmanager/inject_txs.go
- We want a high-level Go client, analogous to the EthClient
- We want the sim-tests to use this client
- Add an ObsClient and an AuthObsClient, ObsClient is for unencrypted requests and AuthObsClient is bound to a single wallet, has a registered viewing key and provides the encrypted requests
- Wire these clients into the simulation tests to get confidence in them and avoid duplication
- These clients should eventually support all relevant methods from the EthClient and more, but for now just the bare minimum to get the tests passing and structure in place
- The /obsclient package
- The naming of these things, I went for ObsClient because of EthClient but not wedded to it at all
> Add obscuro client for Go

- go/host/interfaces.go
- go/host/node/node.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
We have a `MockHost` interface that is implemented by the host, and exposes methods required by the in-memory integration tests. Where possible, we should be removing these methods, so that we're testing the "real" host API.
Refactoring.
- Removes the `MockHost.P2P` method
- ...
> Removes host method only used by tests

- go/host/interfaces.go
- go/host/node/node.go
- integration/simulation/network/network_utils.go
Removes an unnecessary host method that's only used in tests.
Refactoring.
- Removes the `ConnectToEthNode` method
- ...
> Removes ConnectToEthNode test method.

- integration/simulation/simulation_docker_test.go
- integration/simulation/simulation_geth_in_mem_test.go
The CI times are very long. A large contributor is the large number of simulations we run.
Since we now have the test-obscuro tests and a running testnet, we no longer need as many sims to gain assurance that everything is working fine.
Functional.
- Moves the Docker and Geth sims behind an environment flag
- ...
> Puts the Docker and Geth sims behind an environment variable.

- .github/workflows/build-pr.yml
We no longer run tests using the Docker image in CI
Functional.
- Removes the set up of Docker and the Docker image build
- ...
> Removes Docker image build from CI.

- integration/walletextension/wallet_extension_test.go
Previously, running all the wallet extension tests took around five minutes. This was the bottleneck on quick CI runs.
Refactoring.
- All the WE integration tests now share a single Obscuro network
- ...
> Uses a single Obscuro network for all WE integration tests

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- https://github.com/obscuronet/obscuro-internal/issues/907
- Cleans up double vm creation
- CI changes
> Remove double vm creation + allow tags deployment

- .github/workflows/manual-deploy-testnet-l2.yml
- https://github.com/obscuronet/obscuro-internal/issues/910
- Deploying testnet triggers the faucet deployment
- adds a new step to the end of the l2 deployment
> Triggers the faucet deployemnt

- go/obsclient/authclient.go
- go/obsclient/authclient_test.go
- go/obsclient/obsclient.go
- integration/simulation/transaction_injector.go
- Per Joel's suggestion it makes this client a bit more coherent. The client is bound to a single account, it should populate the address in requests (and not allow addresses to be passed in that can never be successful).
- store account on AuthObsClient
- remove address from NonceAt method
- add BalanceAt method, also without an address field
- My main concern was wondering if we'd ever support Nonce/Balance lookups for contracts from other accounts? In which case we'd need that option. But I think current design means we won't be able to do that (contract devs would need to expose it through methods if they wanted to, and that could be permissioned)
> Remove address param from AuthClient's NonceAt and BalanceAt

- tools/walletextension/wallet_extension.go
To make it clear to the user that keys are being re-registered.
Functional.
- Prints information about re-registered keys
- ...
> Logs re-registered viewing keys.

- go/enclave/core/types.go
- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/rollupchain/rollup_chain.go
Currently, we recalculate the logs for the entire chain each time we get a new block. This isn't sustainable.
Refactoring.
- Pushes the logs for each block to the DB
- Retrieves the logs for each block from the DB
- ...
> Store logs for each block to not have to recalculate them

- pull_request_template.md
- Updating the definition of done for merging a PR
- The PR template
- The PR template
> Update the definition of done for merging a PR

- go/host/node/node.go
> Clarifies logic if a node starts processing blocks too early.

- tools/walletextension/multi_acc_helper.go
- tools/walletextension/multi_acc_helper_test.go
- Found when working on https://github.com/obscuronet/obscuro-internal/issues/911
- If the `acc` is nil, then the wallet blows up with nil point exception
- Found when runnign the following curl cmd and pointing at testnet
```
curl --location --request POST 'http://127.0.0.1:3001' \
--header 'Content-Type: application/json' \
--data-raw '{
"jsonrpc":"2.0",
"method":"eth_call",
"params":[{
"from": "0x38a47fe0c945900d2b29db7edae05178cdba3d15",
"to": null,
"gas": "null",
"gasPrice": "null",
"value": "0x3635c9adc5dea00000",
"data": ""
}, "latest"],
"id":1
}'
```
> Fixes nil point except

- integration/walletextension/wallet_extension_test.go
Now we have a `TestMain` method for the WE tests, we can set up the log file there, rather than once in each test.
Now that we use a single Geth and Obscuro network for all tests, and logs are no longer going to different files, logging out which test was starting felt a bit redundant.
> Sets log once in wallet extension tests, not every time.

- go/common/log/log.go
to be able to investigate issues on the testnet
Functional PR
- hardcode the log level to trace. 
Note: this is temporary until the logging framework is sorted
> set log level to trace

- .github/workflows/manual-deploy-obscuroscan.yml
- testnet/testnet-deploy-l2-contracts.sh
- tools/azuredeployer/networkdeployer/README.md
- tools/azuredeployer/networkdeployer/run.sh
- tools/networkmanager/cli.go
- tools/obscuroscan/main/cli.go
- Some things have hardcoded URLs/ports for the RPC connections that need updating after we switched the clients to be WS-only (this was noticed by Moray using the testnet L2 contract deployment script)
- Searched for '13000' in the code and updated the ones that were being used as RPC addresses rather than HTTP ports
- Did I change them correctly, did I miss any?
> Update default RPC ports to use WS

- go/common/retry/README.md
- go/common/retry/retry.go
- go/common/retry/retry_strategy.go
- go/common/retry/retry_test.go
- go/obsclient/clientutil/clientutil.go
- tools/contractdeployer/contract_deployer.go
- tools/contractdeployer/main/main.go
- The retry mechanism is more widely useful than just in the obsclient utils
- The contract deployer can use it as Tudor suggested in review yesterday
- I'd like to use it in particular in the node code where we need to retry connections to the L1 client (and I'll merge the backoff mechanism into it too)
- Move the retry mechanism to a small `retry` package in common
- Add a `retry.Do()` that takes a function which errors for generic retry behaviour
- Update contract deployer to use retry.Do() for the deployment
I've run the contract deployer against testnet to verify multiple attempts are made before it succeeds and outputs the contract address.
> Separate retry package for re-use

- go/common/enclave.go
- go/common/types.go
- go/enclave/enclave.go
- go/enclave/events/subscription_manager.go
- go/host/interfaces.go
- go/host/node/node.go
- go/host/rpc/clientapi/client_api_filter.go
- go/host/rpc/enclaverpc/enclave_client.go
- go/obsclient/test_util.go
- go/rpc/client.go
- go/rpc/encrypted_client.go
- go/rpc/network_client.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/multi_acc_helper.go
Creation of subscriptions is encrypted, and needs special handling via the wallet extension
- Adds a `Subscribe` method to all clients
- Implements `Subscribe` for the encrypted client
- Encrypts outbound subscription creation requests via the wallet extension
- Adds a very basic wallet extension test, showing that creating a subscription via the wallet extension doesn't blow up
> Allows sub creation to be handled by the wallet extension.

- docs/wallet-extension/wallet-extension.md
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/main/cli.go
- tools/walletextension/main/main.go
- tools/walletextension/readwriter/read_writer.go
- tools/walletextension/wallet_extension.go
Previously, we tried to handle both HTTP and WS connections on a single port. To be consistent with Geth, and to enable us to use lower-cost HTTP clients where possible, we should have two ports.
- Adds a port to the wallet extension dedicated to WS connections
- Adds some todos, about creating WS clients selectively and lazily
> Adds WS port to wallet extension server

- tools/walletextension/multi_acc_helper.go
- tools/walletextension/persistence/persistence.go
- tools/walletextension/wallet_extension.go
The WE was getting very bloated. This change moves the persistence logic into a separate package.
- Moves the persistence logic into a separate package
> WE: Splits out persistence into separate component

- go/rpc/network_client.go
- integration/contractdeployer/contract_deployer_test.go
- integration/noderunner/noderunner_test.go
- integration/simulation/network/obscuro_node_utils.go
- integration/walletextension/wallet_extension_test.go
- tools/contractdeployer/obscuro_deployer.go
Using WS everywhere may hog too many resources.
- Does not add WS protocol to every attempt to dial the client
- Fix-ups in tests
> Does not hardcode use of WS or HTTP for Obscuro clients

- go/ethadapter/geth_rpc_client.go
- go/ethadapter/interface.go
- integration/ethereummock/node.go
There are some unused L1 methods left. I removed them.
- Removes `RPCBlockchainFeed`, since unused
- Removes `getParentBlock`, which is used by the above
> Removes unused L1 methods.

- go/host/node/node.go
- go/host/rpc/clientapi/client_api_filter.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/accountmanager/account_manager.go
- tools/walletextension/readwriter/read_writer.go
- tools/walletextension/userconn/user_conn.go
- tools/walletextension/wallet_extension.go
We'd already plumbed in the return of logs from the enclave to the host to the WE. The final step was to return the logs from the WE to the user.
- Sends logs onwards from the WE to the user
- Adds integration test of logs being received
> WE: Return subscribed logs over websockets

- go/enclave/enclave.go
- go/enclave/events/subscription_manager.go
- go/enclave/rpc/rpc_utils.go
- go/rpc/encrypted_client.go
Previously, the `EncRPCClient` would encrypt params as a JSON list, regardless of whether they were a single object or an actual list. This added some messy handling on the enclave side.
- Encrypts single params as JSON objects, not lists
> Encrypts one-arg params as object, not list.

- integration/walletextension/wallet_extension_test.go
- tools/walletextension/main/cli.go
- tools/walletextension/wallet_extension.go
We modified the client to require either the HTTP or WE protocol to be specified, but didn't update the WE accordingly.
- Adds protocol when starting WE
> Adds missing protocols for connecting to node from WE.

- go/common/types.go
- go/enclave/events/subscription_manager.go
- go/enclave/rpc/rpc_encryption_manager.go
- go/rpc/encrypted_client.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/accountmanager/account_manager.go
We need to authenticate subscription requests, to prevent other people from subscribing to other accounts' logs to view the event patterns.
- Adds authentication for subscription requests
- Adds a test of subscription failing in the absence of viewing keys
> Authenticate subscription requests

- go/rpc/encrypted_client.go
- integration/walletextension/wallet_extension_test.go
- tools/walletextension/accountmanager/account_manager.go
- tools/walletextension/test/utils.go
- tools/walletextension/test/wallet_extension_test.go
Previously, we had individual integration tests for each sensitive method. This was a pain to update.
- Deleted the integration tests for calling each sensitive method without a viewing key
- Added a unit test to check that none of the sensitive methods can be called without a viewing key
> WE: Move integration tests of sensitive methods without viewing key to unit tests

- tools/walletextension/test/wallet_extension_test.go
It will be easier to write tests going forward, as we can easily add API endpoints to hit.
- Replaces custom HTTP server with Geth RPC layer in WE unit tests
- Uses test cleanup instead of using defers and shutdown handles in WE unit tests
> Replaces server with real Geth RPC layer.

- integration/walletextension/wallet_extension_test.go
- tools/walletextension/test/apis.go
- tools/walletextension/test/wallet_extension_test.go
Ongoing move to WE unit tests instead of integration tests where suitable
- Moved more tests over
> WE: Remove cannot-do-for-another-account integration tests

- go/enclave/enclave.go
- go/enclave/enclave_test.go
- go/enclave/events/subscription_manager.go
- go/enclave/rpc/rpc_utils.go
- go/rpc/encrypted_client.go
- integration/walletextension/wallet_extension_test.go
- We made a change to encrypt param as a single element if there was just one of them but semantically it is a list really and we hit issues with methods that have one req param and one optional param (fiddly for code that handles it)
- Revert commit https://github.com/obscuronet/go-obscuro/commit/1f6f04ba81cf907ceade1ffa1a9bb40e98ec6531
- Make estimateGas tolerant to not always getting two params
> Revert to always encoding rpc params as a list

- go/rpc/network_client.go
- client `Call` expects a pointer as the comment says, and it just passes it through to the next layer of client
- Tudor noticed difference between Call and CallContext, Call was taking the pointer of the result
- Change Call to pass the result through unchanged
- It's not used much, I've checked tests are passing and it should be identical to the context method.
> Fix bug on network client call result pointer

- go/enclave/bridge/bridge.go
- go/obsclient/authclient.go
- go/rpc/encrypted_client.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/simulation/params/params.go
- integration/simulation/simulation.go
- integration/simulation/simulation_geth_in_mem_test.go
- integration/simulation/simulation_in_mem_test.go
- integration/simulation/simulation_tester.go
- integration/simulation/validate_chain.go
- tools/walletextension/accountmanager/account_manager.go
We need an end-to-end test to check that logs are working fine (e.g. to flag breaking changes in PRs).
- Adds a check in the full-network sims that the HOC and POC deployment events are received correctly
> Adds rudimentary log event checks to the sims

- go/common/enclave.go
- go/enclave/enclave.go
- go/enclave/rpc_server.go
- go/host/node/node.go
- go/host/rpc/clientapi/client_api_obscuroscan.go
- go/host/rpc/enclaverpc/enclave_client.go
Occasionally, during simulation shutdown, the shutdown sequence will cause one of these panics to be triggered, causing a successful simulation to fail. More generally, it's better to raise these issues and allow them to be handled.
- Replace panics in enclave_client with return of errors
> Replaces panics in enclave client with errors

- go/common/rpc/converters.go
- go/enclave/events/subscription_manager.go
- go/host/rpc/enclaverpc/enclave_client.go
- go/rpc/encrypted_client.go
- integration/simulation/simulation.go
- tools/walletextension/accountmanager/account_manager.go
- tools/walletextension/test/apis.go
- tools/walletextension/test/wallet_extension_test.go
The host must not be able to inspect the logs
- Encrypts the logs with the relevant viewing key on the enclave
- Decrypts the logs with the relevant viewing key in the EncRPCClient
> Encrypts logs between enclave and client

- go/enclave/enclave.go
- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
- go/enclave/rpc/rpc_utils.go
- integration/simulation/validate_chain.go
A transaction can generate logs that are not relevant to the sender. These should be filtered out before the receipt is returned.
> Filters logs in transaction receipts.

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/storage.go
- go/enclave/rollupchain/rollup_chain.go
Previously, we returned historical logs based on the subscriptions at the time the rollup was processed, rather than based on the current subscriptions. For example, a log in rollup N wouldn't be returned if the subscription was created at rollup N+1.
> Recalculate historical subscribed logs based on current subscriptions

- go/common/types.go
- go/enclave/events/subscription_manager.go
- go/enclave/rpc/rpc_encryption_manager.go
- go/rpc/encrypted_client.go
Previously, each subscription was going to have a list of authenticated accounts, so we made a struct to represent each one.
Since, we've decided to move towards a single account per subscription, so the struct isn't necessary.
> Removes unnecessary AccountSubscription type.

- docs/README.md
- docs/_data/navigation.yml
- docs/api/apis.md
- docs/api/sensitive-apis.md
We need to document the subscription APIs that we've introduced
- Split the API docs into sensitive and non-sensitive
- Pulled the API docs out of the wallet extension section, where they didn't belong
- Documented the eth_subscribe and eth_unsubscribe methods
- Updated the readme - the build step is unnecessary when building the docs locally, since serving the docs locally automatically builds them as well
> Updates API docs to cover subscriptions. Clean-up.

- .github/workflows/manual-deploy-obscuroscan.yml
- tools/azuredeployer/networkdeployer/run.sh
- tools/obscuroscan/main/cli.go
Obscuroscan is failing to start in testnet with the following error:
```
panic: clients for Obscuro only support the http:// and ws:// protocols
goroutine 1 [running]:
github.com/obscuronet/go-obscuro/tools/obscuroscan.NewObscuroscan({0x7ffe0d14dd98, 0xc0000426e0})
/home/go-obscuro/tools/obscuroscan/obscuroscan.go:85 +0x22e
main.main()
/home/go-obscuro/tools/obscuroscan/main/main.go:12 +0xb1
```
The rpc address points to the websocket port but doesn't include the protocol.
- Changed to http and http port (can make it WS if preferred).
- updated any references to it in scripts
> Update obscuroscan client url to use http protocol

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
Following discussion with Thomas at Edgeless we came to the conclusion that the DC2s SGX VM might not have the memory to handle the 4GB EDB image. He tested it successfully with the DC4s VM so this PR bumps our VMs up to DC4s.
If this PR is merged then I will *not* merge the PR that rolls back the 1GB -> 4GB EDB image upgrade so we can test if this fixes our issues with EDB falling over.
> Use beefier SGX VMs for testnet to handle the 4GB EDB image

- go/host/rpc/enclaverpc/enclave_client.go
- After recent change to use the production-ready 4GB Edgeless DB image we are seeing the enclave client fail to connect from the host
- I can see in the logs that the enclave finished its handshake with the edgeless DB just one second later (the previous issue of it aborting has resolved).
- There is no rush for this connection, the host should wait a reasonable amount of time at startup for the enclave RPC server to be responsive
- Increase enclave client connection timeout from 30 seconds to 60 seconds
> Increase wait for enclave client connection

- tools/walletextension/test/utils.go
- tools/walletextension/test/wallet_extension_test.go
- tools/walletextension/wallet_extension.go
To avoid the need to create separate clients to register viewing keys and create subscriptions.
- Added support for registering viewing keys over WS
- Added test
- Test cleanup
> Allows viewing keys to be registered over websockets

- tools/walletextension/wallet_extension.go
- If wallet extension fails to create and register an obscuro client then it returns the error but then stores a nil client in the map, causing nil pointers to be spammed in the logs
- Put in the return statement that I missed originally after returning the error to the caller
> Missed return statement in walext error handling

- go/host/hostrunner/cli.go
- go/host/interfaces.go
- go/host/node/node.go
- go/host/rpc/clientapi/client_api_filter.go
- go/obsclient/authclient.go
- go/obsclient/test_util.go
- go/rpc/client.go
- go/rpc/encrypted_client.go
- go/rpc/network_client.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- tools/walletextension/accountmanager/account_manager.go
- tools/walletextension/common/constants.go
- tools/walletextension/test/apis.go
- tools/walletextension/test/utils.go
- tools/walletextension/test/wallet_extension_test.go
A subscription is supposed to return the subscription ID when the subscription is created (e.g. to allow unsubscription, and to establish which events correct to which subscription). See https://geth.ethereum.org/docs/rpc/pubsub for the format the response is expected is.
> WE: Return correct response when new subscription is created

- go/host/events/logs.go
- go/host/node/node.go
node.go has become a dumping ground.
> Pulls log event management out of node.go.

- go/enclave/events/subscription_manager.go
Subscriptions should not return historical items, only new ones since the creation of the subscription.
> Filters out historical logs in subscriptions.

- go/enclave/db/interfaces.go
- go/enclave/db/storage.go
- go/enclave/events/subscription_manager.go
- integration/simulation/transaction_injector.go
There was a bug whereby the subscriptions where started from the number of the current L1 block, rather than of the current L2 block.
> Starts subscriptions from latest rollup.

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l1.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- testnet/gethnetwork.Dockerfile
- testnet/testnet-local-gethnetwork.sh
- Per discussions between Gavin and Tudor we have decided 3 nodes is unnecessary for testnet and dev-testnet
- This will save resources on azure (and datadog)
- Change L1 geth network scripts to only setup 2 geth nodes
- Change L2 docker compose scripts to only setup 2 obscuro nodes
- Update some comments
> Reduce number of testnet L1 + L2 nodes from 3 to 2

- go/common/logs.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/log_for_storage.go
- go/enclave/enclave.go
- go/enclave/events/subscription_manager.go
- go/host/rpc/clientapi/client_api_filter.go
- go/obsclient/authclient.go
- go/rpc/encrypted_client.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/simulation/simulation.go
- integration/simulation/validate_chain.go
- tools/walletextension/accountmanager/account_manager.go
- tools/walletextension/test/wallet_extension_test.go
- Implements the GetLog method
There are a few ToDos that I'd like to pick up in a subsequent PR:
1. We're going to shift from passing in the address of the account the eth_getLogs request is for, to parsing the address from the first topic of the filter criteria
2. We're still seeing dupe logs returned, which all have zero hashes, indices, and block hashes. These are being created by the chain processing in the enclave, so I will fix separately (getting the logs is just highlighting the issue)
> Implement GetLogs method

- go/host/events/logs.go
There was a bug that led to the logs for each rollup being distributed multiple times. Because the subscriptions were stored by value not by pointer, retrieving them and then updating them was having no effect.
> Fixes bug that lead to sending of duplicate logs.

- tools/walletextension/userconn/user_conn.go
- tools/walletextension/wallet_extension.go
Previously, we closed the websocket connection after each request. This was breaking the e2e tests, which expected to be able to funnel multiple requests over a single websocket.
Also took the opportunity to wrap more of the error handling inside `userconn.go`.
> Handle multiple requests on one websocket connection

- go/enclave/events/subscription_manager.go
We were starting the subscriptions from the current block, not the next block. This does not align with the Geth API.
> Fixes start block of subscription.

- go/enclave/events/subscription_manager.go
- go/rpc/encrypted_client.go
It's a completely normal occurrence for the subscription to have been removed (i.e. unsubscribe has been called) before we can get around to encrypting the subscription results. It's fine to ignore this when it happens.
> Avoids panicking if a subscription has been removed.

- go/common/enclave.go
- go/common/logs.go
- go/common/rpc/converters.go
- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
- go/host/events/logs.go
- go/rpc/encrypted_client.go
Currently, we send all logs over RPC, only to drop the already-seen ones on the host. It's much more efficient to discard the already-seen ones on the enclave.
> Move filtering out of already-seen logs from host to enclave

- docs/wallet-extension/wallet-extension.md
- tools/walletextension/main/cli.go
- As part of the end to end testing I need to run multiple wallet extensions concurrently. At the moment the wallet extension persistence file is not exposed at the cli to allow setting, which makes it a single point of contention. This PR exposes setting the persistence file location. 
- CLI parsing and docs
> Allow the wallet extension persistence path to be set on the cli

- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
Previously, the subscribed logs were calculated at every recursive step of `rollup_chain.go/update_state()`. This was unnecessary and made the method signature of `update_state()` too complex.
> Do not calculate subscribed logs on every step on `rollup_chain.go/update_state()`

- go/enclave/events/subscription_manager.go
- integration/datagenerator/wallet.go
- integration/ethereummock/mgmt_contract_lib.go
- integration/simulation/network/inmemory.go
- integration/simulation/validate_chain.go
With the existing logic for checking whether an address is a user address, stuff like topic indices (e.g. `0x0000000000000000000000000000000000000002`) was being flagged as a user address.
We now only consider something to be a user address if:
* It exists in the state DB
* It has a non-zero balance
* It has a non-zero nonce
(On top of the existing checks - no associated code and at least twelve leading zero bytes).
> Add better user address checks

- tools/walletextension/test/utils.go
- tools/walletextension/test/wallet_extension_test.go
Just another layer of checking that will flag if something breaks the format of the JSON returned by the WE.
> Validates the returned JSON in the wallet extension tests.

- go/rpc/encrypted_client.go
- Reduce noise that we sometimes see in logs when looking into sim issues:
```
Oct 19 15:43:45.533 ERR subscription closed
Oct 19 15:43:45.533 ERR subscription closed
Oct 19 15:43:45.533 ERR subscription closed
Oct 19 15:43:45.533 ERR subscription closed
```
- Might be causing stuck goroutines after simulation ends
- Small bugfix where we weren't breaking out of the subscription loop when the client has been closed
> Fix stuck subscription go routine in client

- go/enclave/events/subscription_manager.go
A user address must have a non-zero nonce. This prevents accidental or malicious sending of funds to an address matching a topic, forcing its events to become permanently private.
> Checks nonce to for user addresses.

- go/enclave/evm/no_op_engine.go
- go/enclave/evm/utils.go
- integration/simulation/simulation.go
We were seeing some mysterious balances in the state, which turned out to be the coinbase transaction applied by default by the evm.
This is not expected behaviour, as that gas will have to go into a pool.
Just use a hardcoded pool for now, with a todo to be addressed when the fee work starts
> send coinbase to hardcoded pool address 

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
Currently, for each block we store, we store all the logs from the entirety of the historical chain. This leads to major redundancy in how logs are stored.
> Non-redundant log storage

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_receipts.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/evm/evm_facade.go
- go/enclave/rollupchain/rollup_chain.go
- when deploying a contract in remix, it keeps polling the native balance of that address, and it fails because there is no encryption key
High level this makes the balance of a contract account relevant to the address who deployed that contract.
Implementation:
1. For each receipt, check whether it's a contract creation, and save a mapping from contract address to transaction hash that created it.
2. when reading the balance, check if the address is a contract, and if yes, fetch the transaction signer and use that viewing key.
> eturn balance of contract addresses to the deployer of the contract

- go/enclave/enclave.go
- go/enclave/rollupchain/rollup_chain.go
- go/host/node/node.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/utils.go
- integration/simulation/validate_chain.go
Currently, nodes can be configured to be either aggregators or validators, but both types produce rollups. We change this so that only aggregators produce rollups.
- Have only aggregators produce rollups
- Check in sims that only aggregators produce rollups
> Only aggregators produce rollups

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- README.md
- testnet/docker-compose.debug.yml
- testnet/docker-compose.dev-testnet.yml
- testnet/docker-compose.non-sgx.yml
- testnet/docker-compose.yml
- testnet/start-obscuro-node.sh
Currently, all the nodes of testnet default to being aggregators. We want only a single aggregator.
- Updates testnet scripts
- Updates readme
> Allow node type to be configured in TN set up

- go/common/types.go
- go/enclave/enclave.go
- go/host/db/hostdb.go
- go/host/node/node.go
- integration/common/utils.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
- tools/walletextension/accountmanager/account_manager.go
Just some clean-up I wanted to do and TODOs I wanted to add. Also a bug fix in how the full-network sim nodes were created.
- Documents the `DB.AddSubmittedRollup` and `DB.WasSubmitted` methods
- Provides a node field to indicate whether we're the sequencer
- Adds some todos
- Fixes bug whereby full-network sim node addresses were empty
> Clean up ahead of light-batch work

- README.md
[Docker Issue](https://github.com/docker/for-mac/issues/6539)
The steps to build and run the project in the current README do not work with the latest version of docker
Added a warning notice
> Modified README to add notice of problematic Docker behaviour.

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l1.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- go/config/host_config.go
- go/host/hostrunner/cli.go
- go/host/hostrunner/cli_flags.go
- go/host/hostrunner/host_runner.go
- go/host/main/main.go
- go/host/node/node.go
- integration/gethnetwork/geth_network.go
- integration/gethnetwork/geth_network_test.go
- integration/gethnetwork/main/cli.go
- integration/gethnetwork/main/main.go
- integration/noderunner/noderunner_test.go
- integration/simulation/network/geth_utils.go
- integration/smartcontract/smartcontracts_test.go
- testnet/docker-compose.dev-testnet.yml
- testnet/start-obscuro-node.sh
Dev testnet was not starting because of l1 gas errors. Captured in bug ticket https://github.com/obscuronet/obscuro-internal/issues/1097
After investigations ( which are reflected in different changes), it turned out the problem was in parsing the start l1 command line on the azure docker setup. 
This PR also contains fixes along the way:
- adding support to the gethnetwork util for sending logging params
- passing the wallet address to the obscuro host ( not strictly necessary, but can be used for debugging)
> Fix testnet configs

- go/common/retry/retry.go
- go/common/retry/retry_strategy.go
- go/common/retry/retry_test.go
- go/host/node/node.go
- We sometimes have failures where secrets haven't exchanged or rollups get lost because L1 transaction never got mined
- These can be hard to diagnose and also we need to be provide visibility for this issue for node operators
- Add a watch for receipt part to the L1 transaction submission in the host
- Move the backing-off retry strategy to the retry package
- Fix minor bug in the retry logic where we checked if Done before recording the latest retry attempt (didn't matter in the timeout strategy)
> Watch for receipts to confirm L1 transactions

- go/common/headers.go
- go/common/rollups.go
- go/common/types.go
`common/types.go` was getting messy (shock!).
So I pulled the rollup stuff into a separate file, and the header stuff into a separate file too.
> Splits `types.go` into a few different files

- go/host/main/main.go
- testnet/start-obscuro-node.sh
- testnet/testnet-deploy-contracts.sh
in the testnet configs, we pass in binary values prefixed with 0x, which broke a new check added to the host, that prevented it from starting
- strip the 0x prefix if it exists
> fix host startup

- go/common/gethapi/transaction_args.go
- go/common/gethencoding/geth_encoding.go
- go/enclave/enclave.go
- go/enclave/evm/evm_facade.go
- go/enclave/rollupchain/rollup_chain.go
- Required for https://github.com/obscuronet/obscuro-internal/issues/929
- Uses https://geth.ethereum.org/docs/rpc/objects#transaction-call-object call object to ensure obscuro respects the same params as geth
- Uses the https://github.com/ethereum/go-ethereum/blob/fa1305f8bf1b1e6c4eadf4d12c9dd8ce7ddc4c6c/internal/ethapi/transaction_args.go#L202 ToMessage to ensure the same gas logic as geth uses.
- Added Transactions args between the Encoding of API params and the EVM .
> Using transaction args to form api request object

- .github/workflows/manual-deploy-dev-testnet.yml
- Ensures we use the dev version of the contract deployer image
- The github workflow for deploying dev testnet
> Fix to use the dev build of the contract deployer

- go/enclave/bridge/bridge.go
it is hard to test the bridge because the address was not passing the checksum
- change the address 
-
> fix the bridge address to pass the checksums

- integration/simulation/simulation.go
- integration/simulation/transaction_injector.go
- Part of https://github.com/obscuronet/go-obscuro/pull/815
- Bug description:
```
If `newObscuroTransferTx` creates Tx1 then local nonce = 1  and it issues it then remote nonce =1 
If `newObscuroWithdrawalTx` creates Tx2 then local nonce =2 and it issues it then remote nonce = 2
BUT
If `newObscuroTransferTx` creates Tx1 then local nonce = 1  and it does not issue in time then remote nonce =0
If `newObscuroWithdrawalTx` creates Tx2 then local nonce =2 but when it issues it then remote nonce = 1
```
- Tx injector does not check remote nonces
> Update local Nonce in tx injector

- go/enclave/evm/evm_facade.go
- go/enclave/rollupchain/rollup_chain.go
- go/enclave/rpc_server.go
- Errors were not being correctly propagated from the EVM to the user
- Removed error wrapping
> Fixes eth call error propagation

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- go/enclave/enclave.go
- https://github.com/obscuronet/obscuro-internal/issues/1182
- Adding more logs to figure out what's happening
- Non-sequencer nodes start is now delayed by 1 minute in testnet / dev testnet deployments
> Fixing node start out of sync

- go/common/encoding.go
- go/common/headers.go
- go/common/rollups.go
- go/enclave/core/rollup.go
- go/enclave/core/rollup_serialisation_test.go
- go/host/host.go
- integration/datagenerator/rollup.go
- integration/simulation/utils.go
- integration/simulation/validate_chain.go
- integration/smartcontract/debug_mgmt_contract_lib.go
- integration/smartcontract/smartcontracts_test.go
There was no reason for this split, which just complicated things.
> Removes ExtRollup/ExtRollupWithHash split.

- go/common/headers.go
- go/host/db/hostdb.go
- go/host/host.go
- go/host/rpc/clientapi/client_api_eth.go
- go/host/rpc/clientapi/client_api_obscuroscan.go
- tools/obscuroscan/obscuroscan.go
HeaderWithHashes is in the `common` module, but it's specific to the host DB. I've moved it across for clarity.
> HeaderWithHashes is in the `common` module, but it's specific to the host DB

- go/common/rpc/converters.go
- go/enclave/rpc_server.go
- go/host/host.go
- go/host/rpc/enclaverpc/enclave_client.go
- The block feeding changes I'm making rely on the enclave reporting back what it knows as the L1 head with failures
- There were too many spammy logs from the parent block failures
- Fix the rpc conversion to produce the correct error type from the BlockSubmissionResponse object
- Change the log level to debug for those failures when they happen for 'parent' blocks in the main path (blocks that have usually already been processed and so will always fail as a duplicate)
I verified in the logs that I'm now seeing the hashes for the enclave's view of the L1 head and no longer seeing the spam of "could not submit block" "block already processed"
> Fix issues with submit block errors

- go/enclave/rpc_server.go
- We discovered while looking at `errors.As()` docs and examples that errors are typically returned as pointers and that the `errors.As` target should be a pointer to the pointer variable.
E.g. from official docs https://pkg.go.dev/errors
```
var perr *fs.PathError
if errors.As(err, &perr) {
fmt.Println(perr.Path)
}
```
- I fixed a couple of these issues that I introduced recently
- this EVM error casting seems to be another case where it would not be casting successfully
- cast evm error to a pointer
> Fix EVM error casting to use pointer variable

- go/enclave/rpc_server.go
Reverts obscuronet/go-obscuro#840
> Revert "Fix EVM error casting to use pointer variable"

- go/host/events/logs.go
Getting concurrent access exceptions.
> Locks the subscription list in LogEventManager for threadsafety

- go/host/events/logs.go
> Uses a write lock instead of a read lock.

- go/enclave/bridge/bridge.go
- go/enclave/core/rollup.go
- go/enclave/crypto/crypto.go
- go/enclave/db/rawdb/accessors_indexes.go
- go/enclave/db/sql/edgelessdb.go
- go/enclave/db/sql/sql.go
- go/enclave/db/sql/sql_test.go
- go/enclave/db/sql/sqlite.go
- go/enclave/evm/chain_context.go
- go/enclave/evm/evm_facade.go
- go/enclave/evm/no_op_engine.go
- go/enclave/evm/utils.go
- go/enclave/rollupchain/rollup_chain.go
The enclave is sometimes crashing with segmentation faults which are hard to debug.
One theory is that these are caused by panics.
- Remove panics thrown during the enclave runtime, and replace them with `logger.Crit`, which logs and exits
- in some methods return an error, which is handled in the caller
> Replace panics with logger.Crit in the enclave

- go/common/host/host.go
- go/common/types.go
- go/enclave/enclave.go
- go/host/host.go
- go/host/p2p/p2p.go
- go/host/rpc/clientapi/client_api_eth.go
- integration/simulation/p2p/mock_l2_network.go
We are now producing batches alongside rollups, but they're not being distributed or stored.
- Stores the batch on the sequencer
- Distributes the batch to all other nodes
- Stores the batches on the other nodes
> Distribute and store batches

- README.md
- testnet/start-obscuroscan.sh
- testnet/testnet-local-build_images.sh
- Adds the build of the obscuroscan image into the local testnet build, provides a script to start up obscuroscan locally, and updates the readme accordingly. 
- The top level readme, and build and runs script in the testnet folder
> Allow obcuroscan to be run against a local testnet

- go/enclave/evm/evm_facade.go
Removing the trace logger so that performance of the obscuro nodes is not handicapped. 
Removed the trace logger.
> Remove geth EVM trace logger.

- go/host/db/batches.go
- go/host/db/hostdb.go
- go/host/db/rollups.go
- go/host/rpc/clientapi/client_api_eth.go
- integration/noderunner/noderunner_test.go
- integration/simulation/validate_chain.go
> eth_getBlockByNumber and eth_getBlockByHash responds based on the batches, not the rollups

- go/ethadapter/geth_rpc_client.go
- We were using the context timeouts as the max time before giving up so gave up after 10-15s instead of a longer period
- This should help us reconnect if there are L1 "blips" but won't help with recovery for more serious issues
- Fix timeout
> Set correct timeout for giving up on L1 reconnection

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_attestation.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/accessors_metadata.go
- go/enclave/db/rawdb/accessors_receipts.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
The enclave DB swallows a lot of errors, and uses a critical logger message for others. For resilience, we should return errors and handle those.
This is just the first step - there's too much to change to do it all in one PR.
> Return errors from enclave DB, instead of ignoring or using a critical log message

- go/host/rpc/clientapi/client_api_obscuroscan.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network.go
- integration/simulation/network/socket.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/simulation/validate_chain.go
We need integration tests of the Obscuroscan APIs to stop Obscuroscan from breaking silently.
> Adds integration test of getTotalTxs.

- docs/_docs/api/sensitive-apis.md
- docs/_docs/community/contributions.md
- docs/_docs/testnet/Introduction.md
- docs/_docs/testnet/changelog.md
- docs/_docs/testnet/deploying-a-smart-contract-programmatically.md
- docs/_docs/testnet/deploying-a-smart-contract.md
- docs/_docs/testnet/example-dapps.md
- docs/_docs/testnet/faucet.md
- docs/_docs/testnet/tutorial.md
- docs/_docs/wallet-extension/wallet-extension.md
- Some of the docs pages were pointing to .html pages however when the docs search fix was applied all md files lost their .html suffix when the html pages are constructed by Jekyll
- links embedded in the md files with .html have ".html" removed from the URL
- reference links replaced with FQDN links
> Fix dead links in docs

- go/host/db/batches.go
- go/host/host.go
- go/host/rpc/clientapi/client_api_obscuroscan.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/simulation/transaction_injector.go
- integration/simulation/validate_chain.go
There is an issue with getLatestTxs. It appears to be in how we were creating the batches - we were adding them to the DB in `storeBlockProcessingResult`, meaning that nodes were creating them based on the L1 blocks, as well as getting them via a P2P mechanism from the host.
> Test Obscuroscan's getLatestTxs in integration tests

- .github/workflows/manual-deploy-dev-obscuroscan.yml
- Adds a github action to deploy obscuroscan into dev-testnet
> Add file to deploy obscuroscan into dev-testnet

- .github/workflows/manual-deploy-obscuroscan.yml
- Provides consistency in the naming of deploying obscuroscan.
> Rename Testnet Obscuroscan workflow to be consistent

- .golangci.yml
Avoids this spew:
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
> Removes dead linteres to remove noise.

- go/common/errutil/errors_util.go
Currently, we use a lot of Ethereum components. Some of these may be throwing out their own `ethereum.NotFound` errors which we are failing to convert to `errutil.ErrNotFound`. This is a potential source of bugs, as we may have an `errutil.ErrNotFound` check that misses an unconverted `ethereum.NotFound` error.
> Make our ErrNotFound match Ethereum's

- go/common/profiler/profiler.go
The current impl of the profiler doesn't cause any linting issues on the version of golangci-lint used in CI, but it does on more recent versions. This change avoids that linting issue.
> Profiler - address gosec warning on new versions of golangci-lint

- go/ethadapter/blockprovider.go
- go/ethadapter/blockprovider_test.go
- Blockprovider manages a goroutine that is responsible for streaming out the blocks to its client
- When client requests a new stream the old stream dies and the process is restarted with a clean stream channel
- There were bugs with the goroutine controlling mechanism in block provider
- And it was confusing to understand
- Replace the atomic status changes to use a context-based approach to stopping the streaming goroutine
> simplify blockprovider process control to use context

- go/common/host/host.go
- go/enclave/events/subscription_manager.go
- go/ethadapter/blockprovider.go
- go/ethadapter/blockprovider_test.go
- go/host/host.go
- integration/common/testlog/testlog.go
- integration/ethereummock/mock_l1_network.go
- integration/ethereummock/node.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/p2p/mock_l2_network.go
BlockProvider interface allows caller to stream canonical L1 blocks consecutively without having to worry about:
* whether it is live streaming or catching-up
* recovering from disconnects
* getting missed blocks after a fork
The motivation for switching to it is:
- BlockProvider interface allows caller to stream from a certain block hash or height. It will allow us to start streaming from the mgmt contract deployment block instead of L1 genesis once we have configured that.
- `host.go` has too many responsibilities, this separation will reduce the code complexity in there
- Update the host main loop to pull blocks from block provider
- Get rid of the `bootstrap` code. The main loop works in catch-up/bootstrap situations as well as in the live streaming happy mode
- Get rid of the …
> Use block provider as source of L1 blocks in host

- go/common/host/host.go
- go/enclave/events/subscription_manager.go
- go/ethadapter/blockprovider.go
- go/ethadapter/blockprovider_test.go
- go/host/host.go
- integration/ethereummock/mock_l1_network.go
- integration/ethereummock/node.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/p2p/mock_l2_network.go
This reverts commit 2e59cdbd1ece8e624fcb2d45fd37e0da29d726f7.
- Seems to be causing test failures intermittently, don't want to slow the team down so will fix it and re-raise
> Revert "Use block provider as source of L1 blocks in host (#891)"

- go/common/batches.go
- go/common/host/host.go
- go/common/types.go
- go/host/batchmanager/batch_manager.go
- go/host/db/batches.go
- go/host/host.go
- go/host/p2p/p2p.go
- integration/simulation/p2p/mock_l2_network.go
- integration/simulation/validate_chain.go
A node can easily miss batches, e.g. due to a network issue, or because they started up late. This PR introduces a catch-up mechanism.
The idea is that when you receive a batch, you check whether you have it's full history. If you are missing any historical batches, you discard the batch and ask the sequencer to send over all the batches up to and including this new batch.
> Allow hosts to catch up on missed batches

- go/host/p2p/p2p.go
-If batches are getting processed before peers list has been updated (or peers list becomes empty for any reason) we don't want to see panics like this:
```
panic: runtime error: index out of range [0] with length 0
goroutine 313 [running]:
github.com/obscuronet/go-obscuro/go/host/p2p.(*p2pImpl).RequestBatches(0xc00048c780, 0xc0010a64a0?)
/Users/joeldudley/Desktop/go-obscuro/go/host/p2p/p2p.go:116 +0xb0
```
The nature of the batch catch-up (batchup, if you will) is that it will recover later on if and when peers are available.
The reason this becomes an issue after my PR is that we jump straight into the main loop and we want to be resilient for the inputs for whatever state the host is in.
> Log error if no peers list yet to send batch request to

- go/common/enclave.go
- go/common/rpc/converters.go
- go/common/rpc/generated/enclave.pb.go
- go/common/rpc/generated/enclave.proto
- go/common/rpc/generated/enclave_grpc.pb.go
- go/enclave/db/interfaces.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/rollupchain/rollup_chain.go
- go/enclave/rpc_server.go
- go/host/host.go
- go/host/rpc/enclaverpc/enclave_client.go
There is now a separate API to produce rollups, instead of one being automatically produced for each block ingested. This will support the unlinking of rollup and batch production from block production.
> Unlink production of rollups from submission of L1 blocks

- go/common/gethdb/geth_inmemdb.go
- go/host/db/batches.go
- go/host/db/blocks.go
- go/host/db/hostdb.go
- go/host/db/rollups.go
- https://github.com/obscuronet/obscuro-internal/issues/1208
- memorydb in geth returns a string error instead of a typed one. It messes with our db usage. This normalizes the error usage.
> Has-Get pattern in the db fix

- go/common/enclave.go
- go/common/host/host.go
- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
- go/ethadapter/blockprovider.go
- go/ethadapter/blockprovider_test.go
- go/host/host.go
- integration/ethereummock/mock_l1_network.go
- integration/ethereummock/node.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/p2p/mock_l2_network.go
Note: again, the first commit here is the commit from the other day which integrates block provider into the host for all block feeding (@tudor-malene reviewed). Only the small second commit here is a completely new change.
- Fix the block error loops in a lighter touch way than that PR from yesterday
- We're still figuring out the nuance of enclave state re: blocks/rollups/batches, I don't want to muddy the water there
- This change means it won't get stuck in a loop, the stream is allowed to continue if the enclave complains about a duplicate block with the view that it's probably just one or two duplicate blocks to get it back on track, respecting the L1Head info it provided already
- move standard submit block errors to common as they are part of the interface
- check for duplicate …
> Fix fork block loop and re-merge blockprovider PR

- go/config/host_config.go
- go/ethadapter/blockprovider.go
- go/host/host.go
- go/host/hostrunner/cli.go
- go/host/hostrunner/cli_flags.go
- integration/simulation/network/geth_network.go
- integration/simulation/network/geth_utils.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
- integration/simulation/params/params.go
- integration/simulation/simulation.go
- integration/simulation/simulation_in_mem_test.go
- integration/simulation/simulation_tester.go
- integration/smartcontract/smartcontracts_test.go
- tools/networkmanager/deploy_contract.go
- To deploy Obscuro to a long-running L1 we want to be able to specify where in that network the nodes need to start tracking from
- No need to start tracking before mgmt contract deployed
- add host config param for L1StartHash
- use that param to start the block provider streaming in the main loop
- fallback to streaming from start of the L1 if that fails/if no hash provided (this change won't break testnets that are missing the arg)
- combined the start hash with the contract addresses in a L1SetupData struct, don't feel strongly about the name :)
> Allow L1 start block to be configured to avoid all L1 history

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- Puts back the change to point RPC traffic to node 1.
> Testnet DNS now point to node1

- integration/ethereummock/node.go
- Joel noticed he'd occasionally hit concurrent map errors like:
```
fatal error: concurrent map iteration and map write
goroutine 45 [running]:
github.com/obscuronet/go-obscuro/integration/ethereummock.(*Node).setHead(0xc0002e4700, 0xc027a2ab40)
/Users/joeldudley/Desktop/go-obscuro/integration/ethereummock/node.go:273 +0xa9
github.com/obscuronet/go-obscuro/integration/ethereummock.(*Node).processBlock(0xc0002e4700, 0xc027a2ab40, 0xc033aed710)
/Users/joeldudley/Desktop/go-obscuro/integration/ethereummock/node.go:263 +0x26f
github.com/obscuronet/go-obscuro/integration/ethereummock.(*Node).Start(0xc0002e4700)
/Users/joeldudley/Desktop/go-obscuro/integration/ethereummock/node.go:199 +0x25a
created by github.com/obscuronet/go-obscuro/integration/simulation/network.(*basicNetworkOfInMemoryNodes …
```
> Fix in-mem mock concurrency bug

- .github/workflows/on-merged-pr.yml
It looks like the POST has invalid format which I assume is that the string owner should have quotes. This adds quotes into the command. 
```
Run curl -XPOST -H "Authorization: ***" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/obscuronet/obscuro-test/dispatches --data '{ "event_type": "merged_pull_request", "client_payload": { "number": 931, "owner": otherview } }'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   2[4](https://github.com/obscuronet/go-obscuro/actions/runs/3619600243/jobs/6100836138#step:2:5) …
```
> Quote the owner in the json

- go/enclave/core/egoutils/egoutils.go
We have to seal the enclave secrets using keys that are unique to the measurement of the enclave.
- Use `ecrypto.SealWithUniqueKey`
> Fix security issue. Seal secrets with the unique sgx key

- go/enclave/container/enclave_container.go
- go/enclave/main/main.go
- go/host/container/host_container.go
- go/host/main/main.go
- integration/noderunner/noderunner_test.go
- For test use-cases we need to be able to start the containers with our own logger and potentially mocked out dependencies for the host
- Need this for the testing I'm doing on enclave/host restarts
- Note: this isn't super elegant but they're only used by tests
- Rename `NewXXXContainer` to `NewXXXContainerFromConfig` for the methods used by `main`s to initialise the servers
- Create a separate constructor that allows dependencies to be passed in (e.g. pass in the logger instead of constructing it based on config
> Separate DI constructor for container in testing

- go/enclave/core/rollup.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/enclave_test.go
- go/enclave/rollupchain/rollup_chain.go
RollupChain should only be responsible for managing the L1 and L2 state, and not producing the block submission response for clients.
> Produce block submission response outside of RollupChain; some cleanup

- go/common/gethutil/gethutil.go
- go/common/types.go
- go/enclave/bridge/bridge.go
- go/enclave/crosschain/message_bus_manager.go
- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/accessors_metadata.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/enclave_test.go
- go/enclave/events/subscription_manager.go
- go/enclave/mempool/manager.go
- go/enclave/rollupchain/rollup_chain.go
- integration/ethereummock/db.go
- integration/ethereummock/mock_l1_network.go
- integration/ethereummock/node.go
- integration/ethereummock/utils.go
The enclave storage had too many methods. Some of these were confusing (e.g. the various "get L2 head" methods), some weren't required (e.g. special treatment of the genesis block), and some were pointless utilities (e.g. `ParentRollup(rollup)`, when you can just call `FetchRollup(rollup.Head.ParentHash`). By shrinking the API, it becomes simpler to reason about what the enclave's storage layer is doing.
> Clean up enclave storage

- README.md
- tools/walletextension/README.md
Old link leads to 404. https://docs.obscu.ro/wallet-extension/wallet-extension/ seems to work.
> Fixed broken link.

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/accessors_indexes.go
- go/enclave/db/rawdb/accessors_receipts.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/rollupchain/rollup_chain.go
We switched all the rollup storage operations over to storing batches. But we still need to store rollups, to check which batches are finalised. We introduce a storage operation to do this here.
I also took this opportunity to delete a bunch of unused `accessors_x` code.
> Reintroduce storage of rollups; store genesis rollup and rollups from blocks

- go/common/host/host.go
- go/host/host.go
- go/host/p2p/p2p.go
- integration/simulation/p2p/mock_l2_network.go
> Send transactions to sequencer, instead of broadcasting them

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/accessors_indexes.go
- go/enclave/db/rawdb/accessors_receipts.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/enclave_test.go
- go/enclave/events/subscription_manager.go
- go/enclave/rollupchain/rollup_chain.go
> Check that rollups processed from L1 blocks are sequential

- go/host/p2p/p2p.go
- go/host/p2p/ttl_map.go
- couple of lint failures got through to main somehow
- lint failures (comment spelling etc.)
The run takes approximately 20 minutes and any failure will be reported in the workflow output. Should the …
> Fix main build errors

- .github/workflows/build-pr.yml
- go/obsclient/authclient.go
- integration/simulation/transaction_injector.go
- https://github.com/obscuronet/obscuro-internal/issues/1284 …
> Tx Injector L1 Deposits are estimated

- go/common/batches.go
- go/common/headers.go
- go/common/rollups.go
- go/common/rpc/converters.go
- go/enclave/core/batch.go
- go/enclave/core/rollup.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/enclave.go
- go/enclave/enclave_test.go
- go/enclave/evm/chain_context.go
- go/enclave/evm/evm_facade.go
- go/enclave/evm/utils.go
- go/enclave/rollupchain/rollup_chain.go
- go/host/db/batches.go
- go/host/db/batches_test.go
- go/host/db/blocks_test.go
- go/host/rpc/clientapi/client_api_eth.go
- go/obsclient/obsclient.go
- integration/datagenerator/batch.go
- integration/datagenerator/rollup.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- integration/simulation/utils.go
- integration/simulation/validate_chain.go
- tools/obscuroscan/obscuroscan_test.go
> Create two separate header structs for batch and rollup

- go/common/retry/retry.go
- go/common/retry/retry_test.go
- integration/common/utils.go
- A couple of situations have come up where it would be useful to be able to exit from a retry mechanism
- One is implemented in this PR, when awaiting receipt we want to retry for "not found" but bail out for other errors (to avoid sitting there for a minute if we can't connect to the RPC node)
- add `retry.FailFast` function that wraps an error to break out of the retry loop
- change AwaitReceipt to use it
- Go to …
> Add fast-fail mechanism to break out of retry

- go/ethadapter/blockprovider.go
- integration/simulation/network/inmemory.go
When blockprovider hits an unexpected error it had a hardcoded 1 second sleep. For some reason it's hitting a bunch of these errors in the in-mem (which has a mock L1).
But 10 blocks go by in that 1 second in the in-mem sim, this is what's causing the inefficiency failures I think. This PR which reduces the hardcoded sleep seems to improve stability (we can look at the cause of the in-mem failures separately).
The unexpected error is rarely hit in normal usage so I don't think having a shorter sleep will have an impact. We should consider adding a back-off perhaps.
- Reduce hard-coded sleep after failure for in-mem sim stability
- Increase sleep at startup to allow mock L1 to produce first block before host starts (one source of unexpected errors)
Running the end-to-end tests in the …
> Reduce sleep time after unexpected block provider error

- go/common/retry/retry.go
- go/host/batchmanager/batch_manager.go
- go/host/host.go
> Fixes two bugs in batch catchup

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- go/enclave/rollupchain/rollup_chain.go
- testnet/docker-compose.debug.yml
- testnet/docker-compose.dev-testnet.yml
- testnet/docker-compose.non-sgx.yml
- testnet/docker-compose.yml
- testnet/start-obscuro-node.sh
> Hooks SequencerId flag

- go/common/enclave.go
- There is a bug in the L1 catch-up mechanism, we get stuck in a loop where the enclave is complaining of a block it's already seen and the host sends it the same one again
- This piece of code in `host.go` was supposed to prevent that bug by continuing to stream when it complains of duplicate block:
This piece of code didn't work because the `errors.Is()` was misreporting the error as *not* being an ErrBlockAlreadyProcessed. Because it lost its type when it was sent over the wire on RPC response
So we extend the blockRejErr.As() implementation to check for matching strings (which works for our standard errors).
- Have err.As() check string message as well as err type for the block reject error.
I have checked and this fixed the issue. After restarting the enclave and one case of the dup …
> Add Is() support to blockRejectErr for standard errors

- testnet/docker-compose.dev-testnet.yml
- testnet/docker-compose.yml
- From https://github.com/edgelesssys/edgelessdb/pull/129 …
> updates the sgx folder to match the edgelessdb usage

- go/enclave/rollupchain/rollup_chain.go
- Validation was failing for the genesis rollup (and then every subsequent rollup because the genesis was missing)
- The cause was that the rollup didn't include the address of the producing node (the sequencer address), instead a 0x0 address was set.
- Fix the genesis rollup agg field
Before the change I see `could not process rollups` appear repeatedly in the logs from the full network sim test, after the change that message does not appear.
- Go …
> Genesis rollup `Agg` field should be the sequencer that produces it

- go/enclave/rollupchain/rollup_chain.go
- go/host/host.go
- Validators require the initialise secret attestation from the sequencer to be able to validate rollups
- We see errors on simulations from genesis rollup getting processed before the attestation has arrived (and once the genesis rollup is missed, all rollup processing will fail for that node)
- Make some L1 transactions at initialisation block until successful receipt returned to guarantee they're published before entering main loop
On `main` I see errors like this reliably in the full network sim logs:
```
ERROR[12-21|09:21:19.007] could not process rollups                cmp=test_log          node_id=0 cmp=enclave           err="rollup signature was invalid. Cause: could not retrieve attested key for aggregator 0x0000000000000000000000000000000000000000. Cause: could not retrieve …
```
> Fix timing issue with sequencer secret

- go/common/metrics/metrics.go
- Host now collects metrics on the process / system
The run takes approximately 20 minutes and any failure will be reported in the workflow output. Should …
> Adds Process Collection Metrics

- docs/_docs/testnet/faucet.md
- In the temp absence of the Discord faucet bot we need to provide information on users on how to obtain OBX - this can be achieved by issuing a curl command directly to the faucet server. 
- Section on using the testnet token faucet.
> Use a curl command to request OBX

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- testnet/start-obscuro-node.sh
- The testnets are failing to start because GH can't find the sequencer ID var
- Add `secrets.` prefix to the variable used for seq ID in GH actions testnet scripts
The run takes approximately 20 minutes …
> Change sequencer ID var to read from GH secrets

- dockerfiles/enclave.Dockerfile
- dockerfiles/enclave.debug.Dockerfile
- dockerfiles/host.Dockerfile
- dockerfiles/plain_go_enclave_local.Dockerfile
- docs/_docs/testnet/starting-a-node.md
- go/enclave/main/entry.sh
- testnet/docker-compose.debug.yml
- testnet/docker-compose.dev-testnet.yml
- testnet/docker-compose.non-sgx.yml
- testnet/docker-compose.yml
- testnet/start-obscuro-node.sh
- https://github.com/obscuronet/obscuro-internal/issues/1273
- In Alibabaclound the PCCS must be specified as the default values don't work.
- Fixed docker-compose env var ingestion ( it was failing to load variables that were not immediately used in the entry command of the container)
- Enclave now starts with an` entry.sh` so it can handle the PCCS address ( needed for ali baba and if you have a custom remote attestation url)
- Enclave is no longer running under docker privileged mode ( changed to used devices like sugested by the edgeless systems )
- Remove the entry point in the docker files as it's misleading that the image may run without any flags
Running the end-to-end tests in the [obscuro-test …
> Updates PCCS URL for edgelessdb + ego

- go/host/container/host_container.go
- go/host/host.go
- go/host/rpc/clientrpc/rpc_server.go
- integration/noderunner/noderunner_test.go
- integration/simulation/network/network_utils.go
- Host now receives an RPC server from the Host Container …
> RPC server is injected into the Host

- go/common/enclave.go
- go/common/rpc/generated/enclave.proto
- go/enclave/enclave.go
- go/enclave/rpc_server.go
- go/host/rpc/enclaverpc/enclave_client.go
- This method originally existed to tell enclave to start doing speculative execution but its lifecycle doesn't require that prompt (and it's not relevant anymore).
- Enclave starts up -> self-heals if its persistence is in a bad state -> starts processing RPC requests from host
- Remove enclave's unused `Start()` method
- Click the "Run …
> Remove unnecessary start method from enclave interface

- testnet/docker-compose.dev-testnet.yml
- testnet/docker-compose.yml
> Locks EDB version for the obscuro node

- go/host/container/host_container.go
- go/host/host.go
- go/host/rpc/clientapi/client_api_obscurotest.go
- integration/simulation/network/network_utils.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/network/socket.go
- integration/simulation/p2p/in_mem_obscuro_client.go
- tools/walletextension/test/utils.go
- Decouples the Host and the RPC server into the Container Layer
- Starting a network of Socket type container hosts now checks the Health Endpoint before returning
- Run the …
> Decouples Host and RPC server

- .github/workflows/manual-deploy-dev-obscuroscan.yml
- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-obscuroscan.yml
- .github/workflows/manual-deploy-testnet-l1.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- As per title, stops using a secret for the registry name …
> Uses known registry address

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/runner-scripts/wait-node-healthy.sh
- CI now wait for the sequencer to healthy before proceeding
- https://github.com/obscuronet/obscuro-internal/issues/1307
The run takes approximately 20 …
> Deployments wait until node 0 is healthy

- .github/workflows/manual-deploy-testnet-l2.yml
- go/enclave/genesis/testnet_genesis.go
- As per title
The run takes approximately 20 minutes and any failure will be reported in the workflow output. Should the tests fail 
the docker container …
> Testnet Genesis prefunded with 7500000000000000000000000000000 OBS

- go/obsclient/authclient.go
- integration/simulation/transaction_injector.go
- integration/simulation/transaction_injector_tracker.go
- integration/simulation/validate_chain.go
- tools/networkmanager/inject_txs.go
- https://github.com/obscuronet/obscuro-internal/issues/1294 …
> Adds native transfers to the tx injector

- .github/workflows/manual-deploy-testnet-l2.yml
> Fixes deployment names

- .github/workflows/hardhat-pr-check.yml
as per - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
The run takes approximately 20 minutes and any failure …
> Changed runner from self hosted to ubuntu.

- .github/workflows/manual-deploy-dev-testnet.yml
- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/runner-scripts/wait-node-healthy.sh
- testnet/docker-compose.dev-testnet.yml
- testnet/docker-compose.yml
- https://github.com/obscuronet/obscuro-internal/issues/1332 …
> Testnet metrics are pushed to datadog

- .github/workflows/manual-deploy-obscuroscan.yml
- https://github.com/obscuronet/obscuro-internal/issues/1341 …
> ObscuroScan now deploys manually

- go/common/utils.go
- go/enclave/core/rollup.go
- go/enclave/rollupchain/rollup_chain.go
- go/host/host.go
Improve validation of rollups in a block, including checking them against batches.
This PR does _not_ handle the case where a rollup is received before the batch required to validate it. For now, an error is logged. This work will be done in a follow-up.
- Use …
> Improved validation of incoming rollups

- go/common/host/host.go
- go/enclave/container/enclave_container.go
- go/host/container/host_container.go
- go/host/host.go
- go/host/rpc/clientrpc/rpc_server.go
- integration/simulation/network/inmemory.go
- integration/simulation/network/obscuro_node_utils.go
- https://github.com/obscuronet/obscuro-internal/issues/1315 …
> Propagates container start error

- contracts/deployment_scripts/layer2/001_deploy_tokens.ts
- contracts/hardhat.config.ts
- contracts/tasks/obscuro-deploy.ts
- go/enclave/genesis/genesis_test.go
- go/enclave/genesis/testnet_genesis.go
- testnet/testnet-deploy-l2-contracts.sh
Replicating the current deployment that the contrat deployer produces using the new hardhat deployer. ERC20 contract addresses do not match.
The run takes …
> Added layer 2 deployment and updated bits around it.

- go/enclave/events/subscription_manager.go
- go/host/rpc/clientapi/client_api_filter.go
- go/rpc/encrypted_client.go
Adds comments to clarify some of the log events logic. …
> Adds comments to clarify some of the log events logic.

- go/common/batches.go
- go/common/headers.go
- go/common/rollups.go
- go/enclave/enclave.go
- go/enclave/rollupchain/rollup_chain.go
> Requires the full set of batches to be specified when creating a rollup from a set of batches

- go/host/host.go
> Adds todo to handle failure to publish rollup to L1

- contracts/README.md
- contracts/hardhat.config.ts
- contracts/package.json
- contracts/src/management/ManagementContract.sol
https://github.com/obscuronet/obscuro-internal/issues/1360 …
> Fix solidity compilation warnings for unused calldata. Warnings are now treated as errors.

- go/enclave/enclave.go
- go/enclave/l2chain/README.md
- go/enclave/l2chain/chain_test.go
- go/enclave/l2chain/l1_blockchain.go
- go/enclave/l2chain/l2_chain.go
- go/enclave/rollupchain/rollup_chain.go
> Store batches from rollups. Check batches at same height are consistent.

- go/enclave/core/egoutils/egoutils.go
- go/enclave/db/sql/edgelessdb.go
- While we continue developing the upgrade process for nodes in production we need a solution that allows testnet nodes to be upgraded without losing access to their state
- Sealing the EDB credentials with the enclave product key rather than the enclave unique ID provides some security but a determined attacker with insider access would be able to access the secrets so this is solely a stop-gap solution for testnet
- A task has been created here https://github.com/obscuronet/obscuro-internal/issues/1377 with todos in the code that point to that to ensure this doesn't get left in
- Change the code to seal EDB credentials with product key rather than unique ID
- Make it clear with the code and the todo comments that this is a temporary solution that will be rectified before mainnet
Running …
> Temporarily allow product key sealing of EDB credentials

- go/enclave/enclave.go
- go/enclave/l2chain/l2_chain.go
- go/host/host.go
> No need to manage a mempool on non-sequencer nodes

- dockerfiles/enclave.Dockerfile
- dockerfiles/host.Dockerfile
> Docker image size reduction

- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/l2chain/l2_chain.go
- Currently the enclave's view on what is the head of the L2 chain is determined by the head of the L1 chain and the mappings from L1 block -> head L2 hash for that block.
- This is a relic from the POBI design and no longer needed
- It makes it hard to rewind the head to rebuild state after recovering from an ungraceful shutdown
- Note: this change does not get rid of the mapping which is a tricker thread to pull at, it just stops treating it as the source of truth for current head of L2 chain
- Add new DB entry for the batch hash at the head of the L2 chain
discretion of the developer prior to merging a PR. The intention is not to slow down development by having the …
> Store the L2 head hash directly in the enclave

- .github/workflows/manual-deploy-testnet-l2.yml
- https://github.com/obscuronet/obscuro-internal/issues/1374 …
> Fix faucet deployment trigger

- testnet/start-obscuro-node.sh
- https://github.com/obscuronet/obscuro-internal/issues/1368 …
> Remove early exit

- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/manual-upgrade-testnet-l2.yml
- dockerfiles/enclave.Dockerfile
> Fixes the enclave start

- .github/workflows/manual-upgrade-testnet-l2.yml
> Upgrade enclave l2

- pull_request_template.md
- Make the PR template lighter with a link to the underlying checks required
> Make PR template lighter

- go/enclave/db/storage.go
- Keep meaning to rename these, it's very confusing to have `batch` meaning L2 batches and `batch` mean DB atomic transactions block being used in the same methods.
- Rename `batch` -> `dbBatch` where appropriate
- Run the …
> Call DB client batches dbBatches to avoid confusion

- go/ethadapter/blockprovider.go
- go/ethadapter/geth_rpc_client.go
There was an issue with the L1 block provider on testnet and useful information wasn't being logged that might have helped understand the issue.
Don't swallow errors returned by L1 client when logging
> Avoid swallowing L1 client error messages

- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/l2chain/l2_chain.go
After an enclave is restarted if the stateDB cache wasn't fully flushed then it fails to process batches because it can't find previous stateDB to build onto.
Ethereum has this problem too, when its node starts it moves its head backwards until it finds a block with stateDB cache intact then replays forwards. We do something similar here.
After starting up an enclave, if there is a head batch in the DB then it makes sure it has stateDB for that batch.
If not it steps backwards along the batch-chain, building up a list of batches to replay until it reaches genesis or finds a batch with existing stateDB.
Then it steps forwards through the list of batches and processes their transactions again to restore the stateDB caches.
Please indicate below by ticking the checkbox that you have read and …
> After enclave restart, replay batches to restore missing stateDB cache

- go/enclave/l2chain/l2_chain.go
We were sometimes seeing failures before rollups were published where the rollup lookup would try to go back to genesis but it would run out of L1 blocks because the enclave didn't start from genesis, it started from the mgmt contract deployment block.
Return rollup not found when the L1 blocks run out.
> Rollup lookup should not assume that L1 blocks go back to genesis

- tools/walletextension/test/utils.go
- tools/walletextension/test/wallet_extension_test.go
Fixes the port management in the tests which lead to flaky fails.
Also fixes the messages that would kill the logs in the CI
```
ERROR[02-07|15:20:41.572] could not read request: websocket: close 1006 (abnormal closure): unexpected EOF cmp=wallet_extension
ERROR[02-07|15:20:41.572] could not write error message to websocket cmp=wallet_extension err="write tcp 127.0.0.1:40001->127.0.0.1:63737: write: broken pipe"
```
> Fix wallet extension flakyness

- .github/workflows/manual-deploy-testnet-l2.yml
We are seeing AZ failures fairly often when deploying testnets, seems to be caused by the service not dealing well with requests in quick succession (https://github.com/Azure/azure-cli/issues/21156). So we are staggering the node setups to avoid conflicts.
Add node_id * 30 seconds sleep to each node before VM creation.
> Add sleep to stagger AZ CLI requests on parallel node creation

- go/enclave/enclave.go
- go/enclave/l2chain/l2_chain.go
We're struggling to debug issue where network seizes up after a short time.
Add aggressive logging for L1 block processing and validator batch receipts. We can remove/thin out once we've stabilised main.
> Aggressive enclave logging to track what what it is processing

- .github/workflows/manual-deploy-testnet-l2.yml
bash snippet in https://github.com/obscuronet/go-obscuro/pull/1098 had bad syntax:
Try using double braces like the other variables lower in the script.
> Attempt to fix github sleep step bash syntax

- go/enclave/db/storage.go
Despite fix yesterday we were still seeing the enclave scan back to genesis of L1 looking for rollups. This was because of a bad comparison where it was comparing a hash pointer to a hash.
> fix bug in rollup backwards search original fix

- README.md
- testnet/testnet-local-eth2network.sh
- testnet/testnet-local-start.sh
- testnet/testnet-start.sh
- testnet/wait-eth2network-healthy.sh
Makes it easier for everyone to test starting up a local testnet if there is a single start script, e.g. that obscuro-test can call.
> Add a single start script to launch testnet with default arguments

- .github/workflows/manual-deploy-testnet-l2.yml
To capture issues with deployment into dev-testnet, and the running of the E2E tests on successful deployment.
> Implemented a 4am scheduled deployment of dev-testnet

- go/enclave/db/db.go
- go/enclave/db/sql/sqlite.go
- integration/common/utils.go
- integration/networktest/README.md
- integration/networktest/actions/context.go
- integration/networktest/actions/multiple_actions.go
- integration/networktest/actions/native_fund_actions.go
- integration/networktest/actions/node_actions.go
- integration/networktest/actions/setup_actions.go
- integration/networktest/actions/snapshot_actions.go
- integration/networktest/actions/traffic_actions.go
- integration/networktest/actions/util_actions.go
- integration/networktest/env/dev_network.go
- integration/networktest/env/network_setup.go
- integration/networktest/env/testnet.go
- integration/networktest/interfaces.go
- integration/networktest/log.go
- integration/networktest/runner.go
- integration/networktest/tests/helpful/smoke_test.go
- integration/networktest/tests/helpful/spin_up_local_network_test.go
- integration/networktest/tests/load/load_test.go
- integration/networktest/tests/nodescenario/restart_validator_enclave_test.go
- integration/networktest/userwallet/userwallet.go
- integration/networktest/util.go
- integration/simulation/devnetwork/config.go
- integration/simulation/devnetwork/dev_network.go
- integration/simulation/devnetwork/geth_l1.go
- integration/simulation/devnetwork/l1_network.go
- integration/simulation/devnetwork/node.go
Note: this is a continuation of this PR: https://github.com/obscuronet/go-obscuro/pull/1039 . Fresh branch for the refactor because there was a lot of old comments on there.
The main difference is just swapping out the NetworkTest interface for the more flexible Action interface that Tudor suggested in a comment. So now the tests read more like a series of steps which I think is perhaps what Stefan had in mind too.
I haven't attempted to make this integrate with hardhat stuff or with Pedro's docker-based local network stuff yet but hopefully this is flexible enough that we can use it with that stuff without too much hassle.
- Adds a tool that can be used for testing network situations against a local dev network in-memory or one of our existing testnets
- Adds a test for restarting the …
> Add integration testing and local network tools

- go/enclave/enclave.go
Spammy log is missing one of the most helpful parts (the new batch details) because it's getting overwritten by the rollup msg)
fix the log msg
> New batch log msg getting overwritten

- .github/workflows/manual-deploy-testnet-l2.yml
- testnet/launcher/l1contractdeployer/docker.go
On failure of the L1 or L2 contract deployment, extract and uploads the container logs as build artifacts so we can diagnose from the action UI.
> Save deployment container logs as build artifacts for fault finding

- go/host/db/batches.go
- go/host/db/blocks.go
- go/host/db/hostdb.go
- go/host/db/leveldb.go
Follow-up to yesterday's PR adding persistence to host
Wrap levelDB with thin wrapper that returns our own errNotFound
> Wrap levelDB so its error types don't leak into our codebase

- .github/workflows/manual-deploy-testnet-l1.yml
- .github/workflows/manual-deploy-testnet-l2.yml
We need to schedule L1 deployment followed by L2, rather than just doing an L2 deployment nightly. This adds a schedule trigger to L1 to deploy into dev-testnet, and if successul it will send a repository dispatch to perform the L2 deployment.
> Run a schedule deploy on the L1, and trigger L2 if succesful

- .github/workflows/manual-deploy-testnet-l2.yml
When a nightly deployment is complete we want the trigger to the faucet deployment to be a repository dispatch, so we can use the faucet to trigger the end to end tests
> Trigger a repository dispatch to the faucet

- .github/workflows/build-pr.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/manual-deploy-testnet-l2.yml
Seeing weird lint failures, noticed go version was older than repo, thought I'd update in case it's relevant.
Edit: also had to set `skip-go-installation: true` flag on the lint step to stop the weird failures.
> Update the go versions on actions to match the repo version

- integration/networktest/actions/node_actions.go
- integration/networktest/actions/setup_actions.go
- integration/networktest/actions/snapshot_actions.go
- integration/networktest/actions/util_actions.go
- integration/networktest/env/network_setup.go
- integration/networktest/env/testnet.go
- integration/networktest/interfaces.go
- integration/networktest/tests/helpful/l1_test.go
- integration/simulation/devnetwork/dev_network.go
- add L1 client to network connector interface (we'll need that to test bridging etc. with L1 transactions)
- add basic liveness test for L1 so we can quickly verify when the L1 is up for testnets
- rename the 'RunOnly' test action so it's more obvious and consistent with the VerifyOnly
> Add basic L1 sanity check to networktests tools

- .github/workflows/manual-upgrade-testnet-l2.yml
We changed the node start github action script to use DOCKER_BUILDKIT but the upgrade script wasn't updated and failed with a buildkit missing error.
It got further after this change (something else going wrong now).
Copy the build kit script changes from the testnet deploy action script.
> Add buildkit to docker update step

- tools/walletextension/main/cli.go
- tools/walletextension/main/main.go
- tools/walletextension/wallet_extension.go
Want to understand metamask traffic behaviour for debugging purposes
- add `--verbose` boolean flag
- set logger to debug if true
- add debug log message on receiving each request.
> Wallet extension verbose logging

- go/node/docker.go
At some point the enclave logs on testnet were set above INFO and we started losing visibility of the goings on.
We should continue to reduce logs where possible by selectively downgrading and removing log messages. If we still feel there are too many logs then perhaps we set testnet to WARN but keep dev testnet at INFO level.
Change default log levels to be human readable and set to INFO in the testnet docker launch script.
> Set host and enclave loggers to INFO by default

- go/node/docker.go
https://github.com/obscuronet/go-obscuro/pull/1149 introduced a bug, because of Go magic it was outputting a human readable string instead of the int value for the log level.
So the node start script was failing with `-logLvl info` argument when it expected `-logLvl 4`
This fixes that (verified by starting the nodes on dev testnet).
> Fix logLvl arg format in testnet script

- go/common/docker/docker.go
- go/node/docker.go
- testnet/launcher/eth2network/docker.go
- testnet/launcher/l1contractdeployer/docker.go
- testnet/launcher/l2contractdeployer/docker.go
Currently testnet hosts use in-memory state but it'd be better for upgrades if they use a local db
- Change the docker launcher script to support docker volumes
- make sure the host-persistence volume is there for testnet hosts
> Enable persistence on testnet hosts

- go/common/host/host.go
- go/enclave/l2chain/l2_chain.go
- go/ethadapter/blockprovider.go
- go/host/host.go
- Make the enclave logging a bit clearer
- Provide visibility on how far behind of L1 head we are
- Loosen `isLatest` to be "within 1 block of current head" since it's just a best-effort measure anyway (validators have no idea if sequencer had received the latest L1 block they've seen yet) - this change probably makes no difference in practice, especially when we decouple batch production
> Small logging improvements, loosen isLatest restriction

- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/manual-upgrade-testnet-l2.yml
- docs/_docs/testnet/starting-a-node.md
- go/common/docker/docker.go
- go/node/cmd/cli.go
- go/node/cmd/main.go
- go/node/docker.go
- go/node/network_config.go
- go/node/node.go
We replaced docker compose with go scripts that manage the docker containers.
The main script just starts the containers but we need to be able to upgrade existing nodes as well.
It became obvious as well that some metadata about the network is required when restarting. So now we persist network config data in a json file on the node VMs to be read when restarting/upgrading.
- add "nodeAction" argument to the main script so you can call "start" or "upgrade" (and in the future we may add things like "stop", "status")
- add network config json file to node VMs so relevant config is available for node arguments when upgrading them
[PR checks](https://github.com/obscuronet/obscuro-internal/blob/main/dev …
> Add upgrade option to node script

- go/node/config.go
- go/node/docker.go
- testnet/launcher/docker.go
Spinning up local networks was failing because we haven't catered for setting up difference persistence files for the different nodes. For now this adds the option to use in-memory db for docker host.
- add option to use in-mem DB for docker host.
- use that when launching local testnet
> Docker testnet launcher to use in-mem db for host

- testnet/launcher/docker.go
Missed that the launcher script creates the validator host config separately from the seq.
Set seq host to use in-mem db as well.
> Set sequencer host to use in-mem db as well

- docs/_docs/testnet/deploying-a-smart-contract-programmatically.md
The link to the python example for deploying smart contract programmatically was broken.
Replaced the dead link for the python example to deploy smart contract programmatically: 
Anchor Text: deploying-a-smart-contract-programmatically.py 
Broken Link: deploying-a-smart-contract-programmatically.py 
Fixed Link: https://github.com/obscuronet/go-obscuro/blob/main/docs/_docs/testnet/deploying-a-smart-contract-programmatically.py
> Fix dead links.

- go/common/retry/retry_strategy.go
- go/common/retry/retry_test.go
- go/ethadapter/blockprovider.go
- go/ethadapter/geth_rpc_client.go
Sometimes we get an unexpected error from the L1 client and the host falls over so the node operator can deal with it.
But the host should self recover when the L1 client becomes available again (this will help us understand more clearly what the L1 issues are on testnets, blips or falling over).
Add a new retry strategy that keeps trying forever, use it for L1 connection from host.
> Retry L1 reconnect indefinitely

- integration/eth2network/eth2_network.go
We want to reduce the amount of errors noise we see in the prysm logs. It is often complaining about not being able to find peers, these flags should help with that (unclear whether that will help with our L1 stability but should make it easier to see what's going on hopefully).
Use `--no-discover` flag and `--minimum-peers-per-subnet 0` for our single node network.
> Tell prysm node not to look for peers

- go/enclave/enclave.go
Addresses #527
Reusing the BlockAndReceipts struct in order to have the secret messages functionality only iterate over transactions that are considered successful.
> Process network secrets now iterates only over successful transactions.

- go.mod
- go.sum
- go/enclave/db/db.go
- go/enclave/db/rawdb/README.md
- go/enclave/db/sql/batch.go
- go/enclave/db/sql/edgelessdb.go
- go/enclave/db/sql/sql.go
- go/enclave/db/sql/sqlite.go
- go/enclave/db/storage.go
- go/enclave/genesis/genesis_test.go
This is a prerequisite to the performance improvements required for event storage.
1. Instead of using the `ethdb.Database` as the main database, we use a wrapper `EnclaveDB`, which also exposes an `sql` object which will be used to run queries directly against other tables.
2. There was some minor complexity during testing as we were using an "inMemory" database provided by geth. This is now replaced with an in-memory sqlite.
> Expose underlying sql database

- docs/_docs/testnet/obscuroscan.md
The APIs for fetching rollup & transaction details are not accessible & ready to be used by users.
Removed the 'External API Calls' section.
> Removing the External API Calls section

- go/enclave/db/interfaces.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/host/host.go
We were not shutting down the resources properly
Create a "Close" method for the enclave storage.
Implement a stopping flag for the enclave. When that is set, the enclave will no longer respond to commands.
> close database and guard enclave methods

- go/host/host.go
- integration/networktest/tests/helpful/smoke_test.go
There were flags used to manage the state/lifecycle of the host that aren't used anymore and make the code more confusing to read.
Remove unused controls.
> Remove unused host flow controls

- .github/workflows/manual-deploy-testnet-l1.yml
Allows us to run longer E2E tests over the weekend.
> Run scheduled dev-testnet deployment at 3:05am Tues to Sat

- docs/_docs/testnet/faucet.md
Puts back in to the docs the steps required to use the faucet bot to request OBX.
> Add back in the faucet steps using discord

- docs/_docs/testnet/faucet.md
Resolving images seems to be different on the built pages to that relative in the source
> Resolve image paths for faucet docs

- .github/workflows/manual-upgrade-testnet-l2.yml
When running the L2 upgrade GitHub action the hosts fail to come up with the following error:
`CRIT [03-27|09:04:07.345] could not create Ethereum client.        node_id=0x0000000000000000000000000000000000000000 component=host err="unable to connect to the eth node - dial tcp :9000: connect: connection refused"`
It failed to connect because it's got the empty string as the L1 host name. I did a diff with the L2 Deploy script and this line was missing to output the L1_HOST variable.
Make sure L1_HOST var is exported in GH upgrade script.
> L1_HOST not output properly in GH upgrade action

- go/common/batches.go
- go/common/headers.go
- go/common/rollups.go
- go/common/types.go
- go/config/host_config.go
- go/enclave/core/batch.go
- go/enclave/core/rollup.go
- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/rawdb/accessors_receipts.go
- go/enclave/db/rawdb/schema.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/enclave_test.go
- go/enclave/events/subscription_manager.go
- go/enclave/l2chain/l2_chain.go
- go/ethadapter/blockprovider_test.go
- go/ethadapter/geth_rpc_client.go
- go/ethadapter/interface.go
- go/host/db/batches.go
- integration/ethereummock/db.go
- integration/ethereummock/node.go
- integration/simulation/output_stats.go
- integration/simulation/utils.go
The aliases were not state roots, but hashes of the actual headers
rename
> fix names of types aliases

- dockerfiles/enclave.Dockerfile
- dockerfiles/enclave.debug.Dockerfile
- go/enclave/main/enclave.json
- go/node/docker.go
After upgrading the enclave couldn't find the persisted EDB credentials and was trying to reinitialise the database (which fails).
Eventually realised this is because the creds are just persisted into the enclave container which is discarded on upgrade.
This change mirrors the host persistence, a persistent docker mount on the VM that is made available into the enclave docker container.
Add enclave persistence mount and configure it into the enclave docker container and the SGX enclave within that.
> Use docker mount for enclave persistence

- .github/workflows/manual-deploy-testnet-l1.yml
Fixes small issue where the eth2network image was not being pushed
> Eth2network now pushed as part of the deploy flow

- go/common/batches.go
- go/common/rollups.go
- go/enclave/evm/evm_facade.go
- go/enclave/evm/utils.go
- go/enclave/rollupmanager/rollupmanager.go
- integration/simulation/validate_chain.go
The batch->block header conversion logic was changing the "block hash" property of receipts and logs
> fix the block hash of log messages and receipts

- .github/workflows/manual-upgrade-testnet-l2.yml
Code changes aren't getting pulled in because old docker image already exists on the VM.
Pull docker image to the VM before running upgrade script.
> Pull the updated docker images in testnet upgrade script

- go/enclave/db/storage.go
normalise the "data field" of logs to nil, to prevent "select distinct" from returning multiple rows
> normalise data field to fix event dups bug

- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_enclave_key.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
Some issues with the upgrade seem to be because the enclave key is getting regenerated every time (which makes sense). 
This change persists the enclave key and attempts to load it on startup.
> Persist enclave key

- .github/workflows/manual-deploy-testnet-l1.yml
- .github/workflows/manual-deploy-testnet-l2.yml
In the scheduled nightly dev-testnet deployments, just redeploy the L2
> Only perform the L2 deployment on a scheduled basis

- docs/_docs/wallet-extension/wallet-extension.md
The description was wrong before as new users will have 0 OBX at the beginning and faucet can be used to get funds to your account.
Changed docs.
- [ X] PR checks reviewed and performed
> Update wallet extension docs and include a link to OBX faucet

- go/common/async/README.md
- go/common/async/async.go
- go/common/utils.go
- integration/ethereummock/mock_l1_network.go
- integration/ethereummock/node.go
- integration/networktest/tests/load/load_test.go
- integration/simulation/network/obscuro_node_utils.go
- integration/simulation/p2p/mock_l2_network.go
Host is using a waitgroup for shutdown in Stefan's big PR and things keep hanging on shutdown, this feels like it might help but I didn't want to further bloat the PR with this refactor.
I found another async-related function and pulled it into the new util package as well.
> Add wait group Wait() timeout function to util

- .github/workflows/manual-deploy-testnet-l2.yml
Dev testnet deployments are consistently failing with:
```
cgo: C compiler \"gcc\" not found: exec: \"gcc\": executable file not found in $PATH
cgo: C compiler \"gcc\" not found: exec: \"gcc\": executable file not found in $PATH
cgo: C compiler \"gcc\" not found: exec: \"gcc\": executable file not found in $PATH
cgo: C compiler \"gcc\" not found: exec: \"gcc\": executable file not found in $PATH
```
I think this is because the node package which is called directly (docker launcher) now has a transitive dependency on sqlite and edgeless because of the In-Mem node we added to it.
- Install gcc as part of the prep for the launch
- make sure both nodes sleep for 1minute (this is an attempt to fix an issue where key ubuntu files were missing on the VM, maybe too soon after creation?)
Please …
> Testnet deploy: install gcc and allow time for VMs to initialise

- .github/workflows/manual-upgrade-testnet-l2.yml
Automate testnet upgrades
Use tags to do lookup on VM name, extract build number with regex
> Testnet upgrade - lookup env build number from azure VMs

- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/manual-upgrade-testnet-l2.yml
Run a schedule dev-testnet upgrade nightly, and use only repository dispatches
> Updated to run the upgrade nightly

- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/manual-upgrade-testnet-l2.yml
Fixes a syntax issue in the github workflows
> Fix syntax

- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/manual-upgrade-testnet-l2.yml
- .github/workflows/runner-scripts/wait-node-healthy.sh
Validator starts 1min after sequencer, so giving it just 1min of timeout after seq success is fragile (and regularly failing). 
Removed the 60s timeout so it defaults to 5min.
Also changed the interval to 2sec to reduce the noise.
> Testnet deploy: validator health check to 5mins

- go/host/host.go
When an error comes back from SubmitBlock that is not a blockRejectError then the host has no information on what the enclave is expecting. It should use the same block it just tried rather than moving onto the subsequent block.
Reset stream to current block rather than moving onto the next block.
> Host: retry SubmitBlock on generic errors

- go/enclave/components/batch_registry.go
- go/enclave/core/utils.go
- go/enclave/enclave.go
- go/enclave/mempool/interface.go
- go/enclave/mempool/manager.go
- go/enclave/mempool/nonce_tracker.go
- go/enclave/nodetype/sequencer.go
Sequencer needs to remove failing transactions from mempool.
Modified the logic by which the mempool determines what current transactions to give. Furthermore changed what transactions are removed from it. We no longer use the successful transactions that can be found in the batch. 
> Mempool is now using a simpler mechanism to pick transactions and wait for ones that are not ready to go in yet.

- go/node/docker_node.go
Typo meant the management contract was getting set wrong, breaking the rollup publishing.
> Node upgrade: Fix management contract config

- integration/networktest/actions/node_actions.go
- integration/networktest/tests/nodescenario/restart_network_test.go
- integration/simulation/devnetwork/dev_network.go
- integration/simulation/devnetwork/node.go
In attempt to reproduce the dev testnet issues I made a network test scenario that restarts all the nodes in the network (sequencer and validators) and makes sure it recovers.
> Network tests: Add scenario for restarting all nodes in network

- go/enclave/main/enclave.json
dev testnet failing with OOM errors.
increase heap size to 2G.
If the OOM still happens it means we have a leak
> increase ego heapSize to 2GB

- go/host/p2p/p2p.go
to prevent an inconsistent state on validators, add a simple retry to the tcp "send"
> add simple retry to p2p

- go/enclave/components/block_processor.go
The enclave should always be operating from the tip of the L1 that it knows about. So we should treat every submitted L1 block as the new head.
- Remove the isLatest gate on updating L1 head
- Minor refactor of the block ingest method
> Enclave: always update L1 head on submit block

- go/node/docker_node.go
currently, testnet dies because rollups get too big.
This issue will be fixed properly with the introduction of the limiter.
Until then, we're reducing the rollup interval
- reduce rollup interval to 2s
> decrease rollup time

- go/config/host_config.go
- go/node/docker_node.go
Restore configs after the rollup/batch limiter is introduced
> restore configs

- go/common/compression/data_compression_service.go
- go/enclave/components/batch_producer.go
- go/enclave/components/batch_registry.go
- go/enclave/core/batch.go
- go/enclave/core/rollup.go
- go/enclave/db/interfaces.go
- go/enclave/db/rawdb/accessors_chain.go
- go/enclave/db/storage.go
- go/enclave/enclave.go
- go/enclave/evm/chain_context.go
to remove some bottlenecks
1. no longer read the entire batch when only the header is needed
2. use faster default brotli compression when compressing batches
> performance fixes

- go/config/enclave_config.go
- go/node/docker_node.go
the tests failed with "oversized data"
reducing the rolllup and batch limit
> adjust limiters

- go/enclave/components/rollup_consumer.go
```
ERROR[05-30|03:37:56.803] Encountered error while processing l1 block node_id=0xc272459070A881BfA28aB3E810f9b19E4F468531 component=enclave     err="rollup was not correctly chained. height=3717 hash=[16 220 20 248 176 213 148 46 141 189 113 121 134 63 28 158 254 110 86 208 254 227 234 182 64 180 94 42 235 1 70 0] Cause: expected new rollup but rollup 3717 height was less than or equal to previous rollup 3717"
```
fix hex formatting
> fix hash formatting in error msg

- go/common/host/host_healthcheck.go
- go/host/host.go
When we are behind the L1 we don't produce batches and we probably don't have current L2 state. So we should fail the health check so external tests etc. are aware.
Add L1 synced flag to the host health check
> Add l1 up-to-date flag to host health check

- go/host/batchmanager/batch_manager.go
- go/host/host.go
Hard to see what's going on when batch requests failing.
> add logging details when catching up missing batches

- go/host/host.go
Producing rollups when out of sync with L1 is not a good idea (no batches are being produced and the enclave won't see them for a long time, causing issues with spamming out rollups at the same height).
> Skip rollup production when out of sync with L1

- go/common/host/host.go
- go/host/p2p/p2p.go
- integration/simulation/p2p/mock_l2_network.go
Small PR laying the ground work for enclave-guardian and HA.
P2P subscriptions only need the narrow P2PSubscriber interface, not a full Host interface.
> Separate p2p sub methods from host interface

- tools/walletextension/container/walletextension_container.go
- tools/walletextension/useraccountmanager/user_account_manager.go
- tools/walletextension/useraccountmanager/user_account_manager_test.go
- tools/walletextension/wallet_extension.go
This change is needed as part of transforming Wallet Extension to Obscuro Gateway described here: https://github.com/obscuronet/go-obscuro/blob/main/design/ux/Obscuro_Gateway.md
UserAccountManager was added which enables to handle multiple accounts per user
> add UserAccountManager to manage accounts for multiple users

- go/host/db/batches.go
- go/host/db/batches_test.go
- go/host/host.go
AddBatchHeader method adds all parts of a batch to the DB. Was confusing that it only mentioned storing header.
Rename method and related comments/test errors
> Rename host db add batch method

- contracts/package.json
Limits the hardhat and hardhat deployer versions to the latest patch version only
> Use latest patch version, not latest minor version

- .github/workflows/manual-deploy-testnet-l2.yml
- .github/workflows/manual-upgrade-testnet-l2.yml
Both the manual deploy and upgrade scripts have been failing because the docker image vars are not being output successfully, this seems to be because the hardcoded part clashes with part of one of our secret usernames.
To fix this I've written out the full image names all over the place and just had a simple var to toggle the `dev_` prefix on the image name.
This comes out quite verbose, there must be a simple way to have a constant for things that are declared in the script (like the hostname in the docker image) but I just wanted to prove this fixes it for now.
> Testnet github actions: fix clash with secrets

- go/enclave/enclave.go
- go/enclave/nodetype/interfaces.go
- go/enclave/nodetype/sequencer.go
- go/enclave/nodetype/validator.go
Sequencers and validators should process rollups using the same code.
In practice, sequencers will never execute the batches, because they produced them, and they are already in the db.
- move the l1 block ingestion logic out of the "Node Type"
> simplify block processing logic
