ten-protocol/go-ten

TODO.txt
go/common/l1_types.go
go/obscuronode/enclave/db.go
go/obscuronode/enclave/enclave.go
go/obscuronode/node.go
ideas.txt
integration/simulation/simulation_test.go

this is the mechanics of the secret-sharing protocol

Implement very basic secret sharing procedure

---

go/common/utils.go
go/obscuronode/enclave/enclave.go
go/obscuronode/enclave/utils.go
go/obscuronode/node.go
integration/ethereummock/node.go
integration/simulation/simulation.go
integration/simulation/simulation_test.go
integration/simulation/utils.go

Sample output:
```
1646928068646 Genesis block: b_3374234790882328481.
1646928068689 > M5: create b_2027583216801375278(Height=1, Nonce=17617)[parent=b_3374234790882328481]. Txs: []
1646928068706 >   Agg1: Could not process block b_3374234790882328481
1646928068706 >   Agg1: Could not process block b_2027583216801375278
1646928068721 > M8: create b_2236825914976897102(Height=2, Nonce=28649)[parent=b_2027583216801375278]. Txs: [deposit(0=0) r_7799613493027915944 deposit(0=0) deposit(0=0)]
1646928068729 >   Agg1: create rollup=r_3800994061866491144(1)[r_7799613493027915944]{proof=b_2236825914976897102}. Txs: []. State=map[].
1646928068731 > M2: create b_17809768653278712935(Height=3, Nonce=9129)[parent=b_2236825914976897102]. Txs: [deposit(0=0) deposit(0=0) deposit(0=0) deposit(0=0) …
```

Prettifies simulation results

---

go.mod
go.sum

As per title.
Quick Note: Might delay this merge a few days until tooling has caught up. (mainly homebrew recipes and golangci-lint)

upgrading to 1.18

---

go/obscuronode/enclave/state.go

Removed some code that was leftover from debugging. 
Minor refactored and commented some key logic.

Clarify genesis handling logic

---

go/obscuronode/enclave/enclave.go
go/obscuronode/enclave/l2tx.go
go/obscuronode/enclave/state.go
go/obscuronode/enclave/utils.go

This PR changes the deposit processing logic to make it more compatible to the future evm implementation, where they will be normal Obscuro transactions.

First step to evm integration. Deposits become L2 txs

---

go.mod
go.sum
go/obscuronode/enclave/enclave.go
go/obscuronode/enclave/rollup.go
go/obscuronode/enclave/state.go
go/obscuronode/nodecommon/enclave.go
integration/simulation/validate_chain.go

This is a prerequisite for the evm integration.
Also changed the verification of the blockchain to be performed in parallel to avoid the height skew that was a bit flaky.

create rollup header before starting tx processing 

---

.github/workflows/build-push.yml
.github/workflows/manual-build-test.yml
dockerfiles/README.md
dockerfiles/enclave.Dockerfile
dockerfiles/enclave_local_build.Dockerfile

Enables building the docker image base on the current code instead of the main github branch

build image based on current code

---

go/obscuronode/enclave/db/db.go
go/obscuronode/enclave/db/storage.go
go/obscuronode/enclave/enclave.go
go/obscuronode/enclave/mempool/interface.go
go/obscuronode/enclave/mempool/manager.go

simplify the db in preparation for integration of the statedb

extract mempool logic

---

go/obscuronode/enclave/db/storage.go
go/obscuronode/enclave/enclave.go
integration/simulation/simulation_docker_test.go

- add TxHandler to docker test
- remove a panic 
- fix docker stopping

Fix docker tests

---

integration/gethnetwork/build_geth_binary.sh

Its files kept showing up in my search results, which was annoying.

Deletes Geth repo after building binary.

---

integration/ethereummock/node.go

Why is this needed
- Not sure how it was working before as it was comparing two pointers
- Returns the same error as ethereum

fixes block_by_number call

---

go/obscuronode/host/host.go

- In relation to https://github.com/obscuronet/obscuro-internal/issues/197
- To prepare for upcoming changes for the bootstrap as streaming
- removed single use methods
- added comments
- renamed some var
- Reduced Nesting https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting
- Hosts file

host file cleanups

---

go/obscuronode/host/host.go

Reverts obscuronet/go-obscuro#213

Revert "host file cleanups"

---

go/ethclient/mgmtcontractlib/mgmt_contract_lib.go
go/obscuronode/enclave/enclaverunner/cli_test.go
tools/obscuroscan/README.md
tools/obscuroscan/obscuroscan.go
tools/obscuroscan/obscuroscan_test.go
tools/obscuroscan/static/block_decoder.html
tools/obscuroscan/static/block_decoder.js
tools/obscuroscan/static/block_monitor.html
tools/obscuroscan/static/block_monitor.js
tools/obscuroscan/static/index.html
tools/obscuroscan/static/style.css

https://github.com/obscuronet/obscuro-internal/issues/468
Functional PR. It extends Obscuroscan to allow decryption of encrypted rollups.
Note that because rollups aren't actually encrypted at present, for now the UI just decodes them. There are TODOs to actually decrypt later on.
* `obscuroscan_test.go` contains tests showing the actual decoding happening. The rest is very basic HTML/JS/webserver stuff
* Follow the instructions in `tools/obscuroscan/readme.md` to run Obscuroscan and try it out. Here's an example encoded rollup you can paste into the UI to decode (doesn't matter what you put in the private key field, it's not used for now):
```5c26b62600000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000e98483473494141 …
```

Extends Obscuroscan to allow decoding of rollups

---

.github/workflows/build-pr.yml
.github/workflows/manual-build-test.yml

Lots of zombie CI processes across runs.
Functional.
Adds a clean-up step for building PRs and manual test CI.

Clean-up step in CI

---

.github/workflows/build-pr.yml
integration/gethnetwork/geth_network.go

- to better understand why tests are failing
- 
-cleanup script was improved, and added a port listing at the end

test debugging

---

go/obscuronode/enclave/db/interfaces.go
go/obscuronode/enclave/db/storage.go

expose the persisted receipts
-  functional PR 
- create functions that expose the info in the db
- the storage

add Receipt & transaction methods

---

go/obscuronode/enclave/sql/edgelessdb.go

To make node start-up orchestration less fragile it is best if it doesn't matter which starts first, the enclave or the EdgelessDB instance
- wait for EDB HTTP port to be connectable before proceeding with handshake process and db connection

Ensure EDB is available before attempting handshake/connection

---

tools/networkmanager/README.md
tools/networkmanager/cli.go
tools/networkmanager/inject_txs.go

See changes below.
Refactoring.
- Better CLI defaults
- Better CLI param names
- Fix wrong and missing params in readme
- Prints before attempting connection to L1 and L2 (useful for timeouts)

Fixes and usability improvements to tx injector tool.

---

docs/_data/navigation.yml
docs/testnet/obscuroscan.md

- description and if available link to ticket

Added ObscuroScan page

---

go/enclave/evm/evm_facade.go

Currently, txs fail because no balances are preallocated.
Functional.
- Preallocates balance to sender of tx (short-term solution)

Preallocs balance.

---

docs/testnet/deploying-a-smart-contract.md
docs/testnet/obscuroscan.md
docs/testnet/wallet-extension.md

- more detail added to docs for SC deployment
- more accurate description on using remix to deply SC

Update to docs

---

docs/testnet/deploying-a-smart-contract.md
docs/testnet/wallet-extension.md

Some minor clarifications based on having worked through the docs "for real"

Minor changes to wallet/deploy docs

---

tools/obscuroscan/obscuroscan.go

I forgot to remove this todo after rollups were encrypted.

Removes outdated todo.

---

go/common/utils.go

- description and if available link to ticket

Removes old todo.

---

integration/simulation/transaction_injector.go

Old todo was lying around. Was very quick to clear up.

Uses random L2 client.

---

.github/workflows/manual-deploy-l1network.yml
.github/workflows/manual-deploy-obscuro-testnet-network.yml
go/common/profiler/profiler.go
go/config/enclave_config.go
go/config/host_config.go
go/enclave/enclave.go
go/enclave/enclaverunner/cli.go
go/enclave/enclaverunner/cli_flags.go
go/host/host.go
go/host/hostrunner/cli.go
go/host/hostrunner/cli_flags.go
go/host/hostrunner/test.toml
integration/noderunner/noderunner_test.go
integration/simulation/network/network_utils.go
testnet/docker-compose.non-sgx.yml
testnet/docker-compose.yml
testnet/start-obscuro-node.sh

- https://github.com/obscuronet/obscuro-internal/issues/607
- Helpful to debug testnet issue
- Host and Enclave Flags

Add profiler flag

---

README.md

We need a readme to explain what the project is, what it does, where to find various things, and how to run the project
Functional PR.
The high-level description o the major components.
A guide on how to start, and other useful bits will be added in subsequent PRs
-

Readme - the high level description

---

go/enclave/rollupchain/rollup_chain.go

help investigate why off chain calls don't work
- add logging
- functional

Improve logging

---

.github/workflows/manual-deploy-obscuroscan.yml

- https://github.com/obscuronet/obscuro-internal/issues/589
-
- github action file

obscuroscan deployment 

---

.github/workflows/manual-deploy-obscuro-testnet-network.yml

- https://github.com/obscuronet/obscuro-internal/issues/635
- new deployments have the testnetlatest=true tag
- new deployments will delete the resources with the tag before deploying

tagging deployment with latest + adding delete step

---

docs/testnet/deploying-a-smart-contract.md

- warning testnet participants the testnet will be restarted and smart contracts redeployed
- new paragraph

Redeploy SC warning

---

tools/walletextension/main/cli.go

wallet extension connects to the pointer address of the port
functional pr.
fix pointer

fix wallet extension cli parsing

---

go/enclave/db/storage.go
go/host/in_mem_obscuro_client.go
integration/ethereummock/node.go

- the in memory test was getting stuck
- functional
- create a mock subscription
- add more logging and some small pointer fix

fix unsubscribe issue

---

tools/walletextension/main/main.go

- Adds more info when starting the wallet

Adds more info

---

.github/workflows/build-pr.yml
.github/workflows/golangci-lint.yml

- As per title
- CI Push Action

CI to ignore the design folder changes

---

docs/_data/navigation.yml

Docs change caused broken paths.
Functional.
- Fixes broken paths

Fixes broken paths.

---

tools/azuredeployer/networkdeployer/run.sh

Run script is now broken due to CLI flag changes.
Functional.
- Fixes run script

Fixes run script.

---

docs/testnet/obscuroscan.md

The ObscuroScan docs page is outdated following ObscuroScan's redesign.
Functional.
- Updates docs to match new behaviour

Updates ObscuroScan docs to match redesign.

---

docs/testnet/essentials.md

- update to obscuroscan url
- minor text change

update to ObscuroScan URL

---

tools/contractdeployer/contract_deployer.go

- very silly bug, was deploying the ABI instead of the bytecode
- deploy the erc20 bytecode

fix the erc20 contract deployment

---

tools/obscuroscan/obscuroscan.go
tools/obscuroscan/static/index.html
tools/obscuroscan/static/index.js

This is one of the statistics we want to display to users in ObscuroScan.
Functional.
- Displays average rollup time.

Displays average rollup time in ObscuroScan.

---

tools/obscuroscan/static/index.html

We need a Discord link on ObscuroScan, to help people get support and join the community.
Functional.
- Adds a Discord link to the ObscuroScan navbar

Adds Discord link to ObscuroScan

---

docs/_data/navigation.yml

- Includes the section about deployment a smart contract programatically 
- Updated docs/_data/navigation.yml
- The include md file containst a link to a file which is contained in the docs/testnet directory (deploying-a-smart-contract-programmatically.py). I'm not sure if this file will automatically be bundled up or included in the site when served, so would be good to check this?

Include deploying-a-smart-contract-programmatically

---

docs/wallet-extension/wallet-extension.md

Fixing image path

---

.github/workflows/golangci-lint.yml

No downsides, and may help us detect linter issues when the linter fails.
Functional.
- Adds verbose flag to linter

Verbose linting.

---

go/host/rpc/clientapi/client_api_eth.go

- Minor fixes related with lint changes

Minor lint fixes

---

go/rpcclientlib/viewing_key_client.go

Minor. There's an assignment we can skip, since variable declarations are `nil` by default.

Simplifies ViewingKeyClient.Call logic.

---

.github/workflows/manual-deploy-obscuro-dev-testnet.yml

- https://github.com/obscuronet/obscuro-internal/issues/711
- Github actions

initial commit

---

go/common/log/log.go
go/common/logging.go
go/enclave/bridge/bridge.go
go/enclave/enclave.go
go/enclave/enclaverunner/enclave_runner.go
go/enclave/evm/evm_facade.go
go/enclave/rollupchain/rollup_chain.go
go/enclave/rpc_server.go
go/host/node/node.go
integration/common/testlog/testlog.go
integration/gethnetwork/geth_network.go
tools/contractdeployer/main/main.go

- Reduces the log verbosity in the tests
- refactoring of some logs

reducing logs verbosity

---

docs/testnet/deploying-a-smart-contract-programmatically.md
docs/testnet/deploying-a-smart-contract-programmatically.py

- Updates the example python script and docs for deploying programmatically into Obscuro.
- docs page detailing how to deploy programatically 
- example python script

Updated for the new approach to generating viewing keys

---

go/common/enclave.go
go/enclave/enclave.go
go/enclave/rollupchain/rollup_chain.go
go/enclave/rpc/rpc_utils.go
go/host/rpc/clientapi/client_api_eth.go
integration/walletextension/wallet_extension_test.go

Currently, we always return a dummy balance. We need to return the user's real balance.
Functional.
- Calculates the user's balance instead of returning a dummy
We now, we always return the latest balance, rather than allowing the user to specify which balance to return.

eth_getBalance returns expected amount

---

docs/testnet/changelog.md

- description and if available link to ticket
- ...

Updates changelog.

---

docs/_data/navigation.yml
docs/testnet/Introduction.md
docs/testnet/limitations.md

- developers are hitting limitations of Testnet without knowing it is a limitation and so potentially wasting time working around it
- new limitations.md file
- pulled in Cais's changes to Introduction.md
- limitations.md
- introduction.md

add limitations.md to docsite

---

go/enclave/db/sql/edgelessdb.go

fix error crashing testnet
blob->mediumblob

increase the storage value size to mediumblob

---

integration/gethnetwork/geth_network.go

Currently, there are various panics in the `NewGethNetwork` constructor, where we do not clean up properly before exiting.
Functional.
- Tries to stop all node processes if panicking during `NewGethNetwork`
- ...

Makes sure Geth nodes are terminated if there are panics in the constructor.

---

tools/contractdeployer/cli.go
tools/contractdeployer/contract_deployer.go

Various changes are required to the contract deployer to support preallocs.
Functional.
- Logs better error messages
- Makes sure prealloc tx succeeds
- Proper handling of default constructor params
- ...

Contract deployer fixes

---

integration/constants.go
integration/contractdeployer/contract_deployer_test.go
integration/noderunner/noderunner_test.go
integration/walletextension/wallet_extension_test.go
tools/contractdeployer/contract_deployer.go

There are no tests of the contract deployer, so it keeps breaking.
Functional.
- Adds a first golden-path integration test of the contract deployer, to catch obvious breakages
- ...

Adds golden-path contract deployer test.

---

go/host/rpc/clientapi/client_api_eth.go

- getCode was not working as expected, latest block was not fetchable
- part of https://github.com/obscuronet/obscuro-internal/issues/596
- Latest and earliest is now acceptable

rpc.BlockNumber now accepts latests and earliest strings

---

go/enclave/evm/evm_facade.go
go/enclave/rollupchain/rollup_chain.go
go/enclave/rpc/rpc_encryption_manager.go
go/enclave/rpc/rpc_utils.go

- part of https://github.com/obscuronet/obscuro-internal/issues/596
- Fixes minor bugs that would be reported when using the deployment tools for uniswap
-
- evm_facade.go 
- Error log upgrade
- ExecuteOffChainCall now uses a pointer to address to support offchain contract creation calls
- ExecuteOffChainCall executes messages with a default 100M gas
- rollup_chain.go
- Correctly handles nil strings
- rpc_utils.go
- ExtractCallParamTo correctly extracts nil addresses ( contract creation )

Minor fixes and tweaks to the enclave/evm

---

docs/testnet/changelog.md

- Updating the change log for modifications going into the release, end of sprint 38
- The docs/testnet/changelog.md file only has been changed
- Could you please add anything else relevant from a users perspective?

Update change log

---

go/host/p2p/p2p.go

- description and if available link to ticket
- Is this a functional or refactoring PR (it needs to be one or the other)
- ...

Updates warning wording.

---

design/Events_design.md

This is useful information that will guide our implementation of Obscuro events.

Adds an appendix to the events design.

---

docs/testnet/changelog.md

Updates changelog.
- Is this a functional or refactoring PR (it needs to be one or the other)
- ...

Adds viewing key persistence to changelog.

---

design/tech_decisions.md

To avoid the proliferation of tooling and frameworks.
Functional.
- Adds a tech-choices design doc
- ...

Adds a tech decisions design doc.

---

.github/workflows/manual-deploy-dev-testnet.yml

- https://github.com/obscuronet/obscuro-internal/issues/918
- As per title
- GA changes

dev tesnet deployment triggers faucet dev deployment

---

docs/testnet/changelog.md

- Adding in user visible changes to testnet in preparation for a v0.3.0 release
- Updates to the change log in docs/testnet
- The change log as described above

Add in change log for user visible changes to testnet

---

.github/workflows/on-merged-pr.yml

- Previously the definition was for a workflow dispatch - this updates to make a repo dispatch 
- The on-merged-pr.yml file has been updated accordingly

Updated to make a repo dispatch

---

docs/testnet/changelog.md
docs/testnet/deploying-a-smart-contract-programmatically.md
docs/testnet/deploying-a-smart-contract-programmatically.py
docs/wallet-extension/wallet-extension.md

- Brings the external docs up to date for the v0.3.0 release. 
- Updates to the change log and the testnet external docs
- See comments in the changed files

Updates for the wallet extension documentation 

---

docs/testnet/Introduction.md
docs/wallet-extension/wallet-extension.md

- Corrections for viewing key persistence, and for downloading the binaries from the release page. 
- Testnet docs only 
- Changes as detailed

Some minor changes /enhancements noticed for the wallet extension docs

---

testnet/docker-compose.debug.yml
testnet/docker-compose.dev-testnet.yml
testnet/docker-compose.non-sgx.yml
testnet/docker-compose.yml
testnet/start-obscuro-node.sh

- https://github.com/obscuronet/obscuro-internal/issues/870
- Changed testnet tooling mainly

Hooking up the log level flag into the testnet tooling

---

docs/testnet/changelog.md

- Adding a change log entry for support with WebSockets
- The change log
- The change log entry - specifically can you update if we support concurrent HTTP and WS connections etc?

Add change log entry for WebSockets

---

integration/walletextension/wallet_extension_test.go
tools/walletextension/readwriter/read_writer.go

Currently, we do not log or report errors when using the WE over WS.
- Adds error reporting when using the WE over WS
- Adds test of error reporting

Implements error handling for WE requests over WS. Adds test.

---

pull_request_template.md

- It feels like the key areas point are mostly ignored/not filled. Albeit used sometimes for very large PRs.
- Slightly tweaks the PR template

Tweaking the PR template

---

go/common/gethenconding/geth_encoding.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/rollupchain/rollup_chain.go
go/enclave/rpc/rpc_utils.go
tools/walletextension/accountmanager/account_manager.go
tools/walletextension/test/wallet_extension_test.go

- Connected with https://github.com/obscuronet/obscuro-internal/issues/929
- Fixes a bug introduced related with the eth call convertion

Fixes eth call convertion approach

---

go/enclave/events/subscription_manager.go
go/host/node/node.go
go/host/rpc/clientapi/client_api_filter.go
integration/simulation/simulation.go
integration/simulation/validate_chain.go

Different subscriptions should receive different logs.
- Route logs using the subscription ID as a topic
- Update checks in the sims
- Extends the sim validation logic for logs
- Fix bug in checking whether a topic could be a user address

Logs: Route events correctly based on subscription IDs

---

go/enclave/bridge/bridge.go
go/enclave/events/subscription_manager.go
go/obsclient/authclient.go
go/rpc/encrypted_client.go
integration/simulation/simulation.go
integration/simulation/validate_chain.go

As per the Geth API, we want the ability to provide filters that limit the logs that are returned.

Apply filters to log subscriptions

---

design/Events_design.md
tools/walletextension/accountmanager/account_manager.go

The existing design covers the decisions around who gets to see what events, but not how the actual handling of events would be implemented. This addresses that.

Updates the events design to cover the implementation

---

go/ethadapter/geth_rpc_client.go

- We have seen some testnet failures where nodes are unable to connect to the L1 and immediately panic, e.g.:
`panic: could not subscribe for new head blocks. Cause: dial tcp 20.90.169.73:9000: connect: connection refused`
- This is not entirely unreasonable but we want to make sure we're not blowing from a minor blip in the azure service or something
- this change is to make the request for streaming head blocks respect the configured timeout on the L1 client instead of immediately panicking on a single connection failure
- this should be improved as part of refactoring work but at least having this retry in will help us, either:
a. it is a brief blip then this means we won't lost our testnet unnecessarily
b. it is not a brief blip and this will demonstrate that the L1 was unavailable …

Basic retry for the L1 block stream to avoid panics from blips

---

docs/api/sensitive-apis.md
docs/testnet/deploying-a-smart-contract-programmatically.md

Fix 404s in docs

---

go/enclave/events/subscription_manager.go

We store the subscriptions in a map that we range over. If we add or delete a subscription while ranging, this causes a concurrency exception (`fatal error: concurrent map iteration and map write`).
- Use a mutex to manage concurrent reads and writes

Fixes concurrency bug with subscriptions.

---

go/enclave/db/interfaces.go
go/enclave/enclave.go
go/enclave/events/subscription_manager.go
go/enclave/rollupchain/rollup_chain.go

Tidying up naming and comments in SubscriptionManager

---

go/host/events/logs.go

Remove unused todo

---

README.md
docs/testnet/changelog.md

- In preparation for the 0.5 release
- The top level readme, and the change log

Addition of change log and faucet server to readme

---

testnet/docker-compose.debug.yml
testnet/docker-compose.dev-testnet.yml
testnet/docker-compose.non-sgx.yml
testnet/docker-compose.yml

Add missing commas to line yaml line ends

---

design/Events_design.md

We've made some changes to the design over time. This update covers some of these, and cleans up the document a bit for readability.

Update events design

---

design/Events_design.md

Cleans up the events design doc.

---

design/Events_design.md
go/rpc/encrypted_client.go

More updates to the events design

---

docs/api/apis.md
docs/api/sensitive-apis.md

Lists eth_getLogs as a sensitive method in the docs

---

go/common/gethencoding/geth_encoding.go
go/enclave/enclave.go
go/enclave/rollupchain/rollup_chain.go
tools/walletextension/accountmanager/account_manager.go

Typo in package name.

---

go/enclave/rollupchain/rollup_chain.go

- Related with https://github.com/obscuronet/obscuro-internal/issues/929
- Minor refactor so that the dynamic gas estimation can check the balance of the account of the call
- Minor refactor of funcionality so it can be called in other methods

Allow for balance to be called from other methods

---

docs/_docs/testnet/changelog.md

- Updates the changelog for v0.6
- The changelog only

Change log for v0.6

---

go/host/db/hostdb.go
go/host/rpc/clientapi/client_api_eth.go
go/obsclient/obsclient.go
go/rpc/client.go
integration/simulation/output_stats.go
integration/simulation/p2p/in_mem_obscuro_client.go
integration/simulation/utils.go
integration/simulation/validate_chain.go

Have sims test the eth_blockNumber endpoint

---

go/enclave/rollupchain/rollup_chain.go

- spammy log message is spammy

Downgrade the spammy log message on block ingestion

---

go/common/host/host.go
go/host/host.go
go/host/hostrunner/host_runner.go
integration/common/testlog/testlog.go
integration/ethereummock/mock_l1_network.go
integration/simulation/network/geth_network.go
integration/simulation/network/inmemory.go
integration/simulation/network/network.go
integration/simulation/network/network_utils.go
integration/simulation/network/obscuro_node_utils.go
integration/simulation/network/socket.go
integration/simulation/output_stats.go
integration/simulation/stats/stats.go
integration/simulation/validate_chain.go
tools/networkmanager/inject_txs.go

Use ObsClients in sims

---

go/common/errutil/errors_util.go
go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/sql/sql.go
go/enclave/db/storage.go
go/enclave/events/subscription_manager.go

- Connected to https://github.com/obscuronet/go-obscuro/pull/825
- Allows to check if DB communication is ok

Fetch latest Rollup Head now returns error

---

go/common/headers.go

a comment was wrong and misleading
-update comment

fix comment

---

go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_metadata.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/events/subscription_manager.go
go/enclave/evm/evm_facade.go
go/enclave/mempool/manager.go
go/enclave/rollupchain/rollup_chain.go
go/ethadapter/geth_rpc_client.go
go/ethadapter/interface.go
go/host/db/hostdb.go
go/host/rpc/clientapi/client_api_eth.go
go/host/rpc/clientapi/client_api_obscuroscan.go
go/host/rpc/clientapi/client_api_obscurotest.go
integration/ethereummock/db.go
integration/ethereummock/node.go
integration/simulation/output_stats.go
integration/simulation/simulation.go
integration/simulation/validate_chain.go
tools/networkmanager/inject_txs.go

Previously, it was too easy to forget to check whether the value returned by the DB was nil, instead of a real header.

Adds booleans to DB methods to indicate whether was found.

---

go/host/rpc/clientapi/client_api_obscuroscan.go

Cleans up the GetLatestTransactions API method

---

.github/workflows/manual-deploy-dev-testnet.yml
.github/workflows/manual-deploy-testnet-l2.yml

- https://github.com/obscuronet/obscuro-internal/issues/1168

Testnet DNS now point to node1

---

go/enclave/events/subscription_manager.go

We did not lock the map of subscriptions when reading from it. This led to `concurrent map read and map write` errors.

Fixes concurrency bug in subscription manager

---

.github/workflows/manual-deploy-dev-testnet.yml
.github/workflows/manual-deploy-testnet-l2.yml

- Datadog container environment option to enable auto detection of multi-line statements 
- The github workflow actions

Enable auto multi line detection

---

go/enclave/events/subscription_manager.go

Gets number of subs in threadsafe way.

---

go/common/errutil/errors_util.go
go/host/db/batches.go
go/host/db/batches_test.go
go/host/db/blocks.go
go/host/db/blocks_test.go
go/host/db/rollups.go
go/host/db/rollups_test.go
go/host/host.go
go/host/rpc/clientapi/client_api_eth.go
go/host/rpc/clientapi/client_api_obscuroscan.go
go/host/rpc/clientapi/client_api_obscurotest.go
integration/simulation/p2p/in_mem_obscuro_client.go

Returns errors from DB methods, instead of `found` bools and critical log events

---

go/host/host.go

Previously, the genesis batch was not stored.

Stores batch at the correct point.

---

docs/_docs/testnet/changelog.md

- Adds in changes to the change log for the v0.7 release
- The changelog.

Update changelog for the v0.7 release

---

go/enclave/evm/evm_facade.go
go/enclave/rpc_server.go

- https://github.com/obscuronet/obscuro-internal/issues/1206

Custom Error is now a pointer

---

.github/workflows/manual-deploy-dev-testnet.yml
.github/workflows/manual-deploy-testnet-l2.yml

Reverts obscuronet/go-obscuro#827

Revert "Testnet DNS now point to node1"

---

go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/storage.go
go/enclave/events/subscription_manager.go
go/enclave/rollupchain/rollup_chain.go

Too many enclave DB errors are swallowed. This work surfaces more of them.

Surface enclave DB errors

---

go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_metadata.go
go/enclave/db/storage.go
go/enclave/events/subscription_manager.go
go/enclave/rollupchain/rollup_chain.go
go/ethadapter/blockprovider.go
go/ethadapter/blockprovider_test.go
go/ethadapter/geth_rpc_client.go
go/ethadapter/interface.go
go/host/host.go
integration/ethereummock/db.go
integration/ethereummock/node.go
integration/simulation/simulation.go
integration/simulation/validate_chain.go
tools/networkmanager/inject_txs.go

More surfacing of enclave DB errors

---

go/common/gethutil/gethutil.go
go/enclave/bridge/bridge.go
go/enclave/db/interfaces.go
go/enclave/db/storage.go
go/enclave/events/subscription_manager.go
go/enclave/rollupchain/rollup_chain.go
integration/ethereummock/db.go
integration/ethereummock/mock_l1_network.go
integration/ethereummock/node.go
integration/ethereummock/utils.go

Surface more enclave errors

---

go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/evm/chain_context.go
go/enclave/mempool/interface.go
go/enclave/mempool/manager.go
go/enclave/rollupchain/rollup_chain.go

Surface enclave errors.

---

go/enclave/db/rawdb/accessors_attestation.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/rawdb/accessors_indexes.go
go/enclave/db/rawdb/accessors_metadata.go
go/enclave/db/rawdb/accessors_receipts.go
go/enclave/db/storage.go

Surface errors from accessors_receipts and accessors_metadata

---

go/common/profiler/profiler.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/rawdb/accessors_indexes.go
go/enclave/db/rawdb/accessors_receipts.go
go/enclave/db/storage.go

More enclave DB error handling

---

go/host/host.go

- As per title, a return was needed otherwise `receipt` would create a NPE at the trace operation

Fixes NPE when receipt takes longer than expected time

---

go/enclave/enclave.go
go/enclave/rollupchain/faucet.go
go/enclave/rollupchain/rollup_chain.go

- Connected with https://github.com/obscuronet/obscuro-internal/issues/1216
- Cleans up the faucet package
- Allows the faucet to return the changed state 
- Propagates errors upwards

Tweaking the faucet to allow for enclave unit tests

---

go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/rollupchain/rollup_chain.go

- https://github.com/obscuronet/obscuro-internal/issues/1216

Fix enclave tests

---

go/enclave/enclave.go
go/enclave/rollupchain/rollup_chain.go

- https://github.com/obscuronet/obscuro-internal/issues/1243

Rollup chain no longer handles encryption and Param validation

---

go/enclave/rollupchain/rollup_chain.go

Reworks confusing error block.

---

go/enclave/core/types.go
go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/rawdb/schema.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/events/subscription_manager.go
go/enclave/rollupchain/rollup_chain.go

Clarifies fields in `BlockState`

---

go/common/gethencoding/geth_encoding.go
go/enclave/enclave.go
go/enclave/rollupchain/rollup_chain.go

- https://github.com/obscuronet/obscuro-internal/issues/1252
- Also identified a dumb error on the block number handling 🤦 

Revert call error not correctly propagated

---

go/enclave/enclave_test.go
go/enclave/rollupchain/rollup_chain.go

Fixes test name that makes it hard to grep CI logs

---

go/enclave/db/interfaces.go
go/enclave/db/rawdb/accessors_chain.go
go/enclave/db/rawdb/schema.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/events/subscription_manager.go
go/enclave/rollupchain/rollup_chain.go

Removes buggy FetchHeadRollup method on storage

---

.github/workflows/manual-deploy-dev-testnet.yml
.github/workflows/manual-deploy-testnet-l2.yml
go/config/host_config.go
go/host/hostrunner/cli.go
go/host/hostrunner/cli_flags.go
go/host/main/main.go
testnet/docker-compose.dev-testnet.yml
testnet/start-obscuro-node.sh

- Part of https://github.com/obscuronet/obscuro-internal/issues/338
- Public key is not used in the code.

Remove pkaddress flag

---

testnet/docker-compose.debug.yml
testnet/docker-compose.dev-testnet.yml
testnet/docker-compose.non-sgx.yml
testnet/docker-compose.yml
testnet/start-obscuro-node.sh

Fixing deployment scripts

---

integration/common/utils.go

We only want to retry on specific error types, so the use of `retry.Do` is not appropriate.

Reverts use of retry.do when awaiting receipts

---

go/enclave/db/interfaces.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/rollupchain/faucet.go
go/enclave/rollupchain/rollup_chain.go

Clean up handling of genesis block

---

go/config/host_config.go
go/host/hostrunner/cli.go
go/host/hostrunner/cli_flags.go
go/host/hostrunner/cli_test.go
go/host/hostrunner/test.toml
integration/simulation/network/network_utils.go

- Removes a few flags that were not being used

Removes unused flags

---

.github/workflows/manual-deploy-dev-testnet.yml
.github/workflows/manual-deploy-testnet-l2.yml
README.md
go/common/node_type.go
go/config/enclave_config.go
go/config/host_config.go
go/enclave/enclave.go
go/enclave/enclaverunner/cli.go
go/enclave/enclaverunner/cli_flags.go
go/enclave/enclaverunner/test.toml
go/enclave/rollupchain/rollup_chain.go
go/host/host.go
go/host/hostrunner/test.toml
integration/noderunner/noderunner_test.go
integration/simulation/network/network_utils.go
integration/simulation/network/obscuro_node_utils.go
integration/simulation/validate_chain.go
testnet/start-obscuro-node.sh
tools/walletextension/main/cli.go

Removes IsSequencerEnclave. Updates node types.

---

go/host/batchmanager/batch_manager.go
go/host/host.go

Submit each batch to the enclave if it's successfully stored

---

docs/_docs/testnet/starting-a-node.md

- https://github.com/obscuronet/obscuro-internal/issues/1264

adds a start node doc

---

testnet/testnet-deploy-contracts.sh

Second attempt at fixing testnet

---

.github/workflows/manual-deploy-dev-testnet.yml
.github/workflows/manual-deploy-testnet-l2.yml

- Fixes the deployment scripts

Hosts now use the addr pk for deployment

---

go/config/enclave_config.go
go/enclave/container/cli.go
go/enclave/container/cli_flags.go
go/enclave/container/test.toml
go/enclave/enclave.go
go/enclave/rollupchain/rollup_chain.go

Check that received batch is produced by sequencer

---

pull_request_template.md

- Adds in details of running the E2E tests

Add section into PR template to cover running E2E tests

---

go/enclave/rollupchain/rollup_chain.go

Returns clearer error if rollup signature cannot be validated

---

.gitignore
.vscode/ltex.dictionary.en-US.txt
.vscode/settings.json

- Removes vscode IDE folder and adds it to the gitignore …

remove ides folders

---

.github/workflows/manual-deploy-testnet-l2.yml

- Fixes mismatch in the load balancer deployment and corrects step title (was a copy and paste)

Fix for issue deploying testnet

---

docs/_docs/testnet/changelog.md

- Adds in the additional PRs merged for this release

Updated changelog

---

README.md
testnet/docker-compose.local.yml
testnet/testnet-local-build_images.sh

- Uses docker compose --parallel to speed up the time to build the images

Parallel build the images

---

contracts/hardhat.config.ts
contracts/package.json
contracts/tasks/wallet-extension.ts
testnet/docker-compose.local.yml
testnet/walletextension.Dockerfile
tools/walletextension/common/constants.go

Added tasks for the wallet extension.

---

README.md
contracts/deployment_scripts/testnet/001_deploy_tokens.ts
contracts/hardhat.config.ts
contracts/src/common/ConstantSupplyERC20.sol
contracts/tasks/wallet-extension.ts

Fixes to some hh deployment issues. 

---

docs/_docs/testnet/changelog.md

- Updates the changelog for the release

Added changelog for the v0.9 release

---

go/enclave/rollupchain/rollup_chain.go

Check batches chain correctly across rollups. Delete some useless validation

---

go/common/headers.go
go/common/rpc/converters.go
go/enclave/l2chain/l2_chain.go
go/host/rpc/clientapi/client_api_eth.go
integration/datagenerator/batch.go

Fixes typo

---

integration/simulation/validate_chain.go

Removes dead code

---

go/enclave/db/interfaces.go
go/enclave/l2chain/l2_chain.go

Provide a clearer way for finding the latest rollup in the chain of a given head block.

---

integration/constants.go
integration/contractdeployer/contract_deployer_test.go
integration/simulation/network/geth_utils.go
integration/simulation/network/network_utils.go
integration/simulation/network/obscuro_node_utils.go
integration/simulation/network/socket.go

https://github.com/obscuronet/obscuro-internal/issues/1431

Fix contract deployer test ports

---

go/enclave/db/storage.go
go/enclave/l2chain/l2_chain.go

Currently we scan back through the L1 chain doing db lookups for rollups. When no rollup has been published we scan back to the start of the chain on **every** L1 block, causing thrashing and bringing the network to a halt.
Record the latest rollup against every L1 hash (even if it's no rollup) so we don't have to scan back. FWIW we used to do something like this and stopped at some point.
This might not be super efficient but it fixes the problem for now and we can optimise once we've built more out imo.

Record latest rollup for every L1 block to avoid scanning back

---

tools/walletextension/test/utils.go
tools/walletextension/test/wallet_extension_test.go
tools/walletextension/userconn/user_conn.go
tools/walletextension/wallet_extension.go

https://github.com/obscuronet/obscuro-internal/issues/1431
- Fixes in the WE port, conn and dummy api usage

Fixes for the we tests

---

go/common/log/log.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/l2chain/l2_chain.go
go/host/host.go

Makes use of the `log.BlockHeigh` and `log.BlockHash` consts

Add BlockHeight and BlockHash log keys

---

testnet/wait-eth2network-healthy.sh

Adds a script that waits for the eth2network to be ready

---

integration/eth2network/eth2_network.go
integration/eth2network/rotation_writer.go
integration/eth2network/rotation_writer_test.go

https://github.com/obscuronet/obscuro-internal/issues/1441

Rotates the eth2 logs

---

go/host/host.go

The code that fetches the latest p2p addresses from the L1 was a bit confusing.
Also it needs to run at node startup because at the moment it's only triggered by seeing responses to secret requests.
- Minor refactor to clarify the code that fetches p2p addresses from the L1 whenever it sees a secret response
- Call that same code at start-up

Clarify p2p address syncing

---

go/host/host.go

Host only needs to request secret after startup if its enclave is waiting for a secret (i.e. when the node initially starts)
Check the status of enclave before requesting secret for it

No need to request secret for enclave on host restart

---

go/host/p2p/p2p.go

I hit issues while testing node restart where an RPC request at the wrong time could cause index out of bounds errors when looking for sequencer.
We'd probably want other safe guards against that but at the very least we shouldn't just panic, we should return sensible error and recover.
Return error when sequencer requested but not known

Resilient to RPC requests while sequencer unknown

---

.github/workflows/manual-deploy-testnet-l1.yml
.github/workflows/manual-deploy-testnet-l2.yml

Fixed the format error in the dispatch event.

Fix to the format of the dispatch event

---

contracts/deployment_scripts/testnet/layer1/002_add_bridge_admin.ts
testnet/launcher/docker.go

The bridge admin address did not match the PK stated, and looked to be the POC address - this changes that.

Fix to the bridge admin address

---

.github/workflows/manual-deploy-testnet-l2.yml
contracts/tasks/wallet-extension.ts
testnet/launcher/docker.go
testnet/launcher/l2contractdeployer/cmd/main.go
testnet/launcher/l2contractdeployer/docker.go

This PR fixes the L2 deployment.
The launcher now waits for the docker container to finish.
Github action updated with the correct port. 

Deploy L2 contracts synchronously

---

go/enclave/events/subscription_manager.go

This PR addresses #1483 
Just added some logging to help identify issues with event relevancy.

Logging around event relevancy to help with debugging.

---

go/enclave/enclave.go

Null ptr rollup fix.

---

go/enclave/db/db.go
go/enclave/db/sql/batch.go
go/enclave/db/sql/edgelessdb.go
go/enclave/db/sql/sql.go
go/enclave/db/sql/sqlite.go
go/enclave/db/storage.go

Removed unnecessary interfaces

remove db interfaces

---

go/enclave/db/sql/sqlite.go
go/enclave/enclave_test.go

minor change to prepare for more tables

simplify sqlite creation logic

---

dockerfiles/enclave.debug.Dockerfile
dockerfiles/host.Dockerfile
testnet/contractdeployer.Dockerfile
testnet/eth2network.Dockerfile
testnet/hardhatdeployer.Dockerfile
testnet/obscuroscan.Dockerfile
testnet/walletextension.Dockerfile

Replaced Go version 1.17->1.18

---

go/common/batches.go
go/common/headers.go
go/common/log_events.go
go/common/metrics/metrics.go
go/common/rollups.go
go/common/rpc/generated/enclave.proto
go/config/enclave_config.go
go/enclave/container/enclave_container.go
go/enclave/core/batch.go
go/enclave/core/egoutils/egoutils.go
go/enclave/core/rollup.go
go/enclave/crosschain/block_message_extractor.go
go/enclave/crosschain/interfaces.go
go/enclave/crosschain/message_bus_manager.go
go/enclave/crypto/crypto.go
go/enclave/crypto/transaction_blob_crypto.go
go/enclave/db/interfaces.go
go/enclave/db/sql/edb_attestation.go
go/enclave/db/sql/edgelessdb.go
go/enclave/db/sql/sql.go
go/enclave/db/sql/sql_test.go
go/enclave/db/storage.go

Updates to the todos as part of backlog review (comments only)

Todo review edits

---

go/enclave/db/interfaces.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/events/subscription_manager.go
integration/simulation/validate_chain.go

there was a bug in the subscription logic.
The fromBlock was not defaulting to the latest number.
- fix bug
- add log messages
- add more validity checks 

fix filtering logic

---

.github/workflows/manual-deploy-testnet-l1.yml

remove -a option.

---

go/enclave/attestation.go
go/enclave/db/storage.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/events/subscription_manager.go
go/enclave/evm/evm_facade.go
go/enclave/evm/no_op_engine.go
go/enclave/evm/utils.go
go/enclave/genesis/testnet_genesis.go
go/enclave/l2chain/l1_blockchain.go
go/enclave/l2chain/l2_chain.go
go/enclave/mempool/manager.go
go/enclave/rollupmanager/rollupmanager.go
go/enclave/rpc/rpc_encryption_manager.go
go/enclave/rpc/rpc_utils.go
go/enclave/rpc_server.go

Second pass at review the todos in the code base

Review of todos part two

---

go/rpc/encrypted_client.go

more logging to debug event dups

add more logging in the verbose WE

---

go/enclave/enclave.go
go/rpc/encrypted_client.go

- fix off-by-one error on the subscription
- improve log

fix bug and improve log

---

go/enclave/db/sql/sqlite.go

check if sqlite is run on top of an existing file.
If yes, don't run the initialisation logic

fix sqlite init logic

---

testnet/hardhatdeployer.Dockerfile

Disabled notifications for npm.

---

go/common/docker/docker.go
go/node/docker.go

Small update to the docker volumes names

Renaming docker volumes

---

go/common/host/host.go
go/common/host/host_healthcheck.go
go/ethadapter/blockprovider.go
go/ethadapter/blockprovider_test.go
go/host/host.go

https://github.com/obscuronet/obscuro-internal/issues/1583

Block Provider now contributes to health status

---

docs/_docs/testnet/changelog.md

Adds in change log for the v0.12 release.

Add in change log for the v0.12 release

---

testnet/hardhatdeployer.Dockerfile

Locking the docker image alpine to 16

---

go/enclave/attestation.go
go/enclave/rollupmanager/rollupmanager.go
go/ethadapter/geth_rpc_client.go
go/host/db/hostdb.go
go/host/host.go

Part of our effort to clear down todos and make sure they're covered by issues. Started going through the @matt todos and removing or updating them. There are some left still, to revisit after the refactor is in/when I have more clarity.

Update some of the @matt todos

---

docs/index.md

The link for the PDF version of the Whitepaper was broken.
Replaced the broken link with a working link.

Fix broken link for the PDF version of the Whitepaper.

---

docs/_docs/testnet/changelog.md

Adds in the merged PRs for the version 0.13 release

Add change log for the v0.13 release

---

go/common/enclave.go
go/common/errutil/errors_util.go
go/common/rpc/converters.go
go/enclave/enclave.go
go/enclave/l2chain/l2_chain.go
go/enclave/rpc_server.go
go/host/host.go

https://github.com/obscuronet/obscuro-internal/issues/1645
Review the block submission error.
- Moved the enclave errors to the errutil as the errors are checked/used outside the enclave package.
- Small cleanups

Tidy up block submission errors

---

go/common/async/async.go
go/common/host/host.go
go/common/stopcontrol/stop_control.go
go/enclave/enclave.go
go/enclave/rpc_server.go
go/host/container/host_container.go
go/host/host.go
go/host/rpc/clientapi/client_api_obscurotest.go
integration/noderunner/noderunner_test.go
integration/simulation/network/obscuro_node_utils.go
integration/simulation/p2p/in_mem_obscuro_client.go

https://github.com/obscuronet/obscuro-internal/issues/1664
- Propagate Stop() errors from the host and the enclave
- Handle shutdown of RPC Server and Http Server when they receive a request

Fix the stop issue in the unit tests

---

.github/workflows/manual-deploy-testnet-l1.yml
.github/workflows/runner-scripts/conf.yml
.github/workflows/runner-scripts/run-datadog.sh
testnet/eth2network.Dockerfile

https://github.com/obscuronet/obscuro-internal/issues/921

Logs on the l1 containers

---

go/host/host.go

https://github.com/obscuronet/obscuro-internal/issues/1643

Avoid Forwarding bad txs to the Sequencer

---

go/config/enclave_config.go
go/enclave/container/cli.go
go/enclave/container/enclave_container.go
go/enclave/db/db.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/host/container/host_container.go
go/host/main/main.go
go/node/config.go
go/node/in_memory_node.go
go/wallet/wallet.go
integration/simulation/devnetwork/node.go
integration/simulation/network/network_utils.go

https://github.com/obscuronet/obscuro-internal/issues/1689
- Also stops copying the enclave config everwhere and uses a pointer instead

Fixes the testlog usage

---

.github/workflows/manual-deploy-testnet-l2.yml
.github/workflows/manual-upgrade-testnet-l2.yml

Using the brute force is simpler, and also want to be explicit around whether this is an upgrade or a new deployment.

Be explicit about the environment and whether deployed or upgraded

---

go/enclave/enclave.go

Added log timers.

---

go/enclave/components/batch_registry.go
go/enclave/db/interfaces.go
go/enclave/db/storage.go
go/enclave/enclave_test.go
go/enclave/nodetype/sequencer.go

Storage now accepts db batch.

---

tools/walletextension/main/cli.go

Fix databasePath to be consistent with other settings

---

go/host/host.go

to remove noisy log message
-reduce log level

fix log level

---

developer_onboarding_guide.md

Add developer onboarding guide

---

go/enclave/limiters/rolluplimiter.go
go/host/host.go

Log level was wrong for the error type and severity.

Changed log level.

---

developer_onboarding_guide.md

Add squash and merge to dev onboarding

---

tools/walletextension/userconn/user_conn.go

Add userID parameter in all request handlers

---

go/config/enclave_config.go
go/enclave/components/batch_registry.go
go/enclave/components/interfaces.go
go/enclave/components/rollup_producer.go
go/enclave/container/cli.go
go/enclave/container/cli_flags.go
go/enclave/enclave.go
go/enclave/enclave_test.go
go/enclave/limiters/batchlimiter.go
go/enclave/nodetype/sequencer.go
go/node/config.go
go/node/docker_node.go
integration/simulation/devnetwork/node.go
integration/simulation/network/network_utils.go
integration/simulation/network/socket.go

Added config for batch size limit.

---

go/enclave/components/batch_producer.go
go/enclave/container/enclave_container.go
go/enclave/crosschain/block_message_extractor.go
go/enclave/crosschain/message_bus_manager.go
go/host/container/host_container.go
go/host/p2p/p2p.go
go/node/in_memory_node.go
integration/noderunner/in_memory_node.go
integration/noderunner/noderunner_test.go
integration/simulation/network/obscuro_node_utils.go
integration/simulation/network/socket.go

to remove the annoying fields being logged twice.
And also moves a test class from the production code

fix logger config

---

go/enclave/components/batch_registry.go
go/enclave/limiters/rolluplimiter.go

Swapped true and false on acceptBatch.

---

go/config/enclave_config.go
go/host/host.go
go/node/docker_node.go
integration/simulation/devnetwork/node.go
integration/simulation/network/network_utils.go

Changed limits.

---

go/enclave/components/rollup_producer.go

Spamming out logs for an issue we've already identified. Just warn if it's gone back > 100 blocks.

enclave: log less when scanning backwards for rollups

---

go/obsclient/authclient.go
integration/common/utils.go
integration/manualtests/tx_test.go
integration/networktest/userwallet/userwallet.go
integration/simulation/simulation.go
integration/simulation/transaction_injector.go
tools/contractdeployer/obscuro_deployer.go

https://github.com/obscuronet/obscuro-internal/issues/1593

Fix SendTransaction method signature

---

go/enclave/components/interfaces.go
go/enclave/components/rollup_consumer.go
go/enclave/nodetype/sequencer.go
go/enclave/nodetype/validator.go

Fix for incorrectly chained rollups.

---

go/host/host.go

We should not publish batches while in 'catch-up', if there are issues with the sequencer it will halt batch production rather than carry on ignoring L1 activity that it's unaware of.
Add a flag to the host that is updated to true with every successful submission of an L1 block.

Only publish batches when up-to-date with L1

---

go/host/host.go

Start from right hash.

---

go/common/metrics/metrics.go
go/ethadapter/blockprovider.go

Fix LOG_15 logger param errors

---

.github/workflows/manual-deploy-testnet-faucet.yml

Dependency of https://github.com/obscuronet/obscuro-internal/issues/1784

Adding the faucet workflow

---

tools/walletextension/api/routes.go
tools/walletextension/api/utils.go
tools/walletextension/common/constants.go
tools/walletextension/storage/sqlite.go
tools/walletextension/storage/storage.go
tools/walletextension/wallet_extension.go

As described in [Obscuro Gateway Design](https://github.com/obscuronet/go-obscuro/blob/main/design/ux/Obscuro_Gateway.md ) new endpoints are needed
Added following endpoints:
- /join
- /authenticate
- /revoke
- /query

Add Obscuro gateway endpoints

---

.github/workflows/manual-deploy-testnet-faucet.yml
.github/workflows/manual-deploy-testnet-l2.yml
.github/workflows/manual-upgrade-testnet-l2.yml

Adds in the workflow call and also the repository dispatches for the E2E tests

Fixes to L2 upgrade and deployment 

---

.github/workflows/build-pr.yml

Adds in a 2 day retention period to the build pr

Add in retention period

---

integration/noderunner/in_memory_node.go

no IDs on host log msgs in sims

fix logger for sim hosts

---

integration/noderunner/in_memory_node.go

Add the testlogger back in for sims with the ID being set this time.

fix the sim logger again

---

go/enclave/components/rollup_consumer.go

This is a temporary fix until the rollup refactoring.
address a small corner case

temporary rollup logic fix

---

.github/workflows/manual-deploy-obscuro-gateway.yml

To make Obscuro Gateway deployment work
Add int port and portWS to the command to override defaults

Fix Obscuro Gateway deployment

---

go/common/host/host_healthcheck.go
go/common/host/identity.go
go/common/host/services.go
go/host/host.go
go/host/l1/blockrepository.go
go/host/l1/publisher.go

Move Obscuro management contract L1 logic out of host into its own service as part of enclave-guardian changes.

Add L1 publishing service

---

.github/workflows/manual-deploy-testnet-l2.yml
testnet/testnet-local-build_images.sh

testnet is not deploying
fixed paths, removed unused variables

fix testnet after docker refactoring

---

tools/walletextension/api/routes.go
tools/walletextension/common/common.go
tools/walletextension/common/types.go
tools/walletextension/container/walletextension_container.go
tools/walletextension/storage/sqlite.go
tools/walletextension/storage/storage.go
tools/walletextension/useraccountmanager/user_account_manager.go
tools/walletextension/useraccountmanager/user_account_manager_test.go
tools/walletextension/wallet_extension.go

Obscuro Gateway needs to support multiple users
Handle accountManagers correctly to support multiple users and to still enable old WE endpoints to work

Obscuro gateway multi user support

---

go/enclave/db/sql/edgelessdb.go
go/enclave/db/sql/edgelessdb/001_init.sql
go/enclave/db/sql/sql_test.go
go/enclave/db/sql/sqlite.go
go/enclave/db/sql/sqlite/001_init.sql

As our db schema grows more complex, we need a sane way to manage it.
Move the db initialisation scripts to separate files

Move sql creation logic to "sql" files. 

---

.github/workflows/manual-upgrade-testnet-l2.yml

Deployment of the faucet was not working on a scheduled upgrade

Fix the deployment of the faucet on a scheduled trigger

---

dockerfiles/enclave.Dockerfile

Lock ego container image

---

go/host/host.go

Node can get stuck in a loop if it returns to a previously visited fork branch because the enclave keeps reporting a non-canonical L1 head but has already processed the LCA.

avoid getting stuck when returning to a prev L1 fork

---

.github/workflows/manual-deploy-obscuro-scan-2.yml
.gitignore
tools/obscuroscan_v2/Dockerfile
tools/obscuroscan_v2/container_run.sh
tools/obscuroscan_v2/entrypoint.sh

https://github.com/obscuronet/obscuro-internal/issues/1958
- Adds a dockerfile for obscuroscan
- Adds a manual trigger to deploy it to azure

Obscuroscan v2 deploy 

---

.github/workflows/manual-deploy-obscuro-scan-2.yml

Fixes to the Obscuro Scan V2 deploy

---

.github/workflows/manual-upgrade-testnet-l2.yml

Set the upgrade frequency back to once a night at 03:05am.

Set back to 03:05 nightly

---

go/enclave/enclave.go
go/enclave/events/subscription_manager.go

Set the starting point of a subscription the moment it is created.
Previously it was set on the first call, which might have ended up with missing event logs

fix timing issue for subscriptions

---

go/enclave/events/subscription_manager.go

Add missing "<=" to event log subscription

fix add subscription logic

---

integration/obscurogateway/obscurogateway_test.go
tools/walletextension/api/routes.go
tools/walletextension/common/constants.go

https://github.com/obscuronet/obscuro-internal/issues/2018

Add an health endpoint to OG

---

go/enclave/components/batch_executor.go
go/enclave/core/batch.go
go/enclave/nodetype/sequencer.go

properly reset the cached hash

add hash reset

---

go/host/p2p/p2p.go

- RefreshPeerList() uses a mutex to write the p.peerAddresses
- getSequencer() does not use the mutex and just accesses  p.peerAddresses
- getSequencer is where the error Cause: failed to find sequencer - sequencer address not known is issued.

Fix peerAddresses mutex

---

.github/workflows/manual-deploy-testnet-l1.yml

Fixes deployment of the L1 into testnet

Remove extraneous hyphen

---

go/host/p2p/p2p.go

We were seeing errors because the requester ID on batch requests was wrongly set to the host bind address (often 0.0.0.0) instead of the host public address.

P2P requests: fix to use public address instead of bind address as request sender

---

.github/workflows/build-pr.yml

Changed test timeout.

---

go/enclave/components/batch_executor.go
go/enclave/components/rollup_consumer.go
go/enclave/enclave.go
go/enclave/storage/storage.go
go/ethadapter/geth_rpc_client.go
go/host/enclave/guardian.go
go/host/host.go
go/host/l2/batchrepository.go
go/host/rpc/clientapi/client_api_eth.go
go/host/rpc/clientapi/client_api_filter.go
go/host/rpc/enclaverpc/enclave_client.go
go/rpc/encrypted_client.go
tools/obscuroscan/obscuroscan.go

some log messages are not at the right severity level.
- changes severity level of some messages

tweak log messages

---

go/enclave/rpc_server.go
go/host/enclave/guardian.go
go/host/rpc/clientapi/client_api_eth.go

Make sure we don't swallow enclave system errors
log errors

log errors

---

go/host/enclave/guardian.go

fix logging bug

---

go/enclave/enclave.go
go/enclave/events/subscription_manager.go

- the relevancy check is relatively expensive and was executed unnecessarily
- apply the relevancy check after the filtering
- extract the user addresses from an event lazy, only when necessary
- clarify the logic
- improve logging to help diagnose issue

optimise the relevancy check and improve logging

---

go/host/p2p/p2p.go

Probably not an issue, but if P2P service is stopped we should abandon any threads that are trying to refresh the peer list.
- Update P2P stopper to use atomic.Bool as more convenient
- Have refresh p2p list bail out if service is stopped while it is retrying

Update p2p stopping mechanism

---

go/enclave/storage/storage.go

Trying to identify what is causing the enclave batch creation to be very slow
This is heavy handed but easy to remove or downgrade and will help us pin down db usage problems

Debugging: add timer to all storage calls

---

go/enclave/storage/enclavedb/config.go
go/enclave/storage/init/edgelessdb/edgelessdb.go
go/enclave/storage/init/migration/README.MD
go/enclave/storage/init/migration/db_migration.go
go/enclave/storage/init/sqlite/sqlite.go

We want to be able to update the db schema without wiping the data.
Added very basic db migration. See readme

add very primitive db migration mechanism.

---

.github/workflows/manual-deploy-testnet-l2.yml
.github/workflows/manual-upgrade-testnet-l2.yml
go/node/cmd/cli.go
go/node/cmd/cli_flags.go
go/node/cmd/main.go
go/node/config.go
go/node/docker_node.go
testnet/launcher/docker.go

https://github.com/obscuronet/obscuro-internal/issues/2098
Adds log level to the deployments, node and launcher

Add loglevel flag

---

.github/workflows/manual-deploy-obscuro-gateway.yml

Websocket connection is not working on the hosted gateway
Opened a port used by ws

Open port 3002 on gateway for websockets

---

go/host/enclave/guardian.go

Guardian doesn't need to stop controls. For a brief period while stopping one of them was stopped and the other still running so the main loop was spinning in confusion and spamming out logs.
Remove the running flag now we have stop interrupter.

Enclave guardian: remove superfluous running flag

---

go/common/tracers/debug_logs.go
integration/simulation/network/socket.go

https://github.com/obscuronet/obscuro-internal/issues/2111

Fix the event relevancy fields

---

.github/workflows/manual-upgrade-testnet-l2.yml

Temporarily disable the scheduled upgrade

Disable the upgrade scheduled

---

.github/workflows/manual-deploy-obscuro-gateway.yml
tools/walletextension/config/config.go
tools/walletextension/container/walletextension_container.go
tools/walletextension/main/cli.go
tools/walletextension/storage/database/001_init.sql
tools/walletextension/storage/database/mariadb.go
tools/walletextension/storage/storage.go
tools/walletextension/storage/storage_test.go
tools/walletextension/test/utils.go

https://github.com/obscuronet/obscuro-internal/issues/2156
- Adds a couple of flags to the OG
- Allows to connect to mariadb
- update the deployment to connect to mariadb

OG now can connect to mariadb

---

.github/workflows/manual-deploy-dev-obscuroscan.yml
.github/workflows/manual-deploy-obscuro-scan-2.yml
.github/workflows/manual-deploy-obscuroscan.yml
.github/workflows/manual-deploy-testnet-faucet.yml
.github/workflows/runner-scripts/wait-node-healthy.sh
README.md
docs/_docs/testnet/essentials.md
docs/_docs/wallet-extension/wallet-extension.md
integration/manualtests/client_test.go
integration/networktest/env/network_setup.go
tools/faucet/cmd/cli.go
tools/obscuroscan/main/cli.go
tools/obscuroscan_v2/backend/cmd/cli.go
tools/walletextension/container_run.sh

https://github.com/obscuronet/obscuro-internal/issues/2178
As discussed offline

Update Tesnet dns

---

testnet/launcher/docker.go

Add missing interval configs to testnet launcher

---

.github/workflows/manual-deploy-testnet-l2.yml
.github/workflows/manual-upgrade-testnet-l2.yml

Broke the yaml with this strange copy-paste error.

Fix GH yaml typo

---

.github/workflows/manual-deploy-obscuro-gateway.yml

After changing URLs for node and gateway it was not yet updated in github action.
Update node urls

Obscuro Gateway update node urls

---

.github/workflows/manual-deploy-obscuro-gateway-database.yml
.github/workflows/manual-deploy-obscuro-gateway.yml

- We need to deploy Obscuro Gateway for Sepolia Testnet
https://github.com/obscuronet/obscuro-internal/issues/2207

Deploy Obscuro Gateway for Sepolia testnet

---

testnet/launcher/docker.go
testnet/launcher/l2contractdeployer/cmd/main.go

This config stuff is impossible

Fix config wiring at one of the layers for faucet

---

go/enclave/enclave.go
go/enclave/evm/evm_facade.go

Added stopwatches in important functions.

---

.github/workflows/manual-deploy-testnet-l2.yml

Bumping tesnet to 32gb

---

.github/workflows/manual-deploy-testnet-l1.yml

Add bridge test acc to prefunded list for Moray

Add prefunded L1 bridge address for dev and uat testing

---

integration/manualtests/connection_test.go
integration/obscurogateway/obscurogateway_test.go
tools/walletextension/lib/README.md
tools/walletextension/lib/client_lib.go

https://github.com/obscuronet/obscuro-internal/issues/2275
- Creates a library for using obscuro gateway programatically
- Enables the obscuro gateway integration test

Library for obscuro gateway

---

.github/workflows/manual-deploy-obscuro-gateway-database.yml
.github/workflows/manual-deploy-obscuro-gateway.yml

Update og namings in the GH

---

tools/walletextension/accountmanager/account_manager.go

to fix race condition on accounts
add mutex

add mutex for accts

---

docs/_docs/testnet/changelog.md

Change log entries for the v0.19 release

Add in change log for the v0.19 release

---

.github/workflows/manual-deploy-obscuro-gateway-database.yml
.github/workflows/manual-deploy-testnet-l2.yml

Was checking usages when deleting vars on github and found these two that got missed.

Missed a couple of vars on the rename

---

integration/contractdeployer/contract_deployer_test.go
integration/faucet/faucet_test.go

Seems to be a collision on the ports assigned to some of the tests

fix test ports

---

go/common/headers.go
go/common/headers_test.go
go/host/rpc/clientapi/client_api_eth.go

Fix for https://github.com/ten-protocol/ten-internal/issues/2477
replace big.Int with hexutil.Big

fix json serialisation for batch

---

go/enclave/components/batch_executor.go

Cherry pick #1698  over from main

Enclave: produce no batch if all tx failed (#1698)

---

tools/walletextension/common/common.go
tools/walletextension/wallet_extension.go

Log all requests in the gateway to the file for debugging purposes

add basic file logging in the gateway

---

go/config/enclave_config.go
go/node/docker_node.go
integration/simulation/devnetwork/node.go
integration/simulation/network/network_utils.go

[Config] Upgrade batch size limit

---

go.mod
go/common/cache_util.go
go/enclave/core/rollup.go
go/enclave/enclave.go
go/enclave/storage/storage.go

Attempt to improve performance by adding more caching and increasing some settings
- added a new cache for the batch height
- increased the statedb cache config memory
- some minor refactoring and checks on the cache util

tweak caching

---

go/config/enclave_cli_flags.go
go/node/docker_node.go
integration/common/constants.go
integration/simulation/devnetwork/node.go
integration/simulation/network/network_utils.go

[Config] Update batch size limit

---

contracts/package.json

[Hardhat] Fix for incompatible hardhat-deploy version

---

contracts/deployment_scripts/bridge/001_deploy_bridge.ts
contracts/deployment_scripts/messenger/layer1/001_deploy_cross_chain_messenger.ts
contracts/deployment_scripts/messenger/layer2/001_deploy_cross_chain_messenger.ts

Cherry-pick the contract addresses commit to release branch.

Contract deployers: configure signer for address publishing (#1676)

---

.github/workflows/manual-deploy-ten-scan.yml
tools/walletextension/frontend/src/services/useGatewayService.ts

[TG] Copy update

---

tools/walletextension/wallet_extension.go

Create a shallow copy of cached values to prevent errors

create a shallow copy of a map before modifying it

---

go/enclave/rpc/EstimateGas.go

Overestimate.

---

go/enclave/enclave.go
go/enclave/rpc/EstimateGas.go
go/enclave/rpc/rpc_encryption_manager.go

migration of https://github.com/ten-protocol/go-ten/pull/1826 to main

Estimage gas perf fixes

---

go/config/enclave_cli_flags.go
go/node/docker_node.go
integration/common/constants.go
integration/simulation/devnetwork/node.go
integration/simulation/network/network_utils.go

Updated batch size limit.

---

tools/walletextension/frontend/src/components/head-seo.tsx

https://github.com/ten-protocol/ten-internal/issues/3139
To prove we own the site
added a meta tag with the Beagle security signature

Add Beagle Security meta tags

---

tools/walletextension/frontend/src/components/head-seo.tsx

Build error during the  `Build and Push Docker Image` step
To ignore the type error caused by the signature attribute on the meta tag for Beagle Security.

fix build error

---

tools/tenscan/frontend/src/components/modules/common/copy.tsx
tools/tenscan/frontend/src/components/modules/common/truncated-address.tsx
tools/tenscan/frontend/src/components/ui/badge.tsx
tools/tenscan/frontend/styles/globals.css

https://github.com/ten-protocol/ten-internal/issues/3172

Update brand colors

---

tools/tenscan/frontend/package-lock.json
tools/tenscan/frontend/pages/batches/[hash].tsx
tools/tenscan/frontend/pages/batches/index.tsx
tools/tenscan/frontend/pages/blocks/index.tsx
tools/tenscan/frontend/pages/transactions/index.tsx
tools/tenscan/frontend/src/components/modules/batches/batch-details.tsx
tools/tenscan/frontend/src/components/modules/batches/columns.tsx
tools/tenscan/frontend/src/components/modules/blocks/columns.tsx
tools/tenscan/frontend/src/components/modules/common/data-table/data-table-pagination.tsx
tools/tenscan/frontend/src/components/modules/dashboard/index.tsx
tools/tenscan/frontend/src/components/modules/dashboard/recent-batches.tsx
tools/tenscan/frontend/src/components/modules/dashboard/recent-blocks.tsx
tools/tenscan/frontend/src/components/modules/dashboard/recent-transactions.tsx
tools/tenscan/frontend/src/components/modules/personal/columns.tsx
tools/tenscan/frontend/src/components/modules/personal/index.tsx
tools/tenscan/frontend/src/components/modules/transactions/columns.tsx
tools/tenscan/frontend/src/lib/utils.ts

https://github.com/ten-protocol/ten-internal/issues/3196 - Format numbers with commas
- Added a utility function to format numbers with commas
- Used the utility function to format numbers in the UI

[Tenscan] Add `formatNumber` utility function to display numbers with commas

---

go/enclave/enclave.go
lib/gethfork/debug/flags.go

the logging is verbose and it slows down ci
- only print to the file

fix logging - remove the terminal when a file is specified

---

tools/tenscan/frontend/src/components/layouts/header.tsx

https://github.com/ten-protocol/ten-internal/issues/3329
Logo is not visible in light mode
update relative path for the logo in header component

Update logo image path in header component

---

.github/workflows/manual-deploy-testnet-validator.yml
.github/workflows/manual-upgrade-testnet-l2.yml
integration/tenscan/tenscan_test.go

Postgres host config to upgrade script

---

go/common/subscription/utils.go

close ticker

---

tools/tenscan/backend/webserver/webserver_routes_items.go
tools/tenscan/frontend/api/general.ts
tools/walletextension/frontend/src/api/general.ts

use GET request for `/info/health/` like with other endpoints 

change /info/health/ from post to get

---

go/common/errutil/errors_util.go
go/enclave/nodetype/common.go
go/host/enclave/guardian.go

Disable error log when no batches are produces between bundles

---

go/common/errutil/errors_util.go
go/enclave/nodetype/common.go
go/host/enclave/guardian.go

Fixing log spam. (#1931)

---

go/enclave/txpool/txpool.go

https://github.com/ten-protocol/ten-internal/issues/3426

Enclave: fix panic on uninitialised mempool

---

go/host/enclave/guardian.go

Temporary disable xchain messages

disable xchain message submission

---

.github/workflows/manual-deploy-dexynth-gateway.yml

Fix for Dexynth Gateway deployment

---

go/common/query_types.go
go/host/enclave/guardian.go
go/host/storage/hostdb/batch.go
go/host/storage/hostdb/block.go
go/host/storage/hostdb/rollup.go
go/host/storage/hostdb/rollup_test.go
go/host/storage/hostdb/sql_statements.go
go/host/storage/hostdb/transaction.go
go/host/storage/hostdb/utils.go
go/host/storage/init/postgres/001_init.sql
go/host/storage/init/sqlite/001_init.sql
go/host/storage/interfaces.go
go/host/storage/storage.go

We hit performance issues on the host database when inserting lots of transactions
- remove the random pk of the transaction table
- batch insert transactions
- other small fixes to optimize indexing on random values

host db performance fixes

---

go/enclave/storage/enclavedb/events.go
go/enclave/storage/events_storage.go

Trying to set lifecycle_event flag on topic table instead of event type table.

Fix event sql query

---

go/common/subscription/new_heads_manager.go
tools/walletextension/rpcapi/blockchain_api.go

we were returning a Ten header on an Ethereum RPC
- convert to ethereum types

fix getBlock RPC

---

go/enclave/events/subscription_manager.go
go/enclave/nodetype/common.go
go/enclave/rpc/GetTransactionReceipt.go
go/enclave/storage/enclavedb/events.go
go/enclave/storage/interfaces.go
go/enclave/storage/storage.go

Reverts ten-protocol/go-ten#1988

Revert "Refactor event log filtering for subscriptions"

---

.github/workflows/manual-deploy-dexynth-gateway.yml

disable rate limiting for dexynth gateway

---

tools/walletextension/ratelimiter/rate_limiter.go

fix concurrency issue in SumComputeTime

---

changelog.md

Add in the change log for v0.27

---

go/common/tracers/debug_logs.go
go/enclave/storage/enclavedb/events.go
go/enclave/storage/events_storage.go

To help debug event visibility issues
- add more fields to the log debug endpoint
- small clarification refactor 

improve debug_logs

---

integration/tengateway/tengateway_test.go
tools/walletextension/rpcapi/debug_api.go
tools/walletextension/rpcapi/utils.go

To finalise the debug relevancy functionality
- basic wiring 

wire debug event relevancy in gateway

---

.github/workflows/manual-deploy-ten-bridge.yml
tools/bridge-frontend/src/lib/utils/index.ts

Update bridge host

---

tsconfig.json

update ts config relative path

---

go/enclave/storage/enclavedb/events.go

Merged https://github.com/ten-protocol/go-ten/pull/2075 with a bug
fix

fix table alias name

---

go/enclave/storage/cache_service.go
go/enclave/storage/storage.go

there is contention on the `tx` table during normal operation when there are lots of txs
- cache the last few batches

cache few batches

---

go/enclave/enclave.go
go/enclave/evm/ethchainadapter/eth_chainadapter.go
go/enclave/genesis/genesis_test.go
go/enclave/storage/cache_service.go
go/enclave/storage/enclavedb/block.go
go/enclave/storage/events_storage.go
go/enclave/storage/storage.go
go/enclave/txpool/txpool.go
go/host/enclave/guardian.go
integration/ethereummock/gethutil.go
integration/ethereummock/node.go
integration/smartcontract/debug_wallet.go
integration/smartcontract/smartcontracts_test.go

our tests have become very flaky
Lots of small changes. Please see the messages in the file

small flakyness fixes

---

go/enclave/l2chain/l2_chain.go
go/enclave/storage/cache_service.go
tools/walletextension/cache/RistrettoCache.go

We have a memory leak.
It's most likely due to the blanket caching
Fine-tune cache settings per functionality

tweak cache

---

go/config/defaults/0-base-config.yaml
go/config/defaults/sim/1-env-sim.yaml
integration/simulation/network/socket.go

Remove sim sysout logs

---

go/host/l1/blobresolver_test.go
integration/simulation/simulation_full_network_test.go

when you search for fails in build PR this shows up
* logging only 

Fix annoying blob test skip message

---

go/common/enclave.go
go/enclave/enclave.go
go/enclave/enclave_admin_service.go
go/enclave/enclave_init_service.go
go/enclave/enclave_rpc_service.go
go/enclave/restore_statedb.go

The "enclave.go" file has too many responsibilities, and it's hard to reason about.
This PR is a plain split. No real logic changes

split the enclave file into responsibilities

---

go/enclave/enclave.go
go/enclave/enclave_admin_service.go
go/enclave/enclave_init_service.go
go/enclave/enclave_rpc_service.go
go/enclave/nodetype/interfaces.go

HA - we need to swap the node type
- limit responsibilities of the services

HA - re-arrange enclave services

---

integration/tengateway/tengateway_test.go

rate limiting test is causing some flakiness and should be disabled

disable rate limiting gateway test

---

.github/workflows/manual-deploy-obscuro-gateway.yml

with missing backslash parameters after it are ignored and this PR fixes that

fix missing backslash in deployment script

---

.github/workflows/manual-deploy-ten-gateway-frontend.yml

reverted GW-FE build and deploy action

reverted GW-FE build and deploy action

---

go/enclave/gas/oracle.go

Gas pricing needs to take into account the proper fee for the blobs rather than the calldata base fee

Updated gas pricing.

---

tools/walletextension/storage/database/cosmosdb/cosmosdb.go

If the same user wants to add 2 users at the same time / quick succession we have a race condition and we only write on the of new values (the first one) to the database.
- new `updateUserWithRetries` function performs a read–mutate–write with ETag checks in a loop..
If a “Precondition Failed” response arises due to an ETag mismatch, the code now re-reads the latest user data, merges changes, and retries the write, ensuring both updates are preserved.

ETag based retry logic for user updates

---

go/enclave/crosschain/processors.go

patch to fix a potential NPE
- nil check

patch NPE for EnclavePublicConfig

---

go/enclave/nodetype/sequencer.go
go/enclave/storage/interfaces.go
go/enclave/storage/storage.go

remove dead code

---

tools/walletextension/rpcapi/utils.go

Gateway fix nil in estimate_gas

---

contracts/deployment_scripts/funding/layer1/001_fund_accounts.ts
contracts/deployment_scripts/funding/layer1/002_fund_faucet.ts
contracts/deployment_scripts/messenger/layer1/001_deploy_cross_chain_messenger.ts
contracts/deployment_scripts/messenger/layer2/001_deploy_cross_chain_messenger.ts
contracts/deployment_scripts/testnet/layer1/001_add_bridge_admin.ts
testnet/launcher/l2contractdeployer/docker.go

This reverts commit f958302864a8e8b13d9ea1dfdfce00e87d5209e5.

Revert "Deployment script fixes (#2286)"

---

tools/walletextension/rpcapi/blockchain_api.go
tools/walletextension/rpcapi/utils.go

Fix nil pointer in estimate_gas and handle nil in audit function

---

go/enclave/gas/gas.go
go/enclave/gas/oracle.go
go/host/l1/publisher.go
integration/smartcontract/smartcontracts_test.go
tools/walletextension/rpcapi/utils.go
tools/walletextension/services/wallet_extension.go

The transition to pricing txs using  blobs was complete.

fix gas calculation

---

go/config/defaults/0-base-config.yaml

update base fee

---

go/config/defaults/0-base-config.yaml

Reduce min gas fee in line with the base fee

Fix min price

---

changelog.md

Final last changes into the change log for the 1.0.0 release

Update for additional prs

---

go/ethadapter/utils.go

add retry for normal txs

---

.github/workflows/manual-upgrade-testnet-l2.yml

It was missing in the upgrade workflow

add DOCKER_API_VERSION=1.45

---

.github/workflows/manual-upgrade-testnet-l2.yml

Need ampersands to avoid export syntax err

script typo

---

go/enclave/components/sigverifier.go

temporary removal of the rollup sig check

remove sig check

---

.github/workflows/manual-recover-network-funds.yml

pin docker api version (same fix as other GH action scripts)

Recover funds: pin docker api version for compatibility

---

go/host/l1/publisher.go

The log message was showing nil values
* return the pricedTx from `executeTransaction` so we can log the values

Fix max retries blob log message

---

go/ethadapter/utils.go

increase base fee

---

.github/workflows/manual-deploy-obscuro-gateway.yml
.github/workflows/manual-deploy-ten-gateway-frontend.yml

Deploying gateway needs minor modifications in order to work as expected.

minor fixes for gateway deployment

---

go/host/rpc/enclaverpc/enclave_client.go

bump rollup timeout

---

go/enclave/gas/gas.go
go/enclave/gas/oracle.go

- clarify the naming of the gas calculation
- add share of the L1 tx

clarify gas calculation and add cost of L1 tx

---

go/host/l1/publisher.go

NPE in UAT logs last night
* Add a nil check and return an error if so

Fix NPE on pricing blob txs

---

.github/workflows/build-gateway-lib.yml
.github/workflows/build-pr.yml
.github/workflows/golangci-lint.yml
.github/workflows/hardhat-pr-check.yml

add pr gates to release branch

add pr gates to release branch

---

go/enclave/evm/evm_facade.go
go/enclave/evm/interfaces.go
go/enclave/gas/oracle.go
go/enclave/l2chain/interfaces.go
go/enclave/l2chain/l2_chain.go
go/enclave/rpc/EstimateGas.go
go/enclave/rpc/TenEthCall.go

we were returning system errors when we should have been returning user errors
- return the user errors

fix errors

---

contracts/scripts/test-eth-call.ts
go/enclave/evm/evm_facade.go
go/enclave/rpc/EstimateGas.go
go/enclave/rpc/TenEthCall.go

We had some issues with internal server errors being hit by estimate gas and eth call, this should address them.
Cleaned up a bit user vs system errors. 

Fix gas price

---

.github/workflows/build-gateway-lib.yml
.github/workflows/build-pr.yml
.github/workflows/golangci-lint.yml
.github/workflows/hardhat-pr-check.yml
contracts/scripts/test-eth-call.ts
go/enclave/components/batch_executor.go
go/enclave/evm/evm_facade.go
go/enclave/evm/interfaces.go
go/enclave/gas/oracle.go
go/enclave/l2chain/interfaces.go
go/enclave/l2chain/l2_chain.go
go/enclave/rpc/EstimateGas.go
go/enclave/rpc/GetPersonalTransactions.go
go/enclave/rpc/TenEthCall.go
go/enclave/rpc_server.go
go/enclave/storage/enclavedb/batch.go
go/enclave/storage/enclavedb/block.go
go/enclave/storage/storage.go
go/host/l1/publisher.go
go/host/storage/init/postgres/postgres.go
go/host/storage/storage.go

Merge in fixes from the release branch

Merge release branch

---

go/config/defaults/0-base-config.yaml
go/enclave/components/batch_executor.go
go/enclave/core/batch.go
go/enclave/rpc_server.go

- Bump the l2 gas limit because it includes the l1 amount

bump l2 gas limit

---

go/common/host/host.go
go/common/host/services.go
go/enclave/components/batch_executor.go
go/enclave/components/interfaces.go
go/enclave/components/rollup_compression.go
go/enclave/enclave.go
go/enclave/evm/evm_facade.go
go/enclave/nodetype/sequencer.go
go/enclave/restore_statedb.go
go/enclave/rpc/TenStorageRead.go
go/enclave/storage/enclavedb/batch.go
go/enclave/storage/interfaces.go
go/enclave/storage/storage.go
go/host/host.go
go/host/l2/batchrepository.go
go/host/rpc/clientapi/client_api_chain.go

Merge fixes from the release branch

Tudor/merge release 

---

testnet/launcher/docker.go

Merge the fix for underlying gas price race condition in releases

Fix for race condition. (#2353)

---

go/host/l1/dataservice.go

fix bug when receiving l1 blocks

fix l1 stream

---

integration/simulation/simulation.go

Couple of odd things I bumped into while trying to get in-memory tests to behave consistently for my failure.

Sims: minor clean-ups to help with debugging

---

integration/simulation/devnetwork/dev_network.go
integration/simulation/devnetwork/node.go
tools/walletextension/httpapi/routes.go

Some fixes that start up local network.

---

testnet/eth2network.Dockerfile

Merge release

---

go/enclave/storage/init/edgelessdb/edgelessdb.go

Panic on db "connection failed" error to kill the enclave when the db dies.
create a custom driver

panic on db error

---

.github/workflows/build-pr.yml
go.mod
go/config/config.go
testnet/launcher/docker.go
testnet/launcher/l2contractdeployer/config.go
testnet/launcher/l2contractdeployer/docker.go

https://github.com/ten-protocol/ten-internal/issues/4698
* Deep copy config, replace pk string with **** and log the copy

Obfuscate private keys from logs 

---

integration/simulation/network/geth_utils.go
integration/simulation/network/inmemory.go
integration/simulation/network/network_utils.go
integration/simulation/network/obscuro_node_utils.go

Intermittent PR build failures when deploying the contracts
* Add a check to call `CodeAt` after contract deployment to make sure we can grant state root permission

Fix intermittent deployment failures on PR build

---

go/enclave/core/utils.go
go/host/enclave/service.go
go/host/l1/publisher.go
go/host/storage/hostdb/batch.go

My copilot was drunk at the wheel...

Host: fix missing '?' in sql query

---

contracts/src/ten_erc20/TENToken.sol
contracts/src/ten_erc20/readme.md

The solidity for the TEN token

add TEN token

---

.github/workflows/manual-decommission-testnet-l1.yml
.github/workflows/manual-decommission-testnet-l2.yml

Protect the filter command which feeds into xargs for the az resource deletion

Protect the filter command which feeds into xargs for the az resource deletion 

---

go/host/l1/publisher.go

The sequencer node can enter a state where it isn't able to publish any l1 transaction because of a contract failure
- handle contract errors in gas estimation as final errors and exit the loop
- remove generic "publish" function

improve l1 publishing reliability

---

README.md

docs: fixed broken link

---

.github/workflows/manual-deploy-obscuro-gateway.yml
integration/networktest/env/network_setup.go
integration/simulation/devnetwork/dev_network.go
integration/tengateway/tengateway_test.go
testnet/launcher/gateway/docker.go
tools/walletextension/README.md
tools/walletextension/common/config.go
tools/walletextension/httpapi/routes.go
tools/walletextension/keymanager/keymanager.go
tools/walletextension/main/cli.go
tools/walletextension/main/main.go
tools/walletextension/rpcapi/filter_api.go
tools/walletextension/rpcapi/utils.go
tools/walletextension/services/utils.go
tools/walletextension/services/wallet_extension.go

We had issues with too many logs causing issues.
- Logs for each request were removed as they are not needed.

Remove excessive logging from the gateway

---

go/common/gethencoding/geth_encoding.go
go/enclave/components/batch_executor.go
go/enclave/enclave_admin_service.go
go/enclave/evm/evm_facade.go
go/enclave/nodetype/sequencer.go
go/enclave/rpc/vk_utils.go
go/enclave/storage/enclavedb/batch.go
go/host/enclave/service.go

To help diagnose an error we keep seeing on sepolia
- improve error messaging and tracing
- minor consistency correction when storing hashes

improve error reporting

---

testnet/launcher/l1upgrade/cmd/main.go

* Fix some copy pasta log messages

L1 upgrade script log message fixes

---

tools/tenscan/frontend/src/components/modules/dashboard/recent-transactions.tsx

fix tenscan frontend issue no txs

---

tools/tenscan/frontend/src/components/modules/dashboard/recent-transactions.tsx

Without this change we see 500 page not found error in Tenscan if we for some reason cannot get the transactions.

fix empty transactions issue on tenscan frontend (#2476)

---

tools/walletextension/rpcapi/blockchain_api.go

Remove todo to make it less confusing.

no need for GetCode to be authenticated

---

.github/workflows/build-gateway-images.yml

build gateway images for kubernetes deployment

---

contracts/scripts/upgrade/001_upgrade_contracts.ts

Fix l1 upgrade script console logs 

---

testnet/launcher/l1upgrade/docker.go

Hard to read the logs
* Reverted back to the standard format used by the other docker container scripts

Remove upgrade script hacky logging

---

go/config/defaults/0-base-config.yaml

Broken e2e tests
* Reduced interval time 

Update testnet default rollup retry interval

---

go/host/rpc/clientapi/client_api_scan.go
go/host/storage/interfaces.go
go/host/storage/storage.go
go/obsclient/obsclient.go
go/rpc/client.go
integration/tenscan/tenscan_test.go
packages/ui/components/common/clickable-link.tsx
tools/tenscan/backend/obscuroscan_backend.go
tools/tenscan/backend/webserver/webserver_routes_items.go
tools/tenscan/frontend/src/components/modules/transactions/columns.tsx
tools/tenscan/frontend/src/routes/index.ts

Dead links on the FE & inconsistencies. 
* New get batch by sequencer number API 
* Fix broken links to incorrect API on FE

Tenscan Fixes - Broken batch sequence links 

---

.github/workflows/manual-deploy-testnet-l2.yml

Fix prefund config field name so it matches the expected one from `go/config/deployment.go`.

Deploy: fix dev faucet prefund

---

tools/tenscan/frontend/src/components/modules/rollups/rollup-details.tsx

https://github.com/ten-protocol/ten-internal/issues/5023
* null-safe get on xchain messages as they are often null

Tenscan - Fix view rollup page

---

go/enclave/storage/init/edgelessdb/001_init.sql

Add index to speed up event query

add auto_public index

---

tools/walletextension/httpapi/routes.go

Frequent requests to health and network configuration endpoints can cause high load on the system. We can fix that with caching.
- Added short-living cache to `healthRequestHandler` and `networkHealthRequestHandler` to reduce repeated health check calls
- Added long-living cache to `networkConfigRequestHandler` since network configuration rarely changes

add cache to gw endpoints

---

contracts/package.json
go/enclave/rpc/GetPersonalTransactions.go
go/enclave/storage/enclavedb/batch.go
go/enclave/storage/enclavedb/event_filter.go
go/enclave/storage/enclavedb/personal_txs.go
go/enclave/storage/init/edgelessdb/002_init.sql
go/enclave/storage/init/migration/db_migration.go
go/enclave/storage/init/sqlite/002_init.sql
go/enclave/storage/storage.go
integration/tengateway/tengateway_test.go
tools/walletextension/httpapi/routes.go

port to 1.4 of https://github.com/ten-protocol/go-ten/pull/2564/

Tudor/pers tx perf 1.4

---

integration/networktest/env/network_setup.go

Network tests: update dev and sepolia test config

---

go/host/l1/blobresolver.go
tools/tenscan/frontend/src/components/modules/personal/columns.tsx

* move tx hash column to first col as this is essentially the ID 

Tenscan - Personal tx table fixes

---

go/enclave/system/hooks.go

Removed stale checks.

---

tools/walletextension/enclave.Dockerfile

fixed path. https://github.com/ten-protocol/go-ten/actions/runs/17433908433

fix part for Azure HMS in gw docker

---

contracts/config/networks.json

fix chainID in networks

---

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml
contracts/hardhat.config.ts
contracts/package.json
testnet/launcher/l2contractdeployer/config.go
testnet/launcher/l2contractdeployer/docker.go
tools/hardhatdeployer/scripts/entrypoint.sh

Multiple fixes for chainID.
Successful run here: https://github.com/ten-protocol/go-ten/actions/runs/17532334185

Fix deploying testnet with a different chainID

---

testnet/launcher/docker.go
testnet/launcher/gateway/config.go
testnet/launcher/gateway/docker.go

Ziga/fix local testnet gw chainID

---

.devcontainer/devcontainer.json
go/enclave/components/batch_executor.go
go/enclave/crosschain/message_bus_manager.go

Messages were not being unwrapped properly in order to burn the correct amount from the bridge

Fix for decoding of value transfers

---

go/enclave/storage/init/edgelessdb/002_unique_ky.sql

increase timeouts (#2670)

---

go/enclave/storage/events_storage.go

Currently, the sequencer crashes when a contract is deployed with an invalid visibility config. 
Instead of crashing, just ignore the config

Fix visib config bug. In case of error, just ignore the wrong config

---

go/config/defaults/0-base-config.yaml
go/config/host.go
go/host/config/config.go
go/host/rpc/clientapi/client_api_scan.go
go/host/storage/db_init.go
go/host/storage/hostdb/batch.go
go/host/storage/hostdb/transaction.go
go/host/storage/init/postgres/003_init.sql
go/host/storage/init/sqlite/003_init.sql
go/host/storage/interfaces.go
go/host/storage/storage.go
go/obsclient/obsclient.go
go/rpc/client.go
integration/simulation/network/socket.go
integration/tenscan/tenscan_test.go
tools/tenscan/backend/tenscan_backend.go
tools/tenscan/backend/webserver/webserver_routes_counts.go
tools/tenscan/frontend/api/transactions.ts
tools/tenscan/frontend/src/routes/index.ts

Add historical tx endpoint to 1.5 for sepolia.
* cherry picked dff6943323e949275853e2fc949e812e363a707a

Merge historical tx count table into releases/1.5 (#2665)

---

go/enclave/components/batch_registry.go
go/enclave/nodetype/sequencer.go
go/ethadapter/blob.go
go/ethadapter/blob_beacon_client_test.go

Debug logging to blob encoding

---

.github/workflows/manual-deploy-k8s-testnet-after-nodes.yml
.github/workflows/manual-deploy-k8s-testnet-before-nodes.yml
.github/workflows/manual-deploy-testnet-l2.yml
.github/workflows/manual-l1-contracts-multisig-setup.yml
.github/workflows/manual-l1-contracts-multisig-upgrade.yml
.github/workflows/manual-pause-all-contracts.yml
.github/workflows/manual-transfer-unpauser-roles.yml
.github/workflows/manual-upgrade-l1-contracts.yml

* Run out of artifact storage
* Move all down to 1 or 2 days depending on importance

Remove all 7 day retention periods

---

tools/walletextension/walletextension_container.go

https://github.com/ten-protocol/ten-internal/issues/5704
Add defensive HTTP response headers to wallet extension + restrict port 80 to ACME HTTP-01 challenges only; 301-redirect all other requests to HTTPS.
After deploying to UAT we can see the difference:
```
➜  ten-examples git:(main) curl -I https://rpc.uat-gw-testnet.ten.xyz/v1/network-health/
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Security-Policy: frame-ancestors 'none'
Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), accelerometer=(), gyroscope=(), magnetometer=(), fullscreen=(), autoplay=()
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff …
```

Add secure HTTP headers

---

tools/walletextension/lib/client_lib.go

When deploying l2 on UAT and other network we want to use the ENV variable set for the chainID.
If env variable is not present we can default to local testnet.
successful run: https://github.com/ten-protocol/go-ten/actions/runs/18195378655

read chainID from env variable and use hardcoded as fallback
